package my.project.advent.of.code.y2020;

import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.SortedSet;

import org.junit.Test;

import my.project.advent.of.code.utils.Utils;

public class Day6 {

	@Test
	public void test() {
		List<String> input = Arrays.asList("edmzkxfoprcnhijtyvladxntojykfcvzermplh",
				"jbhpksufcatyhevsuaibjktjbusytghak",
				"ixpckvbrylgtdmhpyojlsgibtvc",
				"sgasaggsraawzgssga",
				"jnwcqfisokbgmtjmtcubwnskbmwkctjsrn",
				"ekxwotiyfhagdlmqnhpvedxwscgqjlkrf",
				"drtguxboeuxotwejgibfdrnrkgxbtaeoupdkohedbgzurtx",
				"diwhdgdd",
				"pukeyxjrvmowtaejyxrwopkhtuupojtrxyekwcjxubkyetrowptgxwyorqnejiufzkp",
				"nqbratyybrqnaqyanbrayrqbnaynqbr",
				"ezljbkmhionfqvhxvtnjqr",
				"fuwsngzivcjrkkprjnfucziv",
				"wonvukglswkoslgvunkusvtolgnw",
				"tieldgxmysdilexmyrvsqjdlxyiemssylxeimd",
				"gfapnyrzlwhscjmixbyramfspwnicghblxzjrnwmehkbjzpalgyfiscqjfyclgmabhrizvwpsngzsahifrytmjlnwpcb",
				"wfyrobghlqcjnyzwhfjlocgqmbnyqgojhlnwczfmbwhlozqfcmnjgby",
				"envihwzxsivswiwsv",
				"gjocrpmlhnkbxevdsztqrvoecmjbgndlswphzktqx",
				"phhphp",
				"vmzyftwkvtkfemzwytymfwkzvktfvwzmykwzvytmf",
				"yntcgdfblkzdykfcmnltbztmzdnylbfhck",
				"jyuwnazhbtrdvlfcoxmimlxowqarbhnitjfvcduyhvbjknialucoptxysmfgdwrfihbrodmtjcxvnwalyu",
				"xdicwhvujszagmeyczjrmdyauevwmuweycajzpvdvayjcwedumzuwyvcedazmj",
				"zqniybfcrrizunqtpcyfcqyizrnffirzchmlnqy",
				"ckezaduhtxoilynkliuytzonedaxulkxznteiydaouanxdpetzlyiwok",
				"opgmiufxdkwonfuxdwmgkifiwxmokdugpfdiumwyxgokfodxuywmigck",
				"fgzgfbufg",
				"zzeaz",
				"scwqjukmhplzxafiyvdtrmpwyerhvqzbfcdikxualstgkzrwpcfnqvxtiyuodlsam",
				"enztyzprnomcanslzqzonr",
				"xlsqjnuobfymtdobtueyxdjkciafqnlmz",
				"fcowyycfow",
				"timwqdnebkcsajpolrhycqduetictgyvidequfxiuecdtqviqetcdz",
				"atlqfdinogrbmdrgqxloektiambu",
				"jdjddj",
				"cknxalfwburopditehsyzwtigkfzlchsrnybuoxaepdvaponqfukzcsiybrljwedth",
				"rxhuzdrzhkxumtginjrcaxzohevyupszhreuxruxhzpy",
				"ceanhqvbtkgiplrmlpithvrkcaqng",
				"lageimuyjxntbwphfsgpnihamyelxbwsuyxmiswngulepabhwxsbnhpylmgaieuayximuwebhpnlgs",
				"begmvrkqptzhwsfjlxdciyaun",
				"prmkvejosyubtnzrkeoynmjavzspubthuomzbtnwyrepsjdvkebskrvtzjmyuopn",
				"ugmwobeiyqtckszvpaxnsivuazqotwxykcpmbgnheugovsircnmqztplwayxbkesxibehutwazpgqynkmvco",
				"gmfipesaykorxbwjlojlfpxwgrnikmeyhqsba",
				"cccm",
				"dapbveoarmnqopxhvieaptebovdvpoezaaotwfepsv",
				"iici",
				"pftbquhlydrspostnjxlihagdzbywce",
				"xcivfymjdrzhesqbfzrcmjhbsviqyxevimlnscfwxbyrhjqupeo",
				"fff",
				"usnhrmupglayuqvuqw",
				"ldbld",
				"sbrqvoulysroylqfqsryitoe",
				"wntmgqjauybzoldvfckgldqtkbaeznufwymcjlrchunbjgdykzawtqfmmcabflwtyqujngkdz",
				"rofcihkmqbwgtexjavnzqfagcjxkhmiotbvwnrezntkqjiyzvboafewhxrcmg",
				"bvtv",
				"wtvepsddyzhirjbqclkxnmguaof",
				"gzbtsreonmhxlkijpqukxhmltszqpnorujbige",
				"hpeakzrxymigovtvrtxgmkoyapzpgzrmvyoakxt",
				"lbygrmxoivfucwrcjivowfgblmxsrxoiamvclujbgwsfxvrfpibeclnmwotlofcxrivmwb",
				"jhxbfydcqwmsoagpirvktelz",
				"wczxsbnqezirqonwpbxenqwxsezb",
				"ydwoydpydaxdsvhjmfydy",
				"rxtujwdoahzrtsym",
				"pbicbcbcbc",
				"jxsbfrbcsrfjxsrixvdnbwzjrxmakbsjsxjmrabf",
				"wruifarfaarfasfrfra",
				"gyigiyaygainkigy",
				"tqoxhlhetqrmyxvtkqfdh",
				"ytkqvupmkpuqv",
				"jreztqmwvgisnhbyrhwtzedsq",
				"qjoojq",
				"xbhzsotugeijrkgkziyorjuxbepds",
				"kusymzbclghfquchlgfkzmybjurvyclihkm",
				"whvkxzmrlkrszxwvmhlzrmhlvwskxmkxrwylovhz",
				"sakfigdbafskgbkfagbs",
				"vnyouxwoynsbpznimgtna",
				"dqjtmskpzifyktjmeorfaipdpmatejdofkifjlpmidkrt",
				"hauldscwintdarhinunhdfuavir",
				"hinbmavocvirmshcazbhavkrcomibviabhmqc",
				"tawexmxmatew",
				"opggpogpoopgpog",
				"vkbznjquyqznuvkybkvuqznabyqkvuyzbnnqzyvkbu",
				"ocansuzdmvweihasyfpwqj",
				"vmjsknpejomvjchumg",
				"mhwshmswshwm",
				"tcpbdzvarixyjdxupoyqfwnkvesbh",
				"dmfomdgdm",
				"yzzjjzvlztahqfizg",
				"itvnmlxphycffzmcpvxhnitylclpfnhixvtym",
				"remigegustzcnbyeoielepag",
				"tzsnfhweuqvoybjimvxzmptudbrowfyneghcqywmlhaotnzfukvbqeqltpcbwvmeuazrfonyh",
				"hcytfwgvedycvepxlhzfngwsvwtcgyfhmewfgeyvhccyghwfev",
				"lzhbucqeczhlkpfzvhjyscxlitalzdqmgchn",
				"qyzgcumalwesqbqy",
				"guxcprsfqezajltmwdrqltsuzcgamxjfwepdjfmuzeswdqxalgrptcjtelwdfcrpagxsumzqiaqjxeyclgprwmzfsduth",
				"zcghqfuprlavsjbktxoidmenwycxbmwnlogdiqrhujpfsyzketavcnaugxstkhizjodpwrqlefbvym",
				"sgvfzhpfwnghspuipsfgahpuhfgns",
				"prtxkifmoyqwbdshiryxfhobqstkdmfmtkdsyqrioxhb",
				"irfcynskvcenorvkisjyfsrfkvynic",
				"njdshblezrfxfesodhrxnnqhiautvrscdwfenhdreslxf",
				"rceubuabflroszvxtkyqngd",
				"ewobrfqcspymmpqcwfsoyber",
				"klrxyafalrykfykaflrfakyrl",
				"ezqwmuawamqeuzeqmzawumqweazuzqweamu",
				"jkfqgzhlpwntmduoyscxbeaznflctasoqekmbwhxdujgpyleqakghpynzjcboudwxfsmitczuyjtdpfxlhakbeognmwqsskbqeydcjlfoazmputhnxwg",
				"haqvxtepiczsgymlkbwyusgxiaehlbzwmqcttqnxiylhmzcsgweabyiatzblcgxhmeswjq",
				"ogzmupysnrtlugmkypqizocnvrsyfurgmpnhzow",
				"pgrbopycugrtjrngadp",
				"swbkulnaopmkdrbqyzonicuj",
				"pfzlflpzvjzfpbelsfpzl",
				"yrboxuhknlwzcdbiurzxogajcpwylxblcywuohrzmrxfowylzubcclxqeurwzybok",
				"earvompikszrmsoieapkgekposamir",
				"mwvlrtaemlavlamiov",
				"oghqcsvlwqowhgvcysldhqewcgvoslglqhkpcsrvnftwox",
				"mpajysmywpjsjyspmvlpsymjsjpmy",
				"rebcoxbwcr",
				"uctgdqwxewctpdgjqxeuqryotwezfmgdixcueqxtwdaucg",
				"motajvxdinaxtduvoizjlpoxvgdsfyhawedvrocakx",
				"qorxjekqzpxjjqx",
				"nxlcnlx",
				"foiotvuxgouoxio",
				"gvjefxziadsjpbchuyw",
				"gvbhodiogbhivdhdvugbiogoihdbvigbvydho",
				"krdufhbgymvlxiqwepcoldxuyefjoqzmr",
				"sycnjnj",
				"qwiyzqwzgqkrwfzbqzawj",
				"bsaxxwabskmbxjas",
				"fqpazsenjukgoyiugznyxfqkaopesiqysokeapnuifzgepfaqiyugnsozk",
				"vrxpusdhtphuxsvbnahfyvpwislmcsjqkdpvh",
				"unkgmjgokmjnsgkjmen",
				"skuznvcheflqrpygjmyjfqghzmdplsnvcuerutboqrgvlfzjcmxnehy",
				"ifiib",
				"ppp",
				"jfwtyhdvugirqlfvhyjwtumrqgidlfjwayensghtikvqlurcx",
				"qbbqbqbqbq",
				"uyxpxpyutxytpuxsuypc",
				"gsslp",
				"pwugetkcbkpbwtegnucpekwutbcgvknwgbeputc",
				"eouscxlntepagmtcn",
				"xlmyghutcbkifbqgmlkvdhrxcalonbpzhsjwg",
				"mkhsnzxbjodyvgielqcpfrw",
				"yftilrxcavjgkuetkrwlzqnmophbdsj",
				"itmfbkclyzushnqexixbtdfqzlsychuveokmbfhqejyzclusimapxvktlfqschwueztbxkimytxsmcbqlrgzfiykehu",
				"yvubdecpxqrhizltskomfjvrmytoujzcghwlxdbqsefpoavjfzndulcbsqrhmytpex",
				"gkrymyjtpbkhrykidmr",
				"gumiaoexmacfxhie",
				"qbtgemyrwnaljraetqlnymbgltaomngsbyzerqretmybagnql",
				"tvoxaddxavjooadvxxoadv",
				"pcbxglukraklrabgcprbzkadlpgccgblxpkralcbrpagk",
				"zeaxivumdroypfuakymxzoirfpdepexaoiyfcudjzrm",
				"gjomtlsxyfazdcnrubqlydrncfamouqxtsbdqxybsfnglmrctoudlpoufkbqxnyermcst",
				"crbwqjdifgivrjqzqoihjr",
				"jmmjmjmjjm",
				"oshtbargiydzqospmtardbhqfyizysdhkitabproqzshjyodqbatmizr",
				"jxizfkrhizdpeiaqz",
				"zfebwrltvjnsxpdfvumj",
				"sqkskskksfsmk",
				"mtrqbqailqxqhnk",
				"guugpug",
				"klvxuwscgkvgslxwcuxcgwulvkswulgxcvks",
				"wmnhyutdyhxvkc",
				"oaqoqaadqoaqo",
				"nyiwslirizf",
				"btfdzqxpskhviyoagjyxruvpdilqoswk",
				"fwcsbydqlkipejhehbpidfwjkclzyslfwmdepbhjiakvsyjedyfwpgbihlsdtisfhlpuxjoenwbyr",
				"veifzdrlqxntckliywjhngobap",
				"wgnmspngmwpscmsgnwp",
				"zxvljcnetoakbfqwdzjfovcexgbaknlqwtqelvwxckfbtnaojzwtockbxaezvfjlnq",
				"gmceodryfdmfbywnvus",
				"avxxavavxmzxavxva",
				"ctmiqovawrydlxbekhbydemtwcoqrklhiavz",
				"twxxwqmdvfowhk",
				"fgqwkstldzmcxonzmdkxfgoscqwltn",
				"vylsuqgaripwxbohejzkrofkhzuqxbwsvpagytkvpswrhoaygzbcxtuqgswqzhxofprakvuby",
				"xxx",
				"kwcsmgzxfqdiorabkxdawsocqbrrhxvoastqpdcubkw",
				"bfeaqczjvtazkjqwoercfczastxvnmfjqeyljeqafzcxnst",
				"gpemfwkazpmgwzekaregzaonyc",
				"jhmaivsqpaxqsbevvaiqssqvhia",
				"abqnlgzroieoigbzqlnuaerljobnzayridqgce",
				"cndveqaglmmeaqndljvcglnvcdagqem",
				"nyklzsdigbgxhqidzuklnnzlykdigr",
				"jwqmrfcvayrylwfmavc",
				"rwftqvskhylxmbaepgxlzaywnqorvhfmitskjcybarkftwvdlqxmhsaqwvtuxfslrkmhyb",
				"nynp",
				"nefprhauytbcozrucpehbntoyfazhezyucarptonbfrahfuxtneyjpzobc",
				"zkwylmvsihxakrjmrktm",
				"zgfhmakjqhukgdxnshlvrpgbkkhwzytge",
				"lkrydykltxnorkeulrbqm",
				"tdtdtvxgdamzcdtptd",
				"xdhmnfgbkjaursotlgzaonesmkjrxdhclb",
				"wsixtvoqmnlbkf",
				"cxilrsjbzquovjqcsirybxovluzvxruqzsijlbocoxqvsiczrujblbhulrzcxivqosj",
				"wiylpnnlpwiiwnlpk",
				"pniluyobxfvzdtazmweqgkchrodjtisnu",
				"rplgxefjosmhdkuzncdbpszvhtrawjyqgi",
				"tweaqxrbfqyhrkwbuftxeaeyqaxhwftrfrwtzqxane",
				"yqcvukgcpuvgkqyovuqckgycygukvqkucqvgy",
				"nagfcwoyuplivxzsbexzswvyianfbepuolgxaovpibgzufnswley",
				"qpgreruqe",
				"pctpwaroqscncyzbiehplfg",
				"eykizclxhovdkzlcxhdvyeoi",
				"mmxm",
				"teyvjkxclfiazshqdrpzkjvflpqyretxdisayetspzadjxvkirlfq",
				"nqjykmcupkytihj",
				"qypkcxsoetmvnwarjiutkfjapegswrbqndzlmh",
				"gfatnypkolobasqczptgniktgmkewxupojanv",
				"knknkn",
				"mwjcfkgywfncjkgmytypcgmxwsfj",
				"iqsbwkyezrhfcrhwcqkbefszyikibyzsfrhqcew",
				"opxftzlyceqvnahgxncgzyqeathbopvlnyzgfvxdcapeqhtlojycxtvlqonezpgahdhaytonpelgcvxuzq",
				"vjcwyvwvwmpskzdwgievaxh",
				"lpmp",
				"mxraeksqfvozblyxsfbkiramh",
				"kdkqkikk",
				"clgqtvawnzoppnclqvogzyjswtaxzqcmnlwvaoigpt",
				"htvvhtthvtvhdwtvh",
				"fontbezgmcwliclgezmnwfitinzgceflmwtoiwtmncvrygze",
				"zhotuercknvpfwalnklerdafopcuvwzhphvwkfeazoucrnlfncorhvpkeauwzl",
				"egqjtbixgmtlpudwoakt",
				"nzpyhsfbijwelckumxvgcwbmzpxlevjksnfyuhi",
				"brivnojrinbvirnbvirvnb",
				"xziegsqjdyxsyiedqjzgdgxizjsqyeeyidzqjgsx",
				"crmdneqtojvormadvcjlokzjvrcwsm",
				"taqlnfvhylqnvfhtaps",
				"aghxmfuohgmrfouxguxohcmffxgumcho",
				"www",
				"lxwlwxwlxwglxoxwl",
				"gajyxnagjnxyuxgjayn",
				"fporwxgqdkihdovpaeythlnwkz",
				"hkmutuitmkhhtukmthkummkhtub",
				"aepugjlmbkrszfvmoflauznjbrp",
				"dwlhdwf",
				"mdpyheoaopmaydopadymypdmaoyomadp",
				"vtlh",
				"fccffc",
				"gcspkvqxznteavxztpqcbsgknaeopacmnsezkqltgxvextncpskiazqbgxcngdatejzrspq",
				"azjuwiqtgxysvkhiayswhobudktr",
				"xbeijkbjxekiiekbxvjqkixejbebxijk",
				"gigi",
				"ebgutwnkjxjbkzgtnaxyewu",
				"pasecmxbjrtvqkznwghjcrmpagzvqhetoksxwn",
				"glcverqzhbdijljzbgiqhecrbcgqzerijlh",
				"sbkjozaasseqawhagsqas",
				"swcbpyiipcswbyiwbpcsy",
				"xxxx",
				"lnjuul",
				"hfvimysrhfryisvm",
				"qhzdvuiacyxwkqbdwfizyvua",
				"txeouhancpqbgjwlkmfsmdbhoapjuclrwsngftqexecijlguqfbmwoxnasphtqapehxvtoclbuszmjynwgf",
				"mtuilgpbkjnavvktduhmynlabjvujxmtikanlb",
				"mcrebzdwvxskndlxjnxtad",
				"wlq",
				"bdajvilhsojisoqhld",
				"jurqvuhsspuh",
				"kuwgybfixdzstifnobygwlpeqxxbihfwvygjda",
				"hckgfqlbontgklfbhrqsozkjgoflqbhckbqmgfohlfwqkolbgh",
				"stantsaqndsantasntntas",
				"rfxqzjdvyzrjfxjbfrxzjrzxfrxjefzg",
				"ixqldtqrs",
				"dbhkjqezeqcdjbnkeqjlbpkdhqjdbeykdjoktmqsawbuexfvgr",
				"xfzwparuvwxrzknavoxrazwpsuvrwxmtaivz",
				"qhrzttdyuamxrnihc",
				"ojcjjjrrj",
				"ipgxrlsakotynbmvbgortknxyuplmsiv",
				"qowdhilapmklwaqkhpimdoikpwmqcdgohaldpilrwaqkmoyhmanlwoiqphdk",
				"bcb",
				"swqtmuhygdnxqgsyehdtumwrstgudwmqhfygytmswhdfqumwhtydgqus",
				"tvbim",
				"drxzwkcgxdzrialdzxrzdxrrxuzd",
				"fzlpvcmfvoplcbcflvpvyfipcbl",
				"opfkbmxsvznguaqmpufsqbnvgxaosmxgofbnaqurqoadwbhxmngusf",
				"xpelhcvbgfwzoslosftcbpewzmxhy",
				"kvjiajviakkavijaikjv",
				"ukppkukpupxkuupk",
				"nahgyxbfijdzukrtlewvcilrhdujgvcaywbfxktougdrxacbkwthofjylvixdtaiuhjcvfgkyrblwubhrwaivcfxdkjgptyl",
				"wbswswzpjsrswswx",
				"ecovmudkgdckvuomgecgeduvkmokexrumgcvoldogdvcmkeu",
				"otzhibuwylnpdjkfqesgmvcx",
				"uhibntjedrqlkzazutlekqijbhadnrlrudvhnxtqbejiwkzaknqdjlhzbrtuiaes",
				"lzucndskkudnslzdculwnzskunpzdlcykqutlnrhdkgb",
				"imvdycuymmyrebicjywxqosanbiry",
				"eeeymey",
				"pupuuppuup",
				"nxywbazjhfpmqrlptlnhfrjzbqioy",
				"jhqrpnacxktuywmzolbgidrcldaozfinhtywukjmgxpbqxknlraouiemtcjwypdvzgshqb",
				"hjtbfsawmyqreuxzpzkmrxelqbfgaijyucvws",
				"tmuodpivjkbesrnxwhgqlygkhvptmqodbicuwjsxlrupilsotvgqmdbjxkwrh",
				"uchfkdwgvoysazrekgnrmjidtphxzlbq",
				"peynjbjdetnbhaqknrlxemosb",
				"okcxgpmevacamkegoxvp",
				"ivetwsloarduhetsdjwviqoautsmfwviponeakxdu",
				"vxouknoxvunkuonxvk",
				"llll",
				"xpatespnavtsw",
				"pwuwz",
				"erqphaigsvmkcaigprevkqmynhscpdarkzqcsvbgmeihgpiemhafqrcksv",
				"gnfxpcvhyeqklbnlyegofxhcpkbpbfckgywxnlhoelkshmjptifecnydugxbzaychrlgnobxkpqfe",
				"fswnqiyamkrthzeudxlgvocjytdzglurakxihjcnfmvesowwtclfvjgmksuinzxehrydaogkhzvswmiayludfcexnorjtpzudegfksxvlnarctwmhyoipj",
				"hkvuctrxgeqbapdswpeqskrducgvhxwjoiqmhekpwvxdcg",
				"vxzygrsldmjoqpmbfvrjzktnsyqlrdymqlvjwzszomcjlqyrvsxg",
				"txt",
				"hidmjcszvwtyulexapvxpuhsmtiecygjarzdyipxsazecjhtvdmuktveujidzswpmhbycoxa",
				"bjhowspnxqrilgckzvyalycxpnjrbvghiwzkoqdasgnljyzbxswqvkcaoprihurpoiljxsvagbfkqyhzmcwnlnjxibqrcpvgszkyhaow",
				"rxdjupsboghfyqkghpcktodiysbafpygdfskohnrbswohdkpgbxmfyez",
				"qfoyjsuiwglpdsajgouipqfeyxwl",
				"ybvsh",
				"akgwpneftcidsmlxvyujpbpwroghzqr",
				"mmwmm",
				"aesucfwnbmzjixollwcsejaniomru",
				"skrijrjiskieszonkrjbv",
				"sqilweulqzisqicyl",
				"hcouimvmoiucvhouhvimciuochvmugihomxcv",
				"xcdqkvlwysm",
				"sd",
				"faqkwzdphtslbrmbsmryfzpkohlnaquqghrailbmpzfjsckxvskdempaqhyflzrb",
				"iftersaovkmqitrosfkmvaejbavftmiosrkekuvtrsoajfmei",
				"qiqqiwqqx",
				"cbmhaqsynzlkepebclhpqsnamzkkbeunmspclqhaz",
				"kkk",
				"lsjddjlssldjsljd",
				"mmmmm",
				"tnkdizrqyinjdbgtktcisnwa",
				"oimrgebkobjmgrik",
				"gzpfiuentbvyrcmzcysfenlprbutmvg",
				"iakzlspqyfdoxghevnwctuvuwhodnxyfqagtzpsceikltflnyxasiozdgcvuheqkwp",
				"apygardxeaua",
				"mahttpmhhmtthm",
				"ociwpsvnjykabufmrgezqldhfamcsnzgvlebjyhroqkpdiuwzvojpcqiufwkrgydnasemlhbt",
				"upkhltslea",
				"wxukirhvlfmgoexykvrhugdblomfwhlkizfomvgrwxussholafwvmukgrxtxwfsmurgvkohl",
				"jul",
				"wzpfqwmefwfe",
				"ewmxovgbcnijhykuklrsgdyzcaeft",
				"baflvedsuohztjxlqvzgwxsatefdcsaxbltdefrivz",
				"cdvmaqkngytfrdgkamagdpmkyskdmcjag",
				"ajnpffnpajfnjapfpnaj",
				"waslqkuvuvwsjakmqpvyuitqrbwcagoxkzeh",
				"pcaowtoptcapactopoatc",
				"ephggphegehpcespghgphe",
				"bcpoedcps",
				"famtdwsbrznjjdznfrtwmbyadfrmjawebgtphnqzjzmnrtafudwbrbaznwtdjmf",
				"qmyhwgtcepkdgkdqtmpyfwpurgdkwoqmtl",
				"zhvstamfpdcdtszpcfvamhdzvhftcpasm",
				"rgwyksyhkgfwreyrsgxocadirygtn",
				"jzdatumwehclkxirsyvfcbkng",
				"dtmkaiubljqmkivbojlimkjbleklmijb",
				"yjtptjy",
				"jvipbosutwjosgipwkutzbjsupowbrtibpikjtsouwfojtpwbsaui",
				"eehgfee",
				"fbdpoauijhroufmvbcfbtoul",
				"rwxplhwhpxlrwxlprhlxwrhp",
				"pncagrrgnclpa",
				"vhjyokxtbpuskuwogrqa",
				"yratqdoxwcpksorywjbenudlxhvapi",
				"evsktdfwogcuhzidwgnrcelxyvjmkp",
				"jcezwrigomdthzcdjtiwretczweijdrh",
				"ukcewyhfsapozlxwciopgukxheylazflwekafhuybozxpcwyhupafeclknzxoezcxlkphouwfay",
				"klfjutwxnhvicympbdrznpkzcituovfldxgbhwjmstxhwjkifmvuzbdcpln",
				"ifrupppgswo",
				"xkimfmxikf",
				"tdneqdiwfzlbsahjokvmpry",
				"wezwezwezrzweezw",
				"stfjbctwfjbcsbstjfctbsfjcsfbjtc",
				"asjbkpugrnteyfcomdlhyoadpfjmubrkltgcneshzlkrfnpmteyjcsubgzoadhxghijfescdwtoykpabumqvnrl",
				"ugdu",
				"qrvyinvvvhzzvm",
				"uoblqtenkysjdcwmraivfgpzxhpckigqsolvfnmjauyzhxtwdebr",
				"wdkrlgqmvuhicnxebatjrcdvkftqnuiewhcntediyvhwukqrvrhqpsiounecwtdkounreidwqchkvt",
				"arelvfzbhkdinoxtgjpcsuszocvdbfjhranixtkelpugeinpchxzdrktlfubgovjsacvbnriuosehxjgdlkpztafuzdfcxejbhtvolknrspiga",
				"dsxcfuzphkroifcpcyifvop",
				"jmillimjljim",
				"smrjzlwuikqholtfauyimumncpieftbl",
				"kqwkqkcktp",
				"zoncjltqxyhasigkfwurbmdvuhbzojkagtxcvdrwlsfynqmixhlyswojgrzcvktbfqidaumnqtgswjoaivybnhcfrxklmduznhvwitqxalkjrdmsguofcyzb",
				"sunhuusu",
				"stxofjnyvhizmelagbdwpucrbfnweycogqztipsaljxkd",
				"rmyclkwgqfhejaqgjucrzyemlwakhkphqegadcwmuryjtaxrkcevbqghjymw",
				"lugcahsyrjnoxpzemespgjrnyzcuhmlaoxjmgrcnsazoehlxupnfepgjluzhcadxmrsosrlnjcpzmeoghaxu",
				"bcqrkadhzdcbhkzahzndimkacdqkczhba",
				"qglerszvszlehqzfjueilqsdeszlqzsqler",
				"twcekgfq",
				"rcmyhawqtgbjiflpxeznaelwqgjmtzycrfpnhxibxnrfbgjtqzyaplmchwie",
				"yhacsmawnvjkeyqcighstuahycs",
				"iwtdgkpi",
				"nizjlemapcwxtsuoqkjbhygdv",
				"pyusefbwjrvgzbjfzpwsuyegrjrsxohcegwfpzuyb",
				"ekxdmsjzuntaizxdaujmtnikesjndizketuasxmnjqakpsuzitefxrgdm",
				"ehvknuhzukmnnbtdksxrgaknnaehok",
				"wipbuyzsysbqdxyqbjstgsyxdb",
				"smhkvxwtgjhtkgmvqsxcjtujghmsxikvhxvsmytgkjd",
				"ynmunykn",
				"qebguqgrblhejuhrqmnfokqxy",
				"mcvytsaupuskqhw",
				"vwmmvjwqcmswvvwjmzwavm",
				"enfqxenxfqfexqn",
				"xsmzlbqpoejwhzigxzcrfznzrv",
				"oueayjqjyu",
				"xrzqtsrzyegnbuzcjqwzxisr",
				"dnwqumcgkntyfqhmtnmfq",
				"syxh",
				"esknrbrpym",
				"syhyiayknbpmyzo",
				"ebhmyzmebyhzezhybm",
				"omzvarexmzoarexmrozaexzaomrxe",
				"fecarzihbklsodvpvdbhpaizlefrscrfeiapvszdhlbqcsfpbaiqvchlrdze",
				"zvjxlgfokbhupnaluigxdtwqves",
				"csekooseecsowsegjoa",
				"bmdrunwniaija",
				"lnapozbanpbzolhyzrbajnluoplopznba",
				"iuhorcktdsitafkxlkvefitdfikxzltglktniv",
				"ibgjqwxbiwqgjx",
				"ofpcnjzmwxtvglbysuqrkadhqfghmrdljbksxzovuawnctyptqxkvnmrjgpahylcsbdzwfuouqxmlkfdnrjovatsgzwpbhcyjfsagdqxrvpcnohubkzmtlyw",
				"nsofzrtgcfjtcsgoniftigacnohoupnqfcgtnfctgvxlyom",
				"gtlrszhtlghsrz",
				"ciygwfesbtvhvcyb",
				"otupmldwkhbvyxrnibdwthuylsvpxkmnornxktbmlyvpdhwsorumkbantvwxyguophdrl",
				"vlxxlvhlxv",
				"falrxmabrml",
				"czfeltxz",
				"zhhzzh",
				"vlpungovnplougnvupgol",
				"aihvwxomyseqjrupvxtbglcnhoewqszud",
				"evdfhlanzowmjwjfakoizvlyumejeadzfswclmvqo",
				"vofnaxpuqdjzktkxouzdqypvafsfaimwuoerx",
				"yiqjnrmwgcnkzxdebopls",
				"mxuyznpkdslobfqethjvgcwidhygwolniuzkmfqtjbexpcsvjtnbavpgulcsfwzmeydkixhq",
				"pwqcdsagneuxapwdslczguex",
				"ochfgitkpjmxvbwsyalzpqfoehjmklytngxzsa",
				"zwcdvjyuxmjvxuczdmjcuxdmzv",
				"exxeex",
				"bruqxpntrtnxqu",
				"cqmpedhtwahjnweafbtmydckvgicoxdwrplmhetaowmdqctaeh",
				"eonvhayprlubmkdxcwqgtmbuqcnylwxekorvtphdaltqohvydpemxknabwucr",
				"bviypkgrtaucmjeojpsbalymxkfcvdzoie",
				"vxlqyrfpvqplyxfryqrplxvflvyrqxpfrwqplfyvx",
				"xxxl",
				"yuvooyvu",
				"dqevksywtmajxhuorncgziflbsaberqxvnhjiwkgdyzfltckvyjwgqcathexndlzsbfri",
				"rmplmatsrkl",
				"dqwdwqwpdqwjsdqqrkwd",
				"vmoltnkuwnatmlzqgonvoutlmontxmvltolxmn",
				"rjqvugxpbwdjgdbwsprqvujdqupyvgwrbe",
				"mkibxclpudcumrklhlztkmasvcwguo",
				"juuuu",
				"hvoizamdrupuqftvdjrrgwsctbvdukfvdlkrpuxterjxvwybudq",
				"thaqbftqfkyvocwlnxzijmpu",
				"isdxlmekbpyvrazoqngjhfwnczselimvurpbxoywgafhqymbhasxeliofwqgnrpzvxmpnzhyiablsqerguvowfvumoseywazfinhpqblxgr",
				"wjuvwicvw",
				"fjxfjtwayjeqojhxjzr",
				"wcqfj",
				"pnysjzkwmeaxgtirdfitgzyernwxkapdsfmrbkawofqxsinmzytgledsfnxytiwzmgakerd",
				"ygnmzdhkxpezktnlepuh",
				"jsbfpuwvkiehgrejkrifnwvbgshpluvcjbhsigfukwprepbjfhesukgwvriwvkrsbeugjhipfy",
				"oxzwnftkoxwtwouxt",
				"nycmubiopggbutcomnypuboypnkcgmpoxndgyubmc",
				"wpodjnyhtqukexcihjlvwdfguzpnxaettojydphkwcxnuem",
				"dfyopwrhjcmxbikumbawgjorfhpildyucxuihbwdocmvnspyqfx",
				"brgjymfawvrjywbgpfywzbjgfibeckofyj",
				"sktrbgulyndkbskuvzabsejpbhxsomckksbqfi",
				"lrkbaizhtpguwjqvgnouwhlabzirkpjqttukpjrbzaigqlwehulasbqtpwhkzgijrzktiwbjuqsahlgpr",
				"ipasgukbhcfwltgzswubeqcalpifwpslbiguxaemfcnapwlgqfisxcbu",
				"tgcirbmwxagxyqrmwztcqgxmczwtrfnoxrwgjklmtec",
				"iqthapgwsyzumejnddxfvsceugokqlwmbyzjpr",
				"ixmsmpsi",
				"gjoxrcmtxrjgtomc",
				"rxikogsafteqbupmdgtqnkwescbrpmojafziregptqlkaisybmfo",
				"gcsnyeojwlljeoyhcng",
				"rboeafpxktihsqncfhjokdgqinwzeoihfmkynqxe",
				"rjuyhaqmliwckgximcfzgwyrlhnhlrgtcsimwxy",
				"wpfqculrmxoscojqsqcszoozcsq",
				"ilbezokgtpwmurkdfphtzcyw",
				"xdabfqugteadhhh",
				"ejvpamsgddgemiloaudmeasgjademg",
				"jfagcbmxylbycfgjlmax",
				"gobmlcirroicglbpbicglrociobrlg",
				"jiqowhrmbiqrqirmqrbil",
				"eamlhtgvzsjoxyuinrpwqbdbtonqpwgjamhrlsixyvzdue",
				"rhnamzcvkqbdpftgwitmbpkihdwzagvrfnqwkpdtzqmfgisbvnarhmwkbihgpfrnadtvqz",
				"pdstumbzqalramzqwdrutpblsrqubzdpatmslstzprabdmulq",
				"lfff",
				"jdegpfinlzxplfnegdzjgnalepfdzjxjeldpzgnfzdspgnfwyelj",
				"ublyneqswi",
				"efrjdgxwdrbtjxkjdvbpjuadqodbj",
				"yrwqyqrrqy",
				"vsxcwouzegqakynfcllrbcrcjh",
				"ikxnftdovcphzaeadpitzckovxhnefcilfohenpdzxtvkaehitodpkvfzxcna",
				"tefamtujintfreudwsxopkqgbl",
				"pmjsxaekqlrdobwufnztvgwuqrkvbgopatsemlnzxdsvonbdeqagtzwlpcukmrxksuzlaernbcwovxgqdpmtwxetnlqazbpgskvomdur",
				"skpvxloqduizwatrgfnycxaeyvgcfwpikoutndgyanbjxwmitocpkufdv",
				"ntuwlfqjyvraktxivfyoldejunacg",
				"nqq",
				"sidtzklzsondqitktskzid",
				"hopdvhpdoohrcdp",
				"ncdjcjdaydkjrv",
				"brtahsneojzqzejbnswvqoahyxrrmhosqeabjnzaebsjoqtmzrnh",
				"ayqmj",
				"zmcfrgsxenlkjavupsyjwrhq",
				"grbxsdkpsygnarxrjbgsexejvgwlsrx",
				"dqrzwiuxiurdwzuidwzrpzwidrumuwzrid",
				"exmywtpwempttpwemtpwme",
				"arlhfxdcmvvsmrhclkqfivrcphfmadl",
				"kylhzzlyzly",
				"taltalaaldaevb");
		// Part one
		int count = 0;
		for (String string : input) {
			String[] split = string.split("");
			split = Utils.tail(split);
			List<String> answers = removeDuplicate(Arrays.asList(split));
			count += answers.size();
		}
		System.out.println(count);
		
		// Part two
		List<Group> input2 = Arrays.asList(
				new Group("edmzkxfoprcnhijtyvl","adxntojykfcvzermplh"),
				new Group("jbhpksufcaty","hevsuaibjkt","jbusytghak"),
				new Group("ixpckvbrylgtdm","hpyojlsgibtvc"),
				new Group("sga","sag","gsra","awzgs","sga"),
				new Group("jnwcqfisokbgmt","jmtcubwnsk","bmwkctjsrn"),
				new Group("ekxwotiyfhagdlmqn","hpvedxwscgqjlkrf"),
				new Group("drtguxboe","uxotwejgibfdrn","rkgxbtaeoupd","kohedbgzurtx"),
				new Group("di","whdg","d","d"),
				new Group("pukeyxjrvmowta","ejyxrwopkhtu","upojtrxyekw","cjxubkyetrowp","tgxwyorqnejiufzkp"),
				new Group("nqbraty","ybrqna","qyanbr","ayrqbn","aynqbr"),
				new Group("ezljbkmhionfqv","hxvtnjqr"),
				new Group("fuwsngzivcjrk","kprjnfucziv"),
				new Group("wonvukgls","wkoslgvun","kusvtolgnw"),
				new Group("tieldgxmys","dilexmyrvsqj","dlxyiems","sylxeimd"),
				new Group("gfapnyrzlwhscjmixb","yramfspwnicghblxzj","rnwmehkbjzpalgyfiscq","jfyclgmabhrizvwpsn","gzsahifrytmjlnwpcb"),
				new Group("wfyrobghlqcjn","yzwhfjlocgqmbn","yqgojhlnwczfmb","whlozqfcmnjgby"),
				new Group("envihwzxs","ivsw","iwsv"),
				new Group("gjocrpmlhnkbxevdsztq","rvoecmjbgndlswphzktqx"),
				new Group("ph","hp","hp"),
				new Group("vmzyftwk","vtkfemzwy","tymfwkzv","ktfvwzmy","kwzvytmf"),
				new Group("yntcgdfblkz","dykfcmnltbz","tmzdnylbfhck"),
				new Group("jyuwnazhbtrdvlfcoxmi","mlxowqarbhnitjfvcduy","hvbjknialucoptxysmfgdwr","fihbrodmtjcxvnwalyu"),
				new Group("xdicwhvujszagmey","czjrmdyauevw","muweycajzpvd","vayjcwedumz","uwyvcedazmj"),
				new Group("zqniybfcr","rizunqtpcyf","cqyizrnf","firzchmlnqy"),
				new Group("ckezaduhtxoilyn","kliuytzonedax","ulkxznteiydao","uanxdpetzlyiwok"),
				new Group("opgmiufxdkw","onfuxdwmgki","fiwxmokdug","pfdiumwyxgok","fodxuywmigck"),
				new Group("fg","zgfb","ufg"),
				new Group("z","ze","az"),
				new Group("scwqjukmhplzxafiyvdtr","mpwyerhvqzbfcdikxualst","gkzrwpcfnqvxtiyuodlsam"),
				new Group("enzt","yzprno","mcanslzq","zonr"),
				new Group("xlsqjnuobfymtd","obtueyxdjkciafqnlmz"),
				new Group("fcowy","ycfow"),
				new Group("timwqdnebkcsajpolr","hycqdueti","ctgyvidequf","xiuecdtq","viqetcdz"),
				new Group("atlqfdinogrbm","drgqxloektiambu"),
				new Group("jd","jd","dj"),
				new Group("cknxalfwburopditehsyz","wtigkfzlchsrnybuoxaepd","vaponqfukzcsiybrljwedth"),
				new Group("rxhuz","drzhkxumtginj","rcaxzohevyu","pszhreux","ruxhzpy"),
				new Group("ceanhqvbtkgiplr","mlpithvrkcaqng"),
				new Group("lageimuyjxntbwphfs","gpnihamyelxbwsu","yxmiswngulepabh","wxsbnhpylmgaieu","ayximuwebhpnlgs"),
				new Group("begmvrkqptz","hwsfjlxdciyaun"),
				new Group("prmkvejosyubtnz","rkeoynmjavzspubt","huomzbtnwyrepsjdvk","ebskrvtzjmyuopn"),
				new Group("ugmwobeiyqtckszvpaxn","sivuazqotwxykcpmbgnhe","ugovsircnmqztplwayxbke","sxibehutwazpgqynkmvco"),
				new Group("gmfipesaykorxbwjl","ojlfpxwgrnikmeyhqsba"),
				new Group("c","c","c","m"),
				new Group("dapbveo","armnqopxhvie","aptebovd","vpoeza","aotwfepsv"),
				new Group("i","ic","i"),
				new Group("pftbquhlydrs","postnjxlihagdzbywce"),
				new Group("xcivfymjdrzhesqb","fzrcmjhbsviqyxe","vimlnscfwxbyrhjqupeo"),
				new Group("f","f","f"),
				new Group("usnh","rmupglay","uqv","uqw"),
				new Group("ldb","ld"),
				new Group("sbrqvouly","sroylqf","qsryitoe"),
				new Group("wntmgqjauybzoldvfck","gldqtkbaeznufwymcj","lrchunbjgdykzawtqfm","mcabflwtyqujngkdz"),
				new Group("rofcihkmqbwgtexjavnz","qfagcjxkhmiotbvwnrez","ntkqjiyzvboafewhxrcmg"),
				new Group("bv","tv"),
				new Group("wtvepsd","dyzhir","jbqclkxnmguaof"),
				new Group("gzbtsreonmhxlkijpqu","kxhmltszqpnorujbige"),
				new Group("hpeakzrxymigovt","vrtxgmkoyapz","pgzrmvyoakxt"),
				new Group("lbygrmxoivfucw","rcjivowfgblmxs","rxoiamvclujbgwsf","xvrfpibeclnmwot","lofcxrivmwb"),
				new Group("jhxbfydcqw","msoagpirvktelz"),
				new Group("wczxsbnqe","zirqonwpbxe","nqwxsezb"),
				new Group("ydwo","ydp","yd","axdsvhjmfy","dy"),
				new Group("rxtujw","doahz","rtsym"),
				new Group("pbic","bc","bc","bc"),
				new Group("jxsbfr","bcsrfjx","srixvdnbwzj","rxmakbsj","sxjmrabf"),
				new Group("wruifa","rfa","arf","asfr","fra"),
				new Group("gyi","giya","ygain","kigy"),
				new Group("tqoxh","lhetqrm","yxvtkqfdh"),
				new Group("ytkqvup","mkpuqv"),
				new Group("jreztqmwvgisnh","byrhwtzedsq"),
				new Group("qjo","ojq"),
				new Group("xbhzsotugeijrk","gkziyorjuxbepds"),
				new Group("kusymzbclghf","quchlgfkzmyb","jurvyclihkm"),
				new Group("whvkxzmrl","krszxwvmhl","zrmhlvwskx","mkxrwylovhz"),
				new Group("sakfigdb","afskgb","kfagbs"),
				new Group("vnyo","uxwoyn","sbpzn","imgtna"),
				new Group("dqjtmskpzify","ktjmeorfaipd","pmatejdofki","fjlpmidkrt"),
				new Group("hauldscwin","tdarhinu","nhdfuavir"),
				new Group("hinbmavoc","virmshcazb","havkrcomib","viabhmqc"),
				new Group("tawexm","xmatew"),
				new Group("opg","gpo","gpo","opg","pog"),
				new Group("vkbznjquy","qznuvkyb","kvuqznaby","qkvuyzbn","nqzyvkbu"),
				new Group("ocansuzdmvwei","hasyfpwqj"),
				new Group("vmj","sknpejom","vjchumg"),
				new Group("mhws","hmsw","shwm"),
				new Group("tcpbdzvarixyj","dxupoyqfwnkvesbh"),
				new Group("dm","fomdg","dm"),
				new Group("yz","zj","jz","vlztahq","fizg"),
				new Group("itvnmlxphycf","fzmcpvxhnityl","clpfnhixvtym"),
				new Group("remig","egu","stzcnbye","oie","lepag"),
				new Group("tzsnfhweuqvoybjim","vxzmptudbrowfyneghcq","ywmlhaotnzfukvbqe","qltpcbwvmeuazrfonyh"),
				new Group("hcytfwgve","dycvepxlhzfngws","vwtcgyfhme","wfgeyvhc","cyghwfev"),
				new Group("lzhbuc","qeczhl","kpfzvhjyscxlita","lzdqmgchn"),
				new Group("qyzgcum","alwesq","bqy"),
				new Group("guxcprsfqezajltmwd","rqltsuzcgamxjfwepd","jfmuzeswdqxalgrptc","jtelwdfcrpagxsumzq","iaqjxeyclgprwmzfsduth"),
				new Group("zcghqfuprlavsjbktxoidmenwy","cxbmwnlogdiqrhujpfsyzketav","cnaugxstkhizjodpwrqlefbvym"),
				new Group("sgvfzhp","fwnghspu","ipsfgah","puhfgns"),
				new Group("prtxkifmoyqwbdsh","iryxfhobqstkdm","fmtkdsyqrioxhb"),
				new Group("irfcynskv","cenorvkisjyf","srfkvynic"),
				new Group("njdshblezrfx","fesodhrxn","nqhiautvrscdwfe","nhdreslxf"),
				new Group("rceub","uabflro","szvxtkyqngd"),
				new Group("ewobrfqcspym","mpqcwfsoyber"),
				new Group("klrxyaf","alrykf","ykaflr","fakyrl"),
				new Group("ezqwmua","wamqeuz","eqmzawu","mqweazu","zqweamu"),
				new Group("jkfqgzhlpwntmduoyscxbea","znflctasoqekmbwhxdujgpy","leqakghpynzjcboudwxfsmit","czuyjtdpfxlhakbeognmwqs","skbqeydcjlfoazmputhnxwg"),
				new Group("haqvxtepiczsgymlkbw","yusgxiaehlbzwmqct","tqnxiylhmzcsgweab","yiatzblcgxhmeswjq"),
				new Group("ogzmupysnrt","lugmkypqizocnvr","syfurgmpnhzow"),
				new Group("pgrb","opycugr","tjrngadp"),
				new Group("swbkulnao","pmkdrbqyzonicuj"),
				new Group("pfzl","flpz","vjzfpbel","sfpzl"),
				new Group("yrboxuhknlwzc","dbiurzxogajcpwyl","xblcywuohrzm","rxfowylzubc","clxqeurwzybok"),
				new Group("earvompiks","zrmsoieapk","gekposamir"),
				new Group("mwvlrtae","mlav","lamiov"),
				new Group("oghqcsvlw","qowhgvcysld","hqewcgvosl","glqhkpcsrvnftwox"),
				new Group("mpajys","mywpjs","jyspmv","lpsymj","sjpmy"),
				new Group("rebc","oxbwcr"),
				new Group("uctgdqwxe","wctpdgjqxeu","qryotwezfmgdixcu","eqxtwdaucg"),
				new Group("motajvxdi","naxtduvoizj","lpoxvgdsfyha","wedvrocakx"),
				new Group("qorxj","ekqzpxj","jqx"),
				new Group("nxl","cnlx"),
				new Group("fo","iot","vuxgo","uo","xio"),
				new Group("gvjefxzi","adsjpbchuyw"),
				new Group("gvbhodi","ogbhivd","hdvugbio","goihdbv","igbvydho"),
				new Group("krdufhbgymvlxiqwepco","ldxuyefjoqzmr"),
				new Group("sy","c","nj","n","j"),
				new Group("qwiyz","qwz","gqkrwfzb","qzawj"),
				new Group("bsax","xwabskm","bxjas"),
				new Group("fqpazsenjukgoyi","ugznyxfqkaopesi","qysokeapnuifzg","epfaqiyugnsozk"),
				new Group("vrxpusdht","phuxsvbn","ahfyvpwislmc","sjqkdpvh"),
				new Group("unkgmj","gokmjns","gkjmen"),
				new Group("skuznvcheflqrpygjm","yjfqghzmdplsnvcuer","utboqrgvlfzjcmxnehy"),
				new Group("i","fi","ib"),
				new Group("p","p","p"),
				new Group("jfwtyhdvugirql","fvhyjwtumrqgidl","fjwayensghtikvqlurcx"),
				new Group("qb","bq","bq","bq","bq"),
				new Group("uyxp","xpyut","xytpu","xsuypc"),
				new Group("g","s","s","lp"),
				new Group("pwugetkcb","kpbwtegnuc","pekwutbcgv","knwgbeputc"),
				new Group("eouscxlnt","epagmtcn"),
				new Group("xlmyghutcbkif","bqgmlkvdhrxc","alonbpzhsjwg"),
				new Group("mkhsnzxbjo","dyvgielqcpfrw"),
				new Group("yftilrxcavjgkue","tkrwlzqnmophbdsj"),
				new Group("itmfbkclyzushnqex","ixbtdfqzlsychuveokm","bfhqejyzclusimapxvkt","lfqschwueztbxkimy","txsmcbqlrgzfiykehu"),
				new Group("yvubdecpxqrhizltskomfj","vrmytoujzcghwlxdbqsefp","oavjfzndulcbsqrhmytpex"),
				new Group("gkrym","yjtpbkhr","ykidmr"),
				new Group("gumiaoex","macfxhie"),
				new Group("qbtgemyrwnalj","raetqlnymbg","ltaomngsbyzerq","retmybagnql"),
				new Group("tvoxad","dxavjo","oadvx","xoadv"),
				new Group("pcbxglukra","klrabgcp","rbzkadlpgc","cgblxpkra","lcbrpagk"),
				new Group("zeaxivumdroypf","uakymxzoirfpde","pexaoiyfcudjzrm"),
				new Group("gjomtlsxyfazdcnrubq","lydrncfamouqxtsb","dqxybsfnglmrctou","dlpoufkbqxnyermcst"),
				new Group("crbwqjdifg","ivrjqz","qoihjr"),
				new Group("jm","mj","mj","mj","jm"),
				new Group("oshtbargiydzq","ospmtardbhqfyiz","ysdhkitabproqz","shjyodqbatmizr"),
				new Group("jxizf","krhizdp","eiaqz"),
				new Group("zfebwrltvjns","xpdfvumj"),
				new Group("sqk","sk","sk","ksf","smk"),
				new Group("mtrqb","qai","lq","xqhnk"),
				new Group("gu","ugp","ug"),
				new Group("klvxuwscg","kvgslxwcu","xcgwulvks","wulgxcvks"),
				new Group("wmnhyu","tdyhxvkc"),
				new Group("oaq","oqa","adqo","aqo"),
				new Group("nyi","wsl","i","ri","zf"),
				new Group("btfdzqxpskhviyo","agjyxruvpdilqoswk"),
				new Group("fwcsbydqlkipejh","ehbpidfwjkclzys","lfwmdepbhjiakvsy","jedyfwpgbihls","dtisfhlpuxjoenwbyr"),
				new Group("veifzdrlqxn","tckliywjhngobap"),
				new Group("wgnmsp","ngmwps","cmsgnwp"),
				new Group("zxvljcnetoakbfqw","dzjfovcexgbaknlqwt","qelvwxckfbtnaojz","wtockbxaezvfjlnq"),
				new Group("gmceodryf","dmfbywnvus"),
				new Group("avx","xav","avx","mzxav","xva"),
				new Group("ctmiqovawrydlxbekh","bydemtwcoqrklhiavz"),
				new Group("twx","xwq","mdvfowhk"),
				new Group("fgqwkstldzmcxon","zmdkxfgoscqwltn"),
				new Group("vylsuqgaripwxbohejzk","rofkhzuqxbwsvpagyt","kvpswrhoaygzbcxtuq","gswqzhxofprakvuby"),
				new Group("x","x","x"),
				new Group("kwcsmgzxfqdiorab","kxdawsocqbr","rhxvoastqpdcubkw"),
				new Group("bfeaqczjvt","azkjqwoercf","czastxvnmfjqeyl","jeqafzcxnst"),
				new Group("gpemfwkaz","pmgwzeka","regzaonyc"),
				new Group("jhmaivsq","paxqsbev","vaiqs","sqvhia"),
				new Group("abqnlgzroie","oigbzqlnuaer","ljobnzayridqgce"),
				new Group("cndveqaglm","meaqndljvcg","lnvcdagqem"),
				new Group("nyklzsdig","bgxhqidzukln","nzlykdigr"),
				new Group("jwqmrfcvay","rylwfmavc"),
				new Group("rwftqvskhylxmbae","pgxlzaywnqorvhfmitskjc","ybarkftwvdlqxmhs","aqwvtuxfslrkmhyb"),
				new Group("n","y","np"),
				new Group("nefprhauytbcoz","rucpehbntoyfaz","hezyucarptonbf","rahfuxtneyjpzobc"),
				new Group("zkwylmvsi","hxakrjm","rktm"),
				new Group("zgfhmak","jqhukg","dxnshlvrpgbk","khwzytge"),
				new Group("lkry","dykltxnor","keulrbqm"),
				new Group("td","td","tvxgdamz","cdtp","td"),
				new Group("xdhmnfgbkjaursotl","gzaonesmkjrxdhclb"),
				new Group("wsixtvoqm","nlbkf"),
				new Group("cxilrsjbzquov","jqcsirybxovluz","vxruqzsijlboc","oxqvsiczrujbl","bhulrzcxivqosj"),
				new Group("wiylpn","nlpwi","iwnlpk"),
				new Group("pniluyobxfvzdta","zmweqgkchrodjtisnu"),
				new Group("rplgxefjosmhdkuzn","cdbpszvhtrawjyqgi"),
				new Group("tweaqxrbf","qyhrkwbuftxea","eyqaxhwftr","frwtzqxane"),
				new Group("yqcvukg","cpuvgkqyo","vuqckgy","cygukvq","kucqvgy"),
				new Group("nagfcwoyuplivxzsbe","xzswvyianfbepuolg","xaovpibgzufnswley"),
				new Group("qpgre","ruqe"),
				new Group("pc","tpwaroqsc","ncyzbiehplfg"),
				new Group("eykizclxhovd","kzlcxhdvyeoi"),
				new Group("m","m","xm"),
				new Group("teyvjkxclfiazshqdrp","zkjvflpqyretxdisa","yetspzadjxvkirlfq"),
				new Group("nqjykmcu","pkytihj"),
				new Group("qypkcxsoetmvnwarjiu","tkfjapegswrbqndzlmh"),
				new Group("gfatnypkol","obasqczptgnik","tgmkewxupojanv"),
				new Group("kn","kn","kn"),
				new Group("mwjcfkgy","wfncjkgmyt","ypcgmxwsfj"),
				new Group("iqsbwkyezrhfc","rhwcqkbefszyi","kibyzsfrhqcew"),
				new Group("opxftzlyceqvnahg","xncgzyqeathbopvl","nyzgfvxdcapeqhtlo","jycxtvlqonezpgah","dhaytonpelgcvxuzq"),
				new Group("vjcwy","vw","vwmps","kzdwgievaxh"),
				new Group("lp","m","p"),
				new Group("mxraeksqfvozb","lyxsfbkiramh"),
				new Group("k","dk","qki","k","k"),
				new Group("clgqtvawnzop","pnclqvogzyjswta","xzqcmnlwvaoigpt"),
				new Group("htv","vht","thv","tvhdw","tvh"),
				new Group("fontbezgmcwli","clgezmnwfit","inzgceflmwto","iwtmncvrygze"),
				new Group("zhotuercknvpfwal","nklerdafopcuvwzh","phvwkfeazoucrnl","fncorhvpkeauwzl"),
				new Group("egqjtbi","xgmt","lpudwoakt"),
				new Group("nzpyhsfbijwelckumxv","gcwbmzpxlevjksnfyuhi"),
				new Group("brivn","ojrinbv","irnbv","irvnb"),
				new Group("xziegsqjdy","xsyiedqjzg","dgxizjsqye","eyidzqjgsx"),
				new Group("crmdneqtojv","ormadvcj","lokzjvrcwsm"),
				new Group("taqlnfvh","ylqnvfhtaps"),
				new Group("aghxmfuo","hgmrfoux","guxohcmf","fxgumcho"),
				new Group("w","w","w"),
				new Group("lxw","lwx","wlx","wglxo","xwl"),
				new Group("gajyxn","agjnxyu","xgjayn"),
				new Group("fporwxgqdkih","dovpaeythlnwkz"),
				new Group("hkmut","uitmkh","htukm","thkum","mkhtub"),
				new Group("aepugjlmbkrszfv","moflauznjbrp"),
				new Group("dwl","hdwf"),
				new Group("mdpyheoa","opmayd","opadym","ypdmao","yomadp"),
				new Group("vt","lh"),
				new Group("fc","cf","fc"),
				new Group("gcspkvqxzntea","vxztpqcbsgknaeo","pacmnsezkqltgx","vextncpskiazqbg","xcngdatejzrspq"),
				new Group("azjuwiqtgxysvkh","iayswhobudktr"),
				new Group("xbeijk","bjxeki","iekbxvjq","kixejb","ebxijk"),
				new Group("gi","gi"),
				new Group("ebgutwnkjx","jbkzgtnaxyewu"),
				new Group("pasecmxbjrtvqkznwgh","jcrmpagzvqhetoksxwn"),
				new Group("glcverqzhbdij","ljzbgiqhecr","bcgqzerijlh"),
				new Group("sbkjoza","as","seqaw","hags","qas"),
				new Group("swcbpyi","ipcswby","iwbpcsy"),
				new Group("x","x","x","x"),
				new Group("lnju","ul"),
				new Group("hfvimysr","hfryisvm"),
				new Group("qhzdvuiacyxw","kqbdwfizyvua"),
				new Group("txeouhancpqbgjwlkmfs","mdbhoapjuclrwsngftqex","ecijlguqfbmwoxnaspht","qapehxvtoclbuszmjynwgf"),
				new Group("mtuilgpbkjnav","vktduhmynlabj","vujxmtikanlb"),
				new Group("mcrebzdwvxs","kndlxj","nxtad"),
				new Group("w","lq"),
				new Group("bdajvilhso","jisoqhld"),
				new Group("jurqv","uhs","spuh"),
				new Group("kuwgybfixdzs","tifnobygwlpeqx","xbihfwvygjda"),
				new Group("hckgfqlbo","ntgklfbhrqso","zkjgoflqbh","ckbqmgfohl","fwqkolbgh"),
				new Group("stan","tsaqnd","sant","asnt","ntas"),
				new Group("rfxqzjdvy","zrjfx","jbfrxz","jrzxf","rxjefzg"),
				new Group("ixql","dtqrs"),
				new Group("dbhkjqez","eqcdjbnk","eqjlbpkd","hqjdbeyk","djoktmqsawbuexfvgr"),
				new Group("xfzwparuv","wxrzknavo","xrazwpsuv","rwxmtaivz"),
				new Group("qhrzt","tdyuamxrnihc"),
				new Group("ojc","j","j","jr","rj"),
				new Group("ipgxrlsakotynbmv","bgortknxyuplmsiv"),
				new Group("qowdhilapmk","lwaqkhpimdo","ikpwmqcdgohal","dpilrwaqkmoyh","manlwoiqphdk"),
				new Group("b","cb"),
				new Group("swqtmuhygd","nxqgsyehdtumwr","stgudwmqhfy","gytmswhdfqu","mwhtydgqus"),
				new Group("t","vb","im"),
				new Group("drxzwkcg","xdzr","ialdzxr","zdxr","rxuzd"),
				new Group("fzlpvcm","fvoplc","bcflvp","vyfipcbl"),
				new Group("opfkbmxsvznguaq","mpufsqbnvgxao","smxgofbnaqu","rqoadwbhxmngusf"),
				new Group("xpelhcvbgfwzos","losftcbpewzmxhy"),
				new Group("kvjia","jviak","kavij","aikjv"),
				new Group("ukp","pku","kpu","pxku","upk"),
				new Group("nahgyxbfijdzukrtlewvc","ilrhdujgvcaywbfxkto","ugdrxacbkwthofjylvi","xdtaiuhjcvfgkyrblw","ubhrwaivcfxdkjgptyl"),
				new Group("wbs","ws","wzpjs","rsw","swx"),
				new Group("ecovmudkg","dckvuomge","cgeduvkmo","kexrumgcvold","ogdvcmkeu"),
				new Group("otzhibuwylnpdjk","fqesgmvcx"),
				new Group("uhibntjedrqlkza","zutlekqijbhadnr","lrudvhnxtqbejiwkza","knqdjlhzbrtuiaes"),
				new Group("lzucndsk","kudnslz","dculwnzsk","unpzdlcyk","qutlnrhdkgb"),
				new Group("imvdyc","uym","myrebic","jywxqosan","biry"),
				new Group("e","e","ey","m","ey"),
				new Group("pu","pu","up","pu","up"),
				new Group("nxywbazjhfpmqrl","ptlnhfrjzbqioy"),
				new Group("jhqrpnacxktuywmzolbgid","rcldaozfinhtywukjmgxpbq","xknlraouiemtcjwypdvzgshqb"),
				new Group("hjtbfsawmyqreuxzp","zkmrxelqbfgaijyucvws"),
				new Group("tmuodpivjkbesrnxwhgqly","gkhvptmqodbicuwjsxlr","upilsotvgqmdbjxkwrh"),
				new Group("uchfkdwgvoysazr","ekgnrmjidtphxzlbq"),
				new Group("peynjb","jdetnbha","qknrlxemosb"),
				new Group("okcxgpmeva","camkegoxvp"),
				new Group("ivetwsloarduh","etsdjwviqoau","tsmfwviponeakxdu"),
				new Group("vxoukn","oxvunk","uonxvk"),
				new Group("l","l","l","l"),
				new Group("xpates","pnavtsw"),
				new Group("p","w","u","w","z"),
				new Group("erqphaigsvmkc","aigprevkqmynhsc","pdarkzqcsvbgmeih","gpiemhafqrcksv"),
				new Group("gnfxpcvhyeqklb","nlyegofxhcpkb","pbfckgywxnlhoe","lkshmjptifecnydugxbza","ychrlgnobxkpqfe"),
				new Group("fswnqiyamkrthzeudxlgvocj","ytdzglurakxihjcnfmvesow","wtclfvjgmksuinzxehrydao","gkhzvswmiayludfcexnorjtp","zudegfksxvlnarctwmhyoipj"),
				new Group("hkvuctrxgeqbapdsw","peqskrducgvhxwj","oiqmhekpwvxdcg"),
				new Group("vxzygrsldmjoq","pmbfvrjzktnsyql","rdymqlvjwzs","zomcjlqyrvsxg"),
				new Group("t","x","t"),
				new Group("hidmjcszvwtyulexap","vxpuhsmtiecygjarzd","yipxsazecjhtvdmuk","tveujidzswpmhbycoxa"),
				new Group("bjhowspnxqrilgckzvya","lycxpnjrbvghiwzkoqdas","gnljyzbxswqvkcaoprih","urpoiljxsvagbfkqyhzmcwn","lnjxibqrcpvgszkyhaow"),
				new Group("rxdjupsboghfyqk","ghpcktodiysbaf","pygdfskohnrb","swohdkpgbxmfyez"),
				new Group("qfoyjsuiwglp","dsajgouipqfeyxwl"),
				new Group("ybv","sh"),
				new Group("akgwp","neftcidsmlxvyu","jpb","pwr","oghzqr"),
				new Group("m","m","wm","m"),
				new Group("aesucfwnbmzjixol","lwcsejaniomru"),
				new Group("skrij","rjisk","ieszonkrjbv"),
				new Group("sqil","weulqzi","sqicyl"),
				new Group("hcouimv","moiucvh","ouhvimc","iuochvm","ugihomxcv"),
				new Group("xcdq","kvlwysm"),
				new Group("s","d"),
				new Group("faqkwzdphtslbrm","bsmryfzpkohlnaq","uqghrailbmpzfjsckxv","skdempaqhyflzrb"),
				new Group("iftersaovkmq","itrosfkmvaej","bavftmiosrke","kuvtrsoajfmei"),
				new Group("qi","q","qiw","q","qx"),
				new Group("cbmhaqsynzlkep","ebclhpqsnamzk","kbeunmspclqhaz"),
				new Group("k","k","k"),
				new Group("lsjd","djls","sldj","sljd"),
				new Group("m","m","m","m","m"),
				new Group("tnkdizrqy","injdbgtk","tcisnwa"),
				new Group("oimrgebk","objmgrik"),
				new Group("gzpfiuentbvyrcm","zcysfenlprbutmvg"),
				new Group("iakzlspqyfdoxghevnwctu","vuwhodnxyfqagtzpsceikl","tflnyxasiozdgcvuheqkwp"),
				new Group("a","pygardx","eau","a"),
				new Group("maht","tpmh","hmt","thm"),
				new Group("ociwpsvnjykabufmrgezqldh","famcsnzgvlebjyhroqkpdiuw","zvojpcqiufwkrgydnasemlhbt"),
				new Group("upkhlt","slea"),
				new Group("wxukirhvlfmgo","exykvrhugdblomfw","hlkizfomvgrwxus","sholafwvmukgrx","txwfsmurgvkohl"),
				new Group("ju","l"),
				new Group("wzpf","qwmef","wfe"),
				new Group("ewmxovgbcnijhyk","uklrsgdyzcaeft"),
				new Group("baflvedsuohztjx","lqvzgwxsatefdc","saxbltdefrivz"),
				new Group("cdvmaqkngy","tfrdgkam","agdpmkys","kdmcjag"),
				new Group("ajnpf","fnpaj","fnjap","fpnaj"),
				new Group("waslqkuv","uvwsjakmq","pvyuitqrbwcagoxkzeh"),
				new Group("pcaowt","optca","pacto","poatc"),
				new Group("ephg","gphe","gehp","cespgh","gphe"),
				new Group("bcpo","edcps"),
				new Group("famtdwsbrznj","jdznfrtwmbya","dfrmjawebgtphnqz","jzmnrtafudwb","rbaznwtdjmf"),
				new Group("qmyhwgtcepkd","gkdqtmpyfw","purgdkwoqmtl"),
				new Group("zhvstamfpdc","dtszpcfvamh","dzvhftcpasm"),
				new Group("rgwyks","yhkgfwre","yrsgxo","cadirygtn"),
				new Group("jzdatumwe","hclk","xirsyv","fcbkng"),
				new Group("dtmkaiubljq","mkivbojl","imkjbl","eklmijb"),
				new Group("yjtp","tjy"),
				new Group("jvipbosutw","josgipwkutzb","jsupowbrti","bpikjtsouw","fojtpwbsaui"),
				new Group("e","ehg","fe","e"),
				new Group("fbdpoau","ijhroufmvb","cfbtoul"),
				new Group("rwxplh","whpxlr","wxlprh","lxwrhp"),
				new Group("pncagr","rgnclpa"),
				new Group("vhjyokxtbpu","skuwogrqa"),
				new Group("yratqdoxwcpk","sorywjbenudlxhvapi"),
				new Group("evsktdfwogcuh","zidwgnrcelxyvjmkp"),
				new Group("jcezwrigomdt","hzcdjtiwre","tczweijdrh"),
				new Group("ukcewyhfsapozlx","wciopgukxheylazf","lwekafhuybozxpc","wyhupafeclknzxo","ezcxlkphouwfay"),
				new Group("klfjutwxnhvicympbdrz","npkzcituovfldxgbhwjms","txhwjkifmvuzbdcpln"),
				new Group("ifr","up","p","p","gswo"),
				new Group("xkimf","mxikf"),
				new Group("td","neqdi","wfz","lbsahjokvmpry"),
				new Group("wez","wez","wezr","zwe","ezw"),
				new Group("stfjbc","twfjbcs","bstjfc","tbsfjc","sfbjtc"),
				new Group("asjbkpugrnteyfcomdlh","yoadpfjmubrkltgcneshz","lkrfnpmteyjcsubgzoadh","xghijfescdwtoykpabumqvnrl"),
				new Group("ug","du"),
				new Group("qrvyi","nv","v","vhz","zvm"),
				new Group("uoblqtenkysjdcwmraivfgpzxh","pckigqsolvfnmjauyzhxtwdebr"),
				new Group("wdkrlgqmvuhicnxebatj","rcdvkftqnuiewh","cntediyvhwukqr","vrhqpsiounecwtdk","ounreidwqchkvt"),
				new Group("arelvfzbhkdinoxtgjpcsu","szocvdbfjhranixtkelpug","einpchxzdrktlfubgovjsa","cvbnriuosehxjgdlkpztaf","uzdfcxejbhtvolknrspiga"),
				new Group("dsxcfuzphk","roifcp","cyifvop"),
				new Group("jmil","limj","ljim"),
				new Group("smrjzlwuikq","holtfauyim","umncpieftbl"),
				new Group("kq","wkq","k","cktp"),
				new Group("zoncjltqxyhasigkfwurbmdv","uhbzojkagtxcvdrwlsfynqmi","xhlyswojgrzcvktbfqidaumn","qtgswjoaivybnhcfrxklmduz","nhvwitqxalkjrdmsguofcyzb"),
				new Group("su","nhu","us","u"),
				new Group("stxofjnyvhizmelagbdwpuc","rbfnweycogqztipsaljxkd"),
				new Group("rmyclkwgqfheja","qgjucrzyemlwakh","kphqegadcwmuryj","taxrkcevbqghjymw"),
				new Group("lugcahsyrjnoxpzem","espgjrnyzcuhmlaox","jmgrcnsazoehlxup","nfepgjluzhcadxmrso","srlnjcpzmeoghaxu"),
				new Group("bcqrkadhz","dcbhkza","hzndimkac","dqkczhba"),
				new Group("qglersz","vszlehq","zfjueilqsd","eszlq","zsqler"),
				new Group("twcekgfq"),
				new Group("rcmyhawqtgbjiflpxezn","aelwqgjmtzycrfpnhxib","xnrfbgjtqzyaplmchwie"),
				new Group("yhacs","mawnvjkeyqcighs","tuahycs"),
				new Group("iw","tdgkpi"),
				new Group("nizjlemapcwx","tsuoqkjbhygdv"),
				new Group("pyusefbwjrvgz","bjfzpwsuyegr","jrsxohcegwfpzuyb"),
				new Group("ekxdmsjzuntai","zxdaujmtnikes","jndizketuasxm","njqakpsuzitefxrgdm"),
				new Group("ehvknu","hzukmn","nbtdksxrg","akn","naehok"),
				new Group("wipbuyzs","ysbq","dxyqbjst","gsyxdb"),
				new Group("smhkvxwtgj","htkgmvqsxcj","tujghmsxikv","hxvsmytgkjd"),
				new Group("ynm","un","ykn"),
				new Group("qebgu","qgrblhej","uhrq","mnfokqxy"),
				new Group("mcvy","tsaup","us","kqhw"),
				new Group("vwm","mvjwq","cmswv","vwjm","zwavm"),
				new Group("enfqx","enxfq","fexqn"),
				new Group("xsmzl","bqpoejwhzi","gxzc","rfzn","zrv"),
				new Group("oueayjq","jyu"),
				new Group("xrzqts","rz","yegnbuz","cjqwzxisr"),
				new Group("dnwqumcg","kntyfqhm","tnmfq"),
				new Group("sy","xh"),
				new Group("esknr","brpym"),
				new Group("syh","yia","ykn","bpmyzo"),
				new Group("ebhmyz","mebyhz","ezhybm"),
				new Group("omzvarex","mzoarex","mrozaex","zaomrxe"),
				new Group("fecarzihbklsodvp","vdbhpaizlefrsc","rfeiapvszdhlbqc","sfpbaiqvchlrdze"),
				new Group("zvjxlgfokbhupn","aluigxdtwqves"),
				new Group("cseko","ose","ecso","wsegjoa"),
				new Group("bmdru","nw","nia","ija"),
				new Group("lnapozb","anpbzolhy","zrbajnluop","lopznba"),
				new Group("iuhorckt","dsitafk","xlkvefit","dfikxzltg","lktniv"),
				new Group("ibgjqwx","biwqgjx"),
				new Group("ofpcnjzmwxtvglbysuqrkadh","qfghmrdljbksxzovuawnctyp","tqxkvnmrjgpahylcsbdzwfuo","uqxmlkfdnrjovatsgzwpbhcy","jfsagdqxrvpcnohubkzmtlyw"),
				new Group("nsofzrtgc","fjtcsgoni","ftigacno","houpnqfcgt","nfctgvxlyom"),
				new Group("gtlrszh","tlghsrz"),
				new Group("ciygwfesbtv","hvcyb"),
				new Group("otupmldwkhbvyxrni","bdwthuylsvpxkmnor","nxktbmlyvpdhwsoru","mkbantvwxyguophdrl"),
				new Group("vlx","xlvh","lxv"),
				new Group("falrxm","abrml"),
				new Group("cz","fe","ltxz"),
				new Group("zh","hz","zh"),
				new Group("vlpungo","vnploug","nvupgol"),
				new Group("aihvwxomyseqjrup","vxtbglcnhoewqszud"),
				new Group("evdfhlanzowmj","wjfakoizvlyume","jeadzfswclmvqo"),
				new Group("vofnaxpuqdjzk","tkxouzdqypvaf","sfaimwuoerx"),
				new Group("yiqjnrmwg","cnkzxdebopls"),
				new Group("mxuyznpkdslobfqethjvgcwi","dhygwolniuzkmfqtjbexpcsv","jtnbavpgulcsfwzmeydkixhq"),
				new Group("pwqcdsagneux","apwdslczguex"),
				new Group("ochfgitkpjmxvbwsyalz","pqfoehjmklytngxzsa"),
				new Group("zwcdvjyuxm","jvxuczdm","jcuxdmzv"),
				new Group("ex","xe","ex"),
				new Group("bruqxpnt","rtnxqu"),
				new Group("cqmpedhtwa","hjnweafbtmydckvgi","coxdwrplmheta","owmdqctaeh"),
				new Group("eonvhayprlubmkdxcwqgt","mbuqcnylwxekorvtphda","ltqohvydpemxknabwucr"),
				new Group("bviypkgrtaucmjeo","jpsbalymxkfcvdzoie"),
				new Group("vxlqyrfp","vqplyxfr","yqrplxvf","lvyrqxpf","rwqplfyvx"),
				new Group("x","x","x","l"),
				new Group("yuvo","oyvu"),
				new Group("dqevksywtmajxhuorncgziflb","saberqxvnhjiwkgdyzfltc","kvyjwgqcathexndlzsbfri"),
				new Group("rmpl","matsrkl"),
				new Group("dqw","dwq","wpdq","wjsdq","qrkwd"),
				new Group("vmoltnku","wnatmlzqgo","nvoutlm","ontxmvl","tolxmn"),
				new Group("rjqvugxpbwd","jgdbwsprqvu","jdqupyvgwrbe"),
				new Group("mkibxclpud","cumrkl","hlztkmasvcwguo"),
				new Group("ju","u","u","u"),
				new Group("hvoizamdru","puqftvdjr","rgwsctbvdukf","vdlkrpuxte","rjxvwybudq"),
				new Group("th","aqbf","tqfkyv","ocw","lnxzijmpu"),
				new Group("isdxlmekbpyvrazoqngjhfw","nczselimvurpbxoywgafhq","ymbhasxeliofwqgnrpzv","xmpnzhyiablsqerguvowf","vumoseywazfinhpqblxgr"),
				new Group("w","juv","wi","c","vw"),
				new Group("fjx","fj","twayjeqo","jhx","jzr"),
				new Group("w","cq","fj"),
				new Group("pnysjzkwmeaxgtirdf","itgzyernwxkapdsfm","rbkawofqxsinmzytgled","sfnxytiwzmgakerd"),
				new Group("ygnmzdhkxpe","zktnlepuh"),
				new Group("jsbfpuwvkiehgr","ejkrifnwvbgshplu","vcjbhsigfukwpre","pbjfhesukgwvri","wvkrsbeugjhipfy"),
				new Group("oxzwnftk","oxwt","wouxt"),
				new Group("nycmubiopg","gbutcomnyp","uboypnkcgm","poxndgyubmc"),
				new Group("wpodjnyhtqukexc","ihjlvwdfguzpnxaet","tojydphkwcxnuem"),
				new Group("dfyopwrhjcmxbiku","mbawgjorfhpildyucx","uihbwdocmvnspyqfx"),
				new Group("brgjymfaw","vrjywbgpf","ywzbjgf","ibeckofyj"),
				new Group("sktrbg","ulyndkbs","kuvzabse","jpbhxsomck","ksbqfi"),
				new Group("lrkbaizhtpguwjq","vgnouwhlabzirkpjqt","tukpjrbzaigqlweh","ulasbqtpwhkzgijr","zktiwbjuqsahlgpr"),
				new Group("ipasgukbhcfwlt","gzswubeqcalpif","wpslbiguxaemfc","napwlgqfisxcbu"),
				new Group("tgcirbmwx","agxyqrmwztc","qgxmczwtr","fnoxrwgjklmtec"),
				new Group("iqthapgwsyzumejnd","dxfvsceugokqlwmbyzjpr"),
				new Group("ixms","mpsi"),
				new Group("gjoxrcmt","xrjgtomc"),
				new Group("rxikogsafteqbupm","dgtqnkwescbrpmojafzi","regptqlkaisybmfo"),
				new Group("gcsnyeojwl","ljeoyhcng"),
				new Group("rboeafpxktihsqnc","fhjokdgqinwze","oihfmkynqxe"),
				new Group("rjuyhaqmliwckg","ximcfzgwyrlhn","hlrgtcsimwxy"),
				new Group("wpfqculrmxos","cojqs","qcszo","ozcsq"),
				new Group("ilbezokgtpwmu","rkdfphtzcyw"),
				new Group("xda","bfqugt","eadh","h","h"),
				new Group("ejvpamsgd","dgemiloau","dmeasg","jademg"),
				new Group("jfagcbmxyl","bycfgjlmax"),
				new Group("gobmlcir","roicglbp","bicglro","ciobrlg"),
				new Group("jiqowhr","mbiqr","qirm","qrbil"),
				new Group("eamlhtgvzsjoxyuinrpwqbd","btonqpwgjamhrlsixyvzdue"),
				new Group("rhnamzcvkqbdpftgwi","tmbpkihdwzagvrfnq","wkpdtzqmfgisbvnarh","mwkbihgpfrnadtvqz"),
				new Group("pdstumbzqalr","amzqwdrutpbls","rqubzdpatmsl","stzprabdmulq"),
				new Group("lf","f","f"),
				new Group("jdegpfinlz","xplfnegdzj","gnalepfdzj","xjeldpzgnf","zdspgnfwyelj"),
				new Group("ubly","neqswi"),
				new Group("efrjdg","xwdrbtj","xkjdvb","pjuadqo","dbj"),
				new Group("yrwq","yqr","rqy"),
				new Group("vsxcwouzegqak","ynfcl","lrbc","rcjh"),
				new Group("ikxnftdovcphzae","adpitzckovxhnef","cilfohenpdzxtvka","ehitodpkvfzxcna"),
				new Group("te","famtuj","intfreudw","sxopkqgbl"),
				new Group("pmjsxaekqlrdobwufnztvg","wuqrkvbgopatsemlnzxd","svonbdeqagtzwlpcukmrx","ksuzlaernbcwovxgqdpmt","wxetnlqazbpgskvomdur"),
				new Group("skpvxloqduizwatrgfnyc","xaeyvgcfwpikoutnd","gyanbjxwmitocpkufdv"),
				new Group("ntuwlfqjyvrak","txivfyoldejunacg"),
				new Group("n","q","q"),
				new Group("sidtzk","lzsondqitk","tskzid"),
				new Group("hopdv","hpdo","ohrcdp"),
				new Group("ncdj","cjda","ydkjrv"),
				new Group("brtahsneojzq","zejbnswvqoahyxr","rmhosqeabjnz","aebsjoqtmzrnh"),
				new Group("a","yq","mj"),
				new Group("zmcfrgsxenlkja","vupsyjwrhq"),
				new Group("grbxsd","kpsygnarx","rjbgsex","ejvgwlsrx"),
				new Group("dqrzwiux","iurdwz","uidwzrp","zwidrum","uwzrid"),
				new Group("exmywtp","wempt","tpwem","tpwme"),
				new Group("arlhfxdcmv","vsmrhclkqfi","vrcphfmadl"),
				new Group("kylhz","zly","zly"),
				new Group("tal","tal","a","al","daevb"));

		// Part two
		count = 0;
		for (Group group : input2) {
			Map<String, Integer> map = new LinkedHashMap<>();
			for (String answer : group.answers) {
				String[] list = Utils.tail(answer.split(""));
				for (String el : list) {
					if (map.containsKey(el)) {
						map.put(el, map.get(el) + 1);
					} else {
						map.put(el, 1);
					}
					
				}
			}
			for (Entry<String, Integer> entry : map.entrySet()) {
				if (entry.getValue() == group.size()) {
					count++;
				}
			}
		}
		System.out.println(count);

	}
	
	private <T> List<T> removeDuplicate(List<T> list) {
		return new ArrayList<T>(new LinkedHashSet<T>(list));
	}
	
	class Group {
		List<String> answers;
		Group(String... answers) {
			this.answers = Arrays.asList(answers);
		}
		int size() {
			return answers.size();
		}
	}

}
