
import static org.junit.Assert.assertEquals;

import java.util.Arrays;
import java.util.List;

import org.junit.Test;

public class Day12 {
	
	List<Instruction> instructions = Arrays.asList(new Instruction("N",5),
			new Instruction("W",1),
			new Instruction("F",61),
			new Instruction("W",2),
			new Instruction("R",90),
			new Instruction("F",50),
			new Instruction("N",2),
			new Instruction("F",40),
			new Instruction("E",4),
			new Instruction("F",48),
			new Instruction("R",180),
			new Instruction("F",17),
			new Instruction("W",4),
			new Instruction("N",5),
			new Instruction("F",3),
			new Instruction("W",3),
			new Instruction("F",1),
			new Instruction("R",90),
			new Instruction("S",2),
			new Instruction("F",23),
			new Instruction("L",90),
			new Instruction("S",3),
			new Instruction("W",3),
			new Instruction("S",4),
			new Instruction("E",4),
			new Instruction("L",90),
			new Instruction("W",3),
			new Instruction("S",3),
			new Instruction("E",4),
			new Instruction("N",2),
			new Instruction("F",28),
			new Instruction("S",2),
			new Instruction("W",2),
			new Instruction("L",180),
			new Instruction("E",3),
			new Instruction("R",90),
			new Instruction("E",3),
			new Instruction("F",83),
			new Instruction("W",5),
			new Instruction("S",4),
			new Instruction("W",3),
			new Instruction("N",2),
			new Instruction("W",5),
			new Instruction("F",90),
			new Instruction("N",2),
			new Instruction("F",82),
			new Instruction("N",2),
			new Instruction("F",2),
			new Instruction("S",4),
			new Instruction("L",90),
			new Instruction("N",3),
			new Instruction("L",90),
			new Instruction("S",2),
			new Instruction("F",12),
			new Instruction("S",3),
			new Instruction("F",40),
			new Instruction("L",90),
			new Instruction("F",56),
			new Instruction("N",1),
			new Instruction("F",29),
			new Instruction("W",2),
			new Instruction("S",2),
			new Instruction("R",270),
			new Instruction("S",4),
			new Instruction("F",14),
			new Instruction("E",4),
			new Instruction("R",90),
			new Instruction("E",2),
			new Instruction("S",2),
			new Instruction("E",2),
			new Instruction("F",82),
			new Instruction("L",90),
			new Instruction("N",3),
			new Instruction("R",180),
			new Instruction("R",90),
			new Instruction("S",1),
			new Instruction("W",1),
			new Instruction("L",90),
			new Instruction("S",2),
			new Instruction("F",78),
			new Instruction("W",2),
			new Instruction("F",52),
			new Instruction("N",4),
			new Instruction("W",5),
			new Instruction("F",38),
			new Instruction("L",90),
			new Instruction("W",2),
			new Instruction("S",2),
			new Instruction("L",90),
			new Instruction("F",66),
			new Instruction("R",90),
			new Instruction("F",62),
			new Instruction("E",3),
			new Instruction("S",5),
			new Instruction("L",90),
			new Instruction("F",99),
			new Instruction("F",2),
			new Instruction("E",4),
			new Instruction("R",90),
			new Instruction("N",3),
			new Instruction("W",4),
			new Instruction("N",1),
			new Instruction("F",71),
			new Instruction("E",2),
			new Instruction("N",3),
			new Instruction("N",2),
			new Instruction("R",90),
			new Instruction("E",2),
			new Instruction("F",66),
			new Instruction("S",4),
			new Instruction("R",90),
			new Instruction("E",5),
			new Instruction("F",29),
			new Instruction("E",5),
			new Instruction("L",90),
			new Instruction("W",2),
			new Instruction("N",2),
			new Instruction("E",3),
			new Instruction("F",18),
			new Instruction("L",180),
			new Instruction("F",17),
			new Instruction("W",1),
			new Instruction("R",90),
			new Instruction("W",3),
			new Instruction("S",5),
			new Instruction("R",90),
			new Instruction("S",3),
			new Instruction("R",180),
			new Instruction("N",5),
			new Instruction("F",69),
			new Instruction("W",1),
			new Instruction("W",3),
			new Instruction("L",180),
			new Instruction("F",72),
			new Instruction("W",5),
			new Instruction("N",1),
			new Instruction("R",180),
			new Instruction("W",3),
			new Instruction("W",4),
			new Instruction("F",85),
			new Instruction("W",4),
			new Instruction("L",90),
			new Instruction("E",4),
			new Instruction("N",5),
			new Instruction("F",73),
			new Instruction("R",90),
			new Instruction("F",70),
			new Instruction("E",4),
			new Instruction("F",79),
			new Instruction("S",5),
			new Instruction("R",180),
			new Instruction("E",2),
			new Instruction("F",35),
			new Instruction("E",4),
			new Instruction("L",270),
			new Instruction("W",2),
			new Instruction("L",90),
			new Instruction("N",5),
			new Instruction("R",90),
			new Instruction("N",4),
			new Instruction("F",64),
			new Instruction("W",2),
			new Instruction("R",270),
			new Instruction("F",33),
			new Instruction("N",5),
			new Instruction("E",4),
			new Instruction("F",94),
			new Instruction("W",1),
			new Instruction("N",1),
			new Instruction("R",90),
			new Instruction("F",79),
			new Instruction("F",46),
			new Instruction("E",1),
			new Instruction("R",180),
			new Instruction("S",3),
			new Instruction("W",3),
			new Instruction("F",72),
			new Instruction("E",1),
			new Instruction("W",4),
			new Instruction("F",95),
			new Instruction("W",2),
			new Instruction("L",90),
			new Instruction("N",3),
			new Instruction("L",90),
			new Instruction("F",85),
			new Instruction("W",3),
			new Instruction("W",1),
			new Instruction("F",54),
			new Instruction("N",3),
			new Instruction("E",1),
			new Instruction("N",4),
			new Instruction("E",5),
			new Instruction("L",90),
			new Instruction("F",61),
			new Instruction("W",2),
			new Instruction("F",7),
			new Instruction("L",180),
			new Instruction("F",87),
			new Instruction("N",4),
			new Instruction("W",1),
			new Instruction("F",87),
			new Instruction("F",3),
			new Instruction("E",3),
			new Instruction("F",63),
			new Instruction("R",90),
			new Instruction("S",4),
			new Instruction("R",180),
			new Instruction("S",4),
			new Instruction("R",180),
			new Instruction("R",90),
			new Instruction("R",90),
			new Instruction("E",5),
			new Instruction("N",4),
			new Instruction("E",2),
			new Instruction("F",86),
			new Instruction("S",3),
			new Instruction("F",98),
			new Instruction("N",4),
			new Instruction("F",70),
			new Instruction("L",90),
			new Instruction("E",4),
			new Instruction("F",26),
			new Instruction("W",4),
			new Instruction("F",19),
			new Instruction("L",90),
			new Instruction("S",4),
			new Instruction("W",4),
			new Instruction("F",84),
			new Instruction("N",1),
			new Instruction("E",4),
			new Instruction("L",180),
			new Instruction("S",2),
			new Instruction("F",74),
			new Instruction("S",1),
			new Instruction("F",86),
			new Instruction("R",90),
			new Instruction("S",2),
			new Instruction("F",78),
			new Instruction("N",4),
			new Instruction("S",2),
			new Instruction("W",1),
			new Instruction("N",5),
			new Instruction("E",2),
			new Instruction("F",38),
			new Instruction("W",4),
			new Instruction("N",1),
			new Instruction("F",75),
			new Instruction("S",1),
			new Instruction("E",1),
			new Instruction("N",3),
			new Instruction("S",1),
			new Instruction("F",54),
			new Instruction("N",3),
			new Instruction("F",88),
			new Instruction("N",5),
			new Instruction("L",180),
			new Instruction("F",15),
			new Instruction("S",2),
			new Instruction("S",2),
			new Instruction("E",2),
			new Instruction("N",3),
			new Instruction("F",97),
			new Instruction("S",3),
			new Instruction("N",3),
			new Instruction("E",3),
			new Instruction("N",5),
			new Instruction("E",3),
			new Instruction("R",90),
			new Instruction("F",87),
			new Instruction("L",90),
			new Instruction("F",15),
			new Instruction("L",90),
			new Instruction("E",5),
			new Instruction("R",90),
			new Instruction("F",70),
			new Instruction("N",3),
			new Instruction("W",2),
			new Instruction("F",47),
			new Instruction("W",2),
			new Instruction("W",3),
			new Instruction("F",17),
			new Instruction("R",90),
			new Instruction("F",95),
			new Instruction("E",4),
			new Instruction("F",28),
			new Instruction("W",4),
			new Instruction("R",90),
			new Instruction("E",2),
			new Instruction("R",180),
			new Instruction("N",4),
			new Instruction("R",180),
			new Instruction("W",4),
			new Instruction("R",270),
			new Instruction("F",73),
			new Instruction("W",1),
			new Instruction("N",2),
			new Instruction("L",90),
			new Instruction("S",1),
			new Instruction("F",65),
			new Instruction("E",1),
			new Instruction("F",42),
			new Instruction("N",2),
			new Instruction("F",74),
			new Instruction("R",90),
			new Instruction("F",21),
			new Instruction("W",5),
			new Instruction("S",1),
			new Instruction("N",5),
			new Instruction("R",90),
			new Instruction("E",4),
			new Instruction("N",5),
			new Instruction("S",5),
			new Instruction("F",99),
			new Instruction("W",4),
			new Instruction("L",180),
			new Instruction("W",1),
			new Instruction("F",83),
			new Instruction("N",2),
			new Instruction("W",2),
			new Instruction("F",87),
			new Instruction("E",2),
			new Instruction("S",3),
			new Instruction("W",1),
			new Instruction("L",180),
			new Instruction("F",89),
			new Instruction("S",1),
			new Instruction("W",2),
			new Instruction("E",2),
			new Instruction("L",90),
			new Instruction("S",2),
			new Instruction("W",1),
			new Instruction("S",5),
			new Instruction("R",180),
			new Instruction("E",5),
			new Instruction("N",1),
			new Instruction("F",82),
			new Instruction("S",3),
			new Instruction("F",7),
			new Instruction("L",90),
			new Instruction("F",31),
			new Instruction("L",90),
			new Instruction("N",3),
			new Instruction("F",84),
			new Instruction("W",3),
			new Instruction("N",4),
			new Instruction("F",100),
			new Instruction("N",1),
			new Instruction("E",2),
			new Instruction("R",90),
			new Instruction("F",90),
			new Instruction("N",3),
			new Instruction("F",43),
			new Instruction("R",90),
			new Instruction("F",2),
			new Instruction("W",4),
			new Instruction("L",90),
			new Instruction("F",87),
			new Instruction("L",90),
			new Instruction("E",3),
			new Instruction("F",71),
			new Instruction("L",180),
			new Instruction("N",1),
			new Instruction("L",90),
			new Instruction("E",4),
			new Instruction("N",3),
			new Instruction("F",31),
			new Instruction("W",1),
			new Instruction("F",80),
			new Instruction("R",270),
			new Instruction("N",1),
			new Instruction("E",4),
			new Instruction("N",1),
			new Instruction("F",22),
			new Instruction("N",4),
			new Instruction("E",1),
			new Instruction("F",57),
			new Instruction("R",90),
			new Instruction("N",3),
			new Instruction("W",2),
			new Instruction("L",180),
			new Instruction("N",3),
			new Instruction("L",180),
			new Instruction("W",4),
			new Instruction("F",59),
			new Instruction("S",4),
			new Instruction("F",10),
			new Instruction("N",5),
			new Instruction("L",90),
			new Instruction("S",3),
			new Instruction("L",90),
			new Instruction("E",1),
			new Instruction("F",96),
			new Instruction("E",4),
			new Instruction("N",3),
			new Instruction("F",54),
			new Instruction("L",180),
			new Instruction("F",47),
			new Instruction("W",1),
			new Instruction("N",4),
			new Instruction("E",1),
			new Instruction("S",4),
			new Instruction("R",180),
			new Instruction("L",90),
			new Instruction("N",1),
			new Instruction("R",90),
			new Instruction("N",3),
			new Instruction("R",90),
			new Instruction("N",4),
			new Instruction("R",90),
			new Instruction("S",3),
			new Instruction("F",59),
			new Instruction("N",5),
			new Instruction("L",90),
			new Instruction("E",4),
			new Instruction("F",72),
			new Instruction("W",4),
			new Instruction("F",76),
			new Instruction("R",90),
			new Instruction("E",3),
			new Instruction("F",70),
			new Instruction("L",180),
			new Instruction("N",3),
			new Instruction("W",2),
			new Instruction("R",90),
			new Instruction("F",65),
			new Instruction("L",90),
			new Instruction("F",71),
			new Instruction("S",3),
			new Instruction("F",43),
			new Instruction("R",90),
			new Instruction("W",2),
			new Instruction("N",2),
			new Instruction("R",90),
			new Instruction("W",1),
			new Instruction("R",90),
			new Instruction("S",4),
			new Instruction("R",180),
			new Instruction("S",1),
			new Instruction("E",3),
			new Instruction("F",72),
			new Instruction("L",90),
			new Instruction("F",61),
			new Instruction("L",90),
			new Instruction("F",75),
			new Instruction("S",1),
			new Instruction("S",5),
			new Instruction("F",15),
			new Instruction("R",90),
			new Instruction("E",3),
			new Instruction("N",2),
			new Instruction("L",270),
			new Instruction("F",48),
			new Instruction("N",1),
			new Instruction("R",180),
			new Instruction("W",2),
			new Instruction("F",69),
			new Instruction("E",4),
			new Instruction("R",90),
			new Instruction("R",90),
			new Instruction("W",1),
			new Instruction("S",5),
			new Instruction("W",5),
			new Instruction("R",90),
			new Instruction("S",4),
			new Instruction("S",3),
			new Instruction("F",51),
			new Instruction("F",43),
			new Instruction("E",2),
			new Instruction("N",5),
			new Instruction("L",180),
			new Instruction("F",89),
			new Instruction("W",1),
			new Instruction("R",90),
			new Instruction("F",59),
			new Instruction("R",90),
			new Instruction("E",2),
			new Instruction("F",51),
			new Instruction("R",90),
			new Instruction("F",91),
			new Instruction("W",4),
			new Instruction("S",5),
			new Instruction("E",4),
			new Instruction("L",90),
			new Instruction("S",5),
			new Instruction("R",90),
			new Instruction("F",44),
			new Instruction("F",47),
			new Instruction("E",4),
			new Instruction("W",1),
			new Instruction("F",77),
			new Instruction("S",5),
			new Instruction("R",90),
			new Instruction("N",2),
			new Instruction("F",87),
			new Instruction("N",4),
			new Instruction("R",90),
			new Instruction("W",5),
			new Instruction("R",90),
			new Instruction("W",5),
			new Instruction("F",89),
			new Instruction("L",90),
			new Instruction("F",61),
			new Instruction("E",2),
			new Instruction("F",29),
			new Instruction("N",4),
			new Instruction("R",90),
			new Instruction("F",31),
			new Instruction("S",1),
			new Instruction("L",90),
			new Instruction("E",5),
			new Instruction("N",2),
			new Instruction("F",7),
			new Instruction("L",180),
			new Instruction("S",4),
			new Instruction("F",63),
			new Instruction("W",4),
			new Instruction("N",5),
			new Instruction("S",2),
			new Instruction("N",1),
			new Instruction("E",5),
			new Instruction("F",87),
			new Instruction("S",5),
			new Instruction("R",180),
			new Instruction("F",14),
			new Instruction("W",4),
			new Instruction("R",180),
			new Instruction("E",1),
			new Instruction("L",90),
			new Instruction("F",67),
			new Instruction("E",2),
			new Instruction("L",90),
			new Instruction("E",5),
			new Instruction("S",2),
			new Instruction("L",90),
			new Instruction("W",2),
			new Instruction("R",90),
			new Instruction("F",94),
			new Instruction("W",4),
			new Instruction("R",90),
			new Instruction("W",3),
			new Instruction("S",3),
			new Instruction("R",90),
			new Instruction("N",5),
			new Instruction("F",55),
			new Instruction("L",90),
			new Instruction("F",43),
			new Instruction("L",90),
			new Instruction("N",5),
			new Instruction("F",16),
			new Instruction("E",4),
			new Instruction("N",2),
			new Instruction("L",270),
			new Instruction("W",3),
			new Instruction("E",1),
			new Instruction("N",2),
			new Instruction("R",180),
			new Instruction("F",51),
			new Instruction("N",5),
			new Instruction("N",1),
			new Instruction("F",36),
			new Instruction("W",4),
			new Instruction("F",38),
			new Instruction("N",5),
			new Instruction("W",1),
			new Instruction("F",29),
			new Instruction("R",180),
			new Instruction("L",90),
			new Instruction("N",1),
			new Instruction("W",3),
			new Instruction("E",1),
			new Instruction("F",78),
			new Instruction("E",1),
			new Instruction("N",1),
			new Instruction("E",2),
			new Instruction("F",57),
			new Instruction("E",4),
			new Instruction("F",83),
			new Instruction("W",5),
			new Instruction("F",32),
			new Instruction("N",3),
			new Instruction("W",4),
			new Instruction("F",36),
			new Instruction("N",2),
			new Instruction("E",3),
			new Instruction("F",74),
			new Instruction("N",4),
			new Instruction("F",54),
			new Instruction("W",5),
			new Instruction("L",90),
			new Instruction("S",1),
			new Instruction("F",42),
			new Instruction("W",4),
			new Instruction("S",5),
			new Instruction("E",3),
			new Instruction("F",64),
			new Instruction("W",2),
			new Instruction("R",180),
			new Instruction("S",2),
			new Instruction("E",1),
			new Instruction("N",2),
			new Instruction("R",90),
			new Instruction("W",3),
			new Instruction("F",36),
			new Instruction("N",3),
			new Instruction("R",90),
			new Instruction("S",2),
			new Instruction("F",53),
			new Instruction("W",2),
			new Instruction("F",85),
			new Instruction("E",5),
			new Instruction("N",2),
			new Instruction("F",9),
			new Instruction("E",1),
			new Instruction("F",83),
			new Instruction("L",90),
			new Instruction("E",5),
			new Instruction("F",44),
			new Instruction("L",90),
			new Instruction("F",92),
			new Instruction("W",5),
			new Instruction("R",270),
			new Instruction("E",4),
			new Instruction("S",1),
			new Instruction("F",6),
			new Instruction("L",90),
			new Instruction("F",96),
			new Instruction("R",90),
			new Instruction("N",1),
			new Instruction("E",4),
			new Instruction("N",1),
			new Instruction("W",3),
			new Instruction("S",2),
			new Instruction("S",4),
			new Instruction("F",39),
			new Instruction("E",1),
			new Instruction("S",1),
			new Instruction("F",82),
			new Instruction("S",3),
			new Instruction("F",78),
			new Instruction("L",90),
			new Instruction("N",4),
			new Instruction("E",1),
			new Instruction("N",2),
			new Instruction("R",90),
			new Instruction("F",63),
			new Instruction("S",3),
			new Instruction("L",180),
			new Instruction("F",52),
			new Instruction("W",2),
			new Instruction("F",49),
			new Instruction("W",2),
			new Instruction("L",270),
			new Instruction("N",1),
			new Instruction("R",180),
			new Instruction("E",3),
			new Instruction("F",79),
			new Instruction("F",73),
			new Instruction("N",1),
			new Instruction("R",90),
			new Instruction("N",3),
			new Instruction("R",180),
			new Instruction("S",2),
			new Instruction("F",35),
			new Instruction("S",1),
			new Instruction("F",43),
			new Instruction("S",1),
			new Instruction("R",90),
			new Instruction("S",4),
			new Instruction("W",4),
			new Instruction("F",12),
			new Instruction("S",1),
			new Instruction("F",2),
			new Instruction("N",3),
			new Instruction("E",4),
			new Instruction("L",90),
			new Instruction("F",51),
			new Instruction("R",90),
			new Instruction("N",4),
			new Instruction("F",90),
			new Instruction("R",90),
			new Instruction("F",99),
			new Instruction("E",3),
			new Instruction("N",1),
			new Instruction("R",90),
			new Instruction("S",3),
			new Instruction("L",270),
			new Instruction("W",5),
			new Instruction("L",90),
			new Instruction("R",270),
			new Instruction("F",50),
			new Instruction("N",5),
			new Instruction("F",33),
			new Instruction("S",3),
			new Instruction("F",18),
			new Instruction("L",90),
			new Instruction("E",4),
			new Instruction("L",180),
			new Instruction("W",4),
			new Instruction("R",90),
			new Instruction("F",21),
			new Instruction("W",4),
			new Instruction("F",24),
			new Instruction("W",2),
			new Instruction("E",5),
			new Instruction("N",3),
			new Instruction("W",1),
			new Instruction("R",90),
			new Instruction("W",3),
			new Instruction("S",3),
			new Instruction("F",82),
			new Instruction("W",1),
			new Instruction("S",1),
			new Instruction("F",12),
			new Instruction("N",3),
			new Instruction("L",90),
			new Instruction("F",37),
			new Instruction("R",180),
			new Instruction("F",36),
			new Instruction("F",27),
			new Instruction("E",3),
			new Instruction("S",3),
			new Instruction("F",36),
			new Instruction("W",4),
			new Instruction("S",1),
			new Instruction("F",6),
			new Instruction("R",90),
			new Instruction("F",59),
			new Instruction("S",1),
			new Instruction("E",1),
			new Instruction("R",180),
			new Instruction("S",2),
			new Instruction("W",3),
			new Instruction("L",90),
			new Instruction("F",45),
			new Instruction("R",90),
			new Instruction("E",1),
			new Instruction("F",29),
			new Instruction("S",5),
			new Instruction("W",3),
			new Instruction("S",5),
			new Instruction("W",4),
			new Instruction("L",270),
			new Instruction("S",2),
			new Instruction("F",13),
			new Instruction("E",4),
			new Instruction("F",28),
			new Instruction("R",90),
			new Instruction("F",80),
			new Instruction("S",4),
			new Instruction("E",1),
			new Instruction("S",2),
			new Instruction("F",62),
			new Instruction("R",90),
			new Instruction("F",26),
			new Instruction("L",180),
			new Instruction("F",19),
			new Instruction("W",2),
			new Instruction("L",180),
			new Instruction("W",5),
			new Instruction("F",15),
			new Instruction("N",1),
			new Instruction("F",68),
			new Instruction("E",4),
			new Instruction("F",75),
			new Instruction("S",2),
			new Instruction("F",58),
			new Instruction("S",4),
			new Instruction("R",180),
			new Instruction("E",3),
			new Instruction("N",1),
			new Instruction("L",90),
			new Instruction("S",2),
			new Instruction("F",12),
			new Instruction("R",90),
			new Instruction("E",5),
			new Instruction("S",5),
			new Instruction("W",4),
			new Instruction("N",5),
			new Instruction("W",1),
			new Instruction("R",180),
			new Instruction("S",1),
			new Instruction("F",70),
			new Instruction("R",90),
			new Instruction("F",97),
			new Instruction("L",90),
			new Instruction("E",3),
			new Instruction("S",3),
			new Instruction("L",270),
			new Instruction("E",1),
			new Instruction("F",51),
			new Instruction("N",4),
			new Instruction("L",180),
			new Instruction("N",1),
			new Instruction("R",90),
			new Instruction("F",42));

	@Test
	public void test() {
		// Testing
		Ship test = new Ship();
		test.facing = Direction.North;
		test.doInstruction(new Instruction("L", 180));
		test.doInstruction(new Instruction("F", 3));
		assertEquals(3, test.getManhattanDistance());
		
		// Part one
		Ship ship = new Ship();
		for (Instruction instruction : instructions) {
			ship.doInstruction(instruction);
		}
		assertEquals(2270, ship.getManhattanDistance());
		
		// Part two
		ship = new Ship();
		for (Instruction instruction : instructions) {
			ship.doInstructionWithWayPoint(instruction);
		}
		System.out.println(ship.getManhattanDistance());
		
	}
	
	class Instruction {
		String operator;
		int value;
		Instruction(String operator, int value) {
			this.operator = operator;
			this.value = value;
		}
	}

	class Ship {
		Direction facing;
		int valueNorth;
		int valueEast;
		WayPoint waypoint;
		
		Ship() {
			this.facing = Direction.East;
			this.valueEast = 0;
			this.valueNorth = 0;
			this.waypoint = new WayPoint();
		}

		void doInstruction(Instruction instruction) {
			int value = instruction.value;
			if (instruction.operator == "N") {
				valueNorth += value;
			} else if (instruction.operator == "S") {
				valueNorth -= value;
			} else if (instruction.operator == "W") {
				valueEast -= value;
			} else if (instruction.operator == "E") {
				valueEast += value;
			} else if (instruction.operator == "L") {
				value /= 90;
				changeDirection("L", value);;
			} else if (instruction.operator == "R") {
				value /= 90;
				changeDirection("R", value);
			} else if (instruction.operator == "F") {
				goForward(value);
			}
		}

		void doInstructionWithWayPoint(Instruction instruction) {
			int value = instruction.value;
			if (instruction.operator == "N") {
				waypoint.north += value;
			} else if (instruction.operator == "S") {
				waypoint.north -= value;
			} else if (instruction.operator == "W") {
				waypoint.east -= value;
			} else if (instruction.operator == "E") {
				waypoint.east += value;
			} else if (instruction.operator == "L") {
				value /= 90;
				value %= 4;
				changeWayPointDirection("L", value);
			} else if (instruction.operator == "R") {
				value /= 90;
				value %= 4;
				changeWayPointDirection("R", value);
			} else if (instruction.operator == "F") {
				goForwardWayPoint(value);
			}
		}
		
		void goForward(int value) {
			switch(facing) {
				case North: valueNorth += value; break;
				case West: valueEast -= value; break;
				case South: valueNorth -= value; break;
				case East: valueEast += value; break;
				default: break;
			}
		}

		void goForwardWayPoint(int value) {
			valueNorth += waypoint.north * value;
			valueEast += waypoint.east * value;
		}
		
		void changeWayPointDirection(String change, int value) {
			if (value < 1) {
				return;
			}
			if ("L".equals(change)) {
				int tmp = waypoint.north;
				waypoint.north = waypoint.east;
				waypoint.east = -tmp;
				
			}
			if ("R".equals(change)) {
				int tmp = waypoint.north;
				waypoint.north = -waypoint.east;
				waypoint.east = tmp;
			}
			changeWayPointDirection(change, value - 1);
				
		}

		
		void changeDirection(String change, int value) {
			if (value < 1) {
				return;
			}
			if ("L".equals(change)) {
				switch(facing) {
					case North: facing = Direction.West; break;
					case West: facing = Direction.South; break;
					case South: facing = Direction.East; break;
					case East: facing = Direction.North; break;
					default: break;
				}
			}
			if ("R".equals(change)) {
				switch(facing) {
					case North: facing = Direction.East; break;
					case West: facing = Direction.North; break;
					case South: facing = Direction.West; break;
					case East: facing = Direction.South; break;
					default: break;
				}
			}
			changeDirection(change, value - 1);
		}
		
		int getManhattanDistance() {
			return Math.abs(valueEast) + Math.abs(valueNorth);
		}
		
	}
	
	class WayPoint {
		int north;
		int east;
		WayPoint() {
			this.north = 1;
			this.east = 10;
		}
	}
	
	enum Direction {
		North,
		West,
		South,
		East
	}
}
