package my.project.advent.of.code.y2021;

import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.List;

import org.junit.Test;

import my.project.advent.of.code.commons.Command;
import my.project.advent.of.code.commons.Direction;
import my.project.advent.of.code.commons.Submarine;
import my.project.advent.of.code.commons.SubmarineComplex;

public class Day2 {
	
	static List<Command> inputTest1 = Arrays.asList(new Command(Direction.FORWARD, 5),new Command(Direction.DOWN, 5),new Command(Direction.FORWARD, 8),new Command(Direction.UP, 3),new Command(Direction.DOWN, 8),new Command(Direction.FORWARD, 2));
	static List<Command> inputPart1 = Arrays.asList(
			new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,5),new Command(Direction.DOWN,5),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,9),new Command(Direction.UP,6),new Command(Direction.UP,7),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,9),
			new Command(Direction.UP,4),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,9),new Command(Direction.UP,3),new Command(Direction.DOWN,1),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,3),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,7),new Command(Direction.UP,7),
			new Command(Direction.DOWN,9),new Command(Direction.DOWN,1),new Command(Direction.DOWN,4),new Command(Direction.DOWN,9),new Command(Direction.DOWN,2),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,4),new Command(Direction.UP,7),new Command(Direction.UP,1),new Command(Direction.FORWARD,3),
			new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,9),new Command(Direction.UP,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,2),
			new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,5),new Command(Direction.UP,8),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,4),new Command(Direction.UP,6),new Command(Direction.UP,9),new Command(Direction.FORWARD,2),new Command(Direction.UP,8),
			new Command(Direction.DOWN,1),new Command(Direction.UP,5),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,6),
			new Command(Direction.UP,6),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,9),new Command(Direction.DOWN,8),new Command(Direction.UP,9),new Command(Direction.DOWN,9),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,4),new Command(Direction.DOWN,2),new Command(Direction.DOWN,8),
			new Command(Direction.UP,3),new Command(Direction.UP,9),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,5),new Command(Direction.DOWN,1),
			new Command(Direction.UP,6),new Command(Direction.UP,6),new Command(Direction.DOWN,4),new Command(Direction.UP,3),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,5),
			new Command(Direction.DOWN,5),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,3),
			new Command(Direction.FORWARD,2),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,9),
			new Command(Direction.DOWN,3),new Command(Direction.UP,7),new Command(Direction.UP,6),new Command(Direction.DOWN,8),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,4),new Command(Direction.DOWN,8),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,5),new Command(Direction.UP,7),
			new Command(Direction.DOWN,8),new Command(Direction.DOWN,4),new Command(Direction.DOWN,5),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,1),
			new Command(Direction.UP,1),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,5),
			new Command(Direction.UP,4),new Command(Direction.DOWN,3),new Command(Direction.UP,7),new Command(Direction.UP,2),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,2),new Command(Direction.FORWARD,8),new Command(Direction.UP,1),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,2),
			new Command(Direction.FORWARD,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,9),
			new Command(Direction.UP,3),new Command(Direction.UP,7),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,4),new Command(Direction.UP,6),
			new Command(Direction.FORWARD,2),new Command(Direction.DOWN,2),new Command(Direction.DOWN,4),new Command(Direction.DOWN,4),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,5),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,8),new Command(Direction.DOWN,1),new Command(Direction.UP,6),
			new Command(Direction.UP,1),new Command(Direction.UP,4),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,4),
			new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,9),new Command(Direction.UP,9),new Command(Direction.DOWN,9),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,7),new Command(Direction.UP,6),new Command(Direction.UP,2),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,3),new Command(Direction.DOWN,8),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,9),
			new Command(Direction.UP,3),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,5),
			new Command(Direction.DOWN,5),new Command(Direction.DOWN,1),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,3),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,4),
			new Command(Direction.UP,3),new Command(Direction.UP,7),new Command(Direction.UP,4),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,9),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,3),new Command(Direction.UP,5),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,7),new Command(Direction.UP,2),new Command(Direction.DOWN,8),
			new Command(Direction.UP,2),new Command(Direction.UP,2),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,3),
			new Command(Direction.DOWN,3),new Command(Direction.UP,8),new Command(Direction.FORWARD,7),new Command(Direction.UP,5),new Command(Direction.FORWARD,4),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,3),new Command(Direction.UP,9),
			new Command(Direction.UP,2),new Command(Direction.DOWN,2),new Command(Direction.DOWN,5),new Command(Direction.DOWN,8),new Command(Direction.DOWN,1),
			new Command(Direction.FORWARD,9),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,9),new Command(Direction.DOWN,4),
			new Command(Direction.UP,6),new Command(Direction.UP,3),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,8),new Command(Direction.UP,3),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,7),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,6),
			new Command(Direction.FORWARD,8),new Command(Direction.UP,7),new Command(Direction.DOWN,5),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,4),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,2),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,3),new Command(Direction.DOWN,5),new Command(Direction.DOWN,3),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,4),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,5),new Command(Direction.UP,7),
			new Command(Direction.UP,3),new Command(Direction.FORWARD,9),new Command(Direction.UP,1),new Command(Direction.FORWARD,9),new Command(Direction.UP,8),
			new Command(Direction.DOWN,3),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,1),
			new Command(Direction.UP,9),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,3),new Command(Direction.UP,4),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,6),
			new Command(Direction.FORWARD,5),new Command(Direction.UP,2),new Command(Direction.DOWN,5),new Command(Direction.UP,7),new Command(Direction.UP,4),
			new Command(Direction.UP,5),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,9),new Command(Direction.UP,4),new Command(Direction.FORWARD,9),
			new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,5),new Command(Direction.DOWN,4),new Command(Direction.DOWN,2),
			new Command(Direction.UP,5),new Command(Direction.UP,7),new Command(Direction.UP,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,9),
			new Command(Direction.DOWN,9),new Command(Direction.DOWN,4),new Command(Direction.UP,2),new Command(Direction.FORWARD,3),new Command(Direction.UP,3),
			new Command(Direction.UP,2),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,6),
			new Command(Direction.FORWARD,3),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,5),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,7),new Command(Direction.UP,6),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,7),
			new Command(Direction.DOWN,3),new Command(Direction.UP,3),new Command(Direction.UP,8),new Command(Direction.FORWARD,3),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,3),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,9),new Command(Direction.UP,8),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,3),new Command(Direction.DOWN,7),new Command(Direction.DOWN,4),new Command(Direction.DOWN,1),new Command(Direction.DOWN,7),
			new Command(Direction.UP,6),new Command(Direction.FORWARD,8),new Command(Direction.UP,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,6),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,6),new Command(Direction.UP,9),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,5),
			new Command(Direction.UP,3),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,8),new Command(Direction.UP,9),
			new Command(Direction.FORWARD,4),new Command(Direction.UP,5),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,8),
			new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,4),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,2),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,9),
			new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,3),
			new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,5),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,8),
			new Command(Direction.UP,9),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,9),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,8),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,6),new Command(Direction.UP,5),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,9),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,7),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,5),new Command(Direction.DOWN,8),new Command(Direction.UP,5),new Command(Direction.DOWN,6),
			new Command(Direction.UP,5),new Command(Direction.UP,7),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,6),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,4),new Command(Direction.DOWN,5),new Command(Direction.UP,4),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,4),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,1),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,6),
			new Command(Direction.UP,5),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,9),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,7),
			new Command(Direction.UP,9),new Command(Direction.DOWN,2),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,3),new Command(Direction.UP,5),
			new Command(Direction.DOWN,8),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,5),
			new Command(Direction.UP,6),new Command(Direction.FORWARD,2),new Command(Direction.UP,5),new Command(Direction.FORWARD,8),new Command(Direction.UP,6),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,1),new Command(Direction.UP,7),new Command(Direction.FORWARD,2),new Command(Direction.UP,5),new Command(Direction.FORWARD,4),
			new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,3),
			new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.UP,9),new Command(Direction.UP,2),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,5),new Command(Direction.UP,9),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,7),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,2),new Command(Direction.DOWN,1),new Command(Direction.DOWN,7),new Command(Direction.DOWN,6),
			new Command(Direction.UP,1),new Command(Direction.UP,4),new Command(Direction.DOWN,9),new Command(Direction.UP,3),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,2),new Command(Direction.FORWARD,4),new Command(Direction.UP,4),new Command(Direction.UP,9),new Command(Direction.DOWN,4),
			new Command(Direction.FORWARD,6),new Command(Direction.DOWN,1),new Command(Direction.DOWN,1),new Command(Direction.DOWN,8),new Command(Direction.UP,5),
			new Command(Direction.FORWARD,1),new Command(Direction.UP,6),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,4),new Command(Direction.UP,8),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,7),new Command(Direction.DOWN,1),
			new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,1),new Command(Direction.UP,6),new Command(Direction.DOWN,1),new Command(Direction.DOWN,8),
			new Command(Direction.FORWARD,6),new Command(Direction.DOWN,4),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,3),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,6),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,9),new Command(Direction.UP,9),new Command(Direction.FORWARD,5),new Command(Direction.UP,9),new Command(Direction.UP,4),
			new Command(Direction.UP,6),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,3),new Command(Direction.UP,2),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,8),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,4),new Command(Direction.DOWN,3),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,1),new Command(Direction.FORWARD,5),new Command(Direction.UP,4),new Command(Direction.DOWN,3),new Command(Direction.DOWN,3),
			new Command(Direction.DOWN,6),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,9),
			new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,1),new Command(Direction.UP,5),new Command(Direction.DOWN,6),
			new Command(Direction.FORWARD,5),new Command(Direction.UP,5),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,8),new Command(Direction.DOWN,1),
			new Command(Direction.DOWN,8),new Command(Direction.UP,1),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,3),
			new Command(Direction.UP,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,2),new Command(Direction.UP,4),new Command(Direction.UP,3),new Command(Direction.DOWN,2),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,3),
			new Command(Direction.UP,9),new Command(Direction.UP,6),new Command(Direction.DOWN,9),new Command(Direction.DOWN,1),new Command(Direction.UP,3),
			new Command(Direction.UP,2),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,6),new Command(Direction.UP,2),new Command(Direction.UP,1),
			new Command(Direction.DOWN,9),new Command(Direction.DOWN,3),new Command(Direction.DOWN,6),new Command(Direction.UP,7),new Command(Direction.UP,5),
			new Command(Direction.FORWARD,8),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,6),new Command(Direction.DOWN,1),
			new Command(Direction.UP,9),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,3),new Command(Direction.DOWN,9),
			new Command(Direction.DOWN,5),new Command(Direction.FORWARD,7),new Command(Direction.UP,1),new Command(Direction.UP,4),new Command(Direction.UP,4),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,1),new Command(Direction.UP,2),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,8),
			new Command(Direction.FORWARD,7),new Command(Direction.UP,8),new Command(Direction.DOWN,1),new Command(Direction.DOWN,8),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,8),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,5),
			new Command(Direction.DOWN,8),new Command(Direction.DOWN,7),new Command(Direction.UP,5),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,5),
			new Command(Direction.UP,9),new Command(Direction.DOWN,5),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,6),
			new Command(Direction.FORWARD,2),new Command(Direction.UP,1),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,7),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,6),new Command(Direction.UP,5),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,7),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,1),
			new Command(Direction.UP,7),new Command(Direction.FORWARD,3),new Command(Direction.UP,3),new Command(Direction.FORWARD,6),new Command(Direction.UP,3),
			new Command(Direction.DOWN,9),new Command(Direction.FORWARD,9),new Command(Direction.UP,6),new Command(Direction.UP,3),new Command(Direction.FORWARD,2),
			new Command(Direction.DOWN,2),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,7),new Command(Direction.UP,7),new Command(Direction.FORWARD,6),
			new Command(Direction.FORWARD,2),new Command(Direction.DOWN,2),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,4),
			new Command(Direction.DOWN,4),new Command(Direction.UP,9),new Command(Direction.DOWN,4),new Command(Direction.DOWN,4),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,7),
			new Command(Direction.UP,4),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,5),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,2),new Command(Direction.UP,8),new Command(Direction.DOWN,7),new Command(Direction.UP,7),
			new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,7),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,6),new Command(Direction.UP,7),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,2),new Command(Direction.UP,9),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,9),
			new Command(Direction.UP,8),new Command(Direction.DOWN,1),new Command(Direction.UP,8),new Command(Direction.UP,2),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,5),new Command(Direction.UP,7),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,7),new Command(Direction.DOWN,6),new Command(Direction.DOWN,2),new Command(Direction.UP,3),new Command(Direction.UP,7),
			new Command(Direction.UP,5),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,1),new Command(Direction.DOWN,5),
			new Command(Direction.UP,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.UP,6),
			new Command(Direction.DOWN,1),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,4),
			new Command(Direction.FORWARD,8),new Command(Direction.UP,2),new Command(Direction.DOWN,8),new Command(Direction.UP,4),new Command(Direction.UP,9),
			new Command(Direction.FORWARD,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,4),new Command(Direction.UP,3),new Command(Direction.UP,1),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,6),
			new Command(Direction.UP,4),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,2),
			new Command(Direction.DOWN,8),new Command(Direction.FORWARD,9),new Command(Direction.UP,7),new Command(Direction.FORWARD,2),new Command(Direction.UP,1),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,9),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,9),new Command(Direction.DOWN,5),new Command(Direction.UP,2),
			new Command(Direction.DOWN,6),new Command(Direction.FORWARD,8),new Command(Direction.UP,6),new Command(Direction.DOWN,3),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,1),new Command(Direction.UP,7),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,8),new Command(Direction.UP,4),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,4),new Command(Direction.DOWN,4),new Command(Direction.DOWN,2),new Command(Direction.DOWN,3),
			new Command(Direction.DOWN,1),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,4),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,9),new Command(Direction.UP,1),new Command(Direction.UP,7),new Command(Direction.FORWARD,4),
			new Command(Direction.UP,7),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,8),
			new Command(Direction.UP,8),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,9),
			new Command(Direction.FORWARD,6),new Command(Direction.UP,3),new Command(Direction.DOWN,4),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,6),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,5),
			new Command(Direction.UP,3),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,2),new Command(Direction.DOWN,9),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,7),
			new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,3),
			new Command(Direction.DOWN,1),new Command(Direction.DOWN,1),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,8),new Command(Direction.UP,3),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,8),
			new Command(Direction.UP,6),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,3),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,9),
			new Command(Direction.UP,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,3),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,1),new Command(Direction.UP,4),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,7),new Command(Direction.UP,3),
			new Command(Direction.DOWN,3),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,9),
			new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,5),
			new Command(Direction.UP,7),new Command(Direction.DOWN,9),new Command(Direction.DOWN,2),new Command(Direction.UP,4),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,1),new Command(Direction.DOWN,2),new Command(Direction.DOWN,5),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,6),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,7),
			new Command(Direction.UP,9),new Command(Direction.UP,2),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,9),new Command(Direction.UP,5),
			new Command(Direction.FORWARD,2),new Command(Direction.UP,5),new Command(Direction.UP,9),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,8),
			new Command(Direction.FORWARD,6),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,1),new Command(Direction.DOWN,4),
			new Command(Direction.FORWARD,4),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,9),
			new Command(Direction.DOWN,5),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),
			new Command(Direction.DOWN,2),new Command(Direction.FORWARD,5),new Command(Direction.UP,2),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,1),new Command(Direction.DOWN,9),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,5),new Command(Direction.UP,5),new Command(Direction.FORWARD,8),new Command(Direction.UP,4),new Command(Direction.DOWN,6),
			new Command(Direction.FORWARD,1),new Command(Direction.UP,2),new Command(Direction.DOWN,3),new Command(Direction.DOWN,1),new Command(Direction.DOWN,8),
			new Command(Direction.DOWN,2),new Command(Direction.UP,6),new Command(Direction.DOWN,5),new Command(Direction.DOWN,2),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,2),new Command(Direction.UP,7),new Command(Direction.DOWN,9),new Command(Direction.UP,1),new Command(Direction.UP,1),
			new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,7),new Command(Direction.UP,7),new Command(Direction.DOWN,7),
			new Command(Direction.FORWARD,5),new Command(Direction.UP,2),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,7),
			new Command(Direction.UP,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,1),new Command(Direction.UP,6),new Command(Direction.DOWN,8),
			new Command(Direction.UP,6),new Command(Direction.DOWN,2),new Command(Direction.DOWN,4),new Command(Direction.UP,8),new Command(Direction.UP,8),
			new Command(Direction.UP,5),new Command(Direction.DOWN,6),new Command(Direction.UP,6),new Command(Direction.DOWN,5),new Command(Direction.UP,1),
			new Command(Direction.DOWN,1),new Command(Direction.FORWARD,6),new Command(Direction.UP,7),new Command(Direction.FORWARD,8),new Command(Direction.UP,9),
			new Command(Direction.DOWN,8),new Command(Direction.UP,7),new Command(Direction.FORWARD,9),new Command(Direction.UP,4),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,7),
			new Command(Direction.FORWARD,9),new Command(Direction.DOWN,6),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,3));
	
	static List<Command> inputTest2 = Arrays.asList(new Command(Direction.FORWARD, 5),new Command(Direction.DOWN, 5),new Command(Direction.FORWARD, 8),new Command(Direction.UP, 3),new Command(Direction.DOWN, 8),new Command(Direction.FORWARD, 2));
	static List<Command> inputPart2 = Arrays.asList(
			new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,5),new Command(Direction.DOWN,5),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,9),new Command(Direction.UP,6),new Command(Direction.UP,7),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,9),
			new Command(Direction.UP,4),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,9),new Command(Direction.UP,3),new Command(Direction.DOWN,1),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,3),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,7),new Command(Direction.UP,7),
			new Command(Direction.DOWN,9),new Command(Direction.DOWN,1),new Command(Direction.DOWN,4),new Command(Direction.DOWN,9),new Command(Direction.DOWN,2),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,4),new Command(Direction.UP,7),new Command(Direction.UP,1),new Command(Direction.FORWARD,3),
			new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,9),new Command(Direction.UP,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,2),
			new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,5),new Command(Direction.UP,8),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,4),new Command(Direction.UP,6),new Command(Direction.UP,9),new Command(Direction.FORWARD,2),new Command(Direction.UP,8),
			new Command(Direction.DOWN,1),new Command(Direction.UP,5),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,6),
			new Command(Direction.UP,6),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,9),new Command(Direction.DOWN,8),new Command(Direction.UP,9),new Command(Direction.DOWN,9),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,4),new Command(Direction.DOWN,2),new Command(Direction.DOWN,8),
			new Command(Direction.UP,3),new Command(Direction.UP,9),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,5),new Command(Direction.DOWN,1),
			new Command(Direction.UP,6),new Command(Direction.UP,6),new Command(Direction.DOWN,4),new Command(Direction.UP,3),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,5),
			new Command(Direction.DOWN,5),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,3),
			new Command(Direction.FORWARD,2),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,9),
			new Command(Direction.DOWN,3),new Command(Direction.UP,7),new Command(Direction.UP,6),new Command(Direction.DOWN,8),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,4),new Command(Direction.DOWN,8),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,5),new Command(Direction.UP,7),
			new Command(Direction.DOWN,8),new Command(Direction.DOWN,4),new Command(Direction.DOWN,5),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,1),
			new Command(Direction.UP,1),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,5),
			new Command(Direction.UP,4),new Command(Direction.DOWN,3),new Command(Direction.UP,7),new Command(Direction.UP,2),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,2),new Command(Direction.FORWARD,8),new Command(Direction.UP,1),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,2),
			new Command(Direction.FORWARD,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,9),
			new Command(Direction.UP,3),new Command(Direction.UP,7),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,4),new Command(Direction.UP,6),
			new Command(Direction.FORWARD,2),new Command(Direction.DOWN,2),new Command(Direction.DOWN,4),new Command(Direction.DOWN,4),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,5),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,8),new Command(Direction.DOWN,1),new Command(Direction.UP,6),
			new Command(Direction.UP,1),new Command(Direction.UP,4),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,4),
			new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,9),new Command(Direction.UP,9),new Command(Direction.DOWN,9),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,7),new Command(Direction.UP,6),new Command(Direction.UP,2),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,3),new Command(Direction.DOWN,8),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,9),
			new Command(Direction.UP,3),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,5),
			new Command(Direction.DOWN,5),new Command(Direction.DOWN,1),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,3),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,4),
			new Command(Direction.UP,3),new Command(Direction.UP,7),new Command(Direction.UP,4),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,9),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,3),new Command(Direction.UP,5),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,7),new Command(Direction.UP,2),new Command(Direction.DOWN,8),
			new Command(Direction.UP,2),new Command(Direction.UP,2),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,3),
			new Command(Direction.DOWN,3),new Command(Direction.UP,8),new Command(Direction.FORWARD,7),new Command(Direction.UP,5),new Command(Direction.FORWARD,4),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,3),new Command(Direction.UP,9),
			new Command(Direction.UP,2),new Command(Direction.DOWN,2),new Command(Direction.DOWN,5),new Command(Direction.DOWN,8),new Command(Direction.DOWN,1),
			new Command(Direction.FORWARD,9),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,9),new Command(Direction.DOWN,4),
			new Command(Direction.UP,6),new Command(Direction.UP,3),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,8),new Command(Direction.UP,3),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,7),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,6),
			new Command(Direction.FORWARD,8),new Command(Direction.UP,7),new Command(Direction.DOWN,5),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,4),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,2),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,3),new Command(Direction.DOWN,5),new Command(Direction.DOWN,3),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,4),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,5),new Command(Direction.UP,7),
			new Command(Direction.UP,3),new Command(Direction.FORWARD,9),new Command(Direction.UP,1),new Command(Direction.FORWARD,9),new Command(Direction.UP,8),
			new Command(Direction.DOWN,3),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,1),
			new Command(Direction.UP,9),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,3),new Command(Direction.UP,4),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,6),
			new Command(Direction.FORWARD,5),new Command(Direction.UP,2),new Command(Direction.DOWN,5),new Command(Direction.UP,7),new Command(Direction.UP,4),
			new Command(Direction.UP,5),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,9),new Command(Direction.UP,4),new Command(Direction.FORWARD,9),
			new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,5),new Command(Direction.DOWN,4),new Command(Direction.DOWN,2),
			new Command(Direction.UP,5),new Command(Direction.UP,7),new Command(Direction.UP,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,9),
			new Command(Direction.DOWN,9),new Command(Direction.DOWN,4),new Command(Direction.UP,2),new Command(Direction.FORWARD,3),new Command(Direction.UP,3),
			new Command(Direction.UP,2),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,6),
			new Command(Direction.FORWARD,3),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,5),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,7),new Command(Direction.UP,6),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,7),
			new Command(Direction.DOWN,3),new Command(Direction.UP,3),new Command(Direction.UP,8),new Command(Direction.FORWARD,3),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,3),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,9),new Command(Direction.UP,8),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,3),new Command(Direction.DOWN,7),new Command(Direction.DOWN,4),new Command(Direction.DOWN,1),new Command(Direction.DOWN,7),
			new Command(Direction.UP,6),new Command(Direction.FORWARD,8),new Command(Direction.UP,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,6),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,6),new Command(Direction.UP,9),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,5),
			new Command(Direction.UP,3),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,8),new Command(Direction.UP,9),
			new Command(Direction.FORWARD,4),new Command(Direction.UP,5),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,8),
			new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,4),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,2),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,9),
			new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,3),
			new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,5),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,8),
			new Command(Direction.UP,9),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,9),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,8),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,6),new Command(Direction.UP,5),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,9),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,7),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,5),new Command(Direction.DOWN,8),new Command(Direction.UP,5),new Command(Direction.DOWN,6),
			new Command(Direction.UP,5),new Command(Direction.UP,7),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,6),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,4),new Command(Direction.DOWN,5),new Command(Direction.UP,4),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,4),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,1),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,6),
			new Command(Direction.UP,5),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,9),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,7),
			new Command(Direction.UP,9),new Command(Direction.DOWN,2),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,3),new Command(Direction.UP,5),
			new Command(Direction.DOWN,8),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,5),
			new Command(Direction.UP,6),new Command(Direction.FORWARD,2),new Command(Direction.UP,5),new Command(Direction.FORWARD,8),new Command(Direction.UP,6),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,1),new Command(Direction.UP,7),new Command(Direction.FORWARD,2),new Command(Direction.UP,5),new Command(Direction.FORWARD,4),
			new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,3),
			new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.UP,9),new Command(Direction.UP,2),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,5),new Command(Direction.UP,9),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,7),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,2),new Command(Direction.DOWN,1),new Command(Direction.DOWN,7),new Command(Direction.DOWN,6),
			new Command(Direction.UP,1),new Command(Direction.UP,4),new Command(Direction.DOWN,9),new Command(Direction.UP,3),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,2),new Command(Direction.FORWARD,4),new Command(Direction.UP,4),new Command(Direction.UP,9),new Command(Direction.DOWN,4),
			new Command(Direction.FORWARD,6),new Command(Direction.DOWN,1),new Command(Direction.DOWN,1),new Command(Direction.DOWN,8),new Command(Direction.UP,5),
			new Command(Direction.FORWARD,1),new Command(Direction.UP,6),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,4),new Command(Direction.UP,8),
			new Command(Direction.DOWN,4),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,7),new Command(Direction.DOWN,1),
			new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,1),new Command(Direction.UP,6),new Command(Direction.DOWN,1),new Command(Direction.DOWN,8),
			new Command(Direction.FORWARD,6),new Command(Direction.DOWN,4),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,3),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,6),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,9),new Command(Direction.UP,9),new Command(Direction.FORWARD,5),new Command(Direction.UP,9),new Command(Direction.UP,4),
			new Command(Direction.UP,6),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,3),new Command(Direction.UP,2),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,8),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,4),new Command(Direction.DOWN,3),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,1),new Command(Direction.FORWARD,5),new Command(Direction.UP,4),new Command(Direction.DOWN,3),new Command(Direction.DOWN,3),
			new Command(Direction.DOWN,6),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,9),
			new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,1),new Command(Direction.UP,5),new Command(Direction.DOWN,6),
			new Command(Direction.FORWARD,5),new Command(Direction.UP,5),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,8),new Command(Direction.DOWN,1),
			new Command(Direction.DOWN,8),new Command(Direction.UP,1),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,3),
			new Command(Direction.UP,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,2),new Command(Direction.UP,4),new Command(Direction.UP,3),new Command(Direction.DOWN,2),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,3),
			new Command(Direction.UP,9),new Command(Direction.UP,6),new Command(Direction.DOWN,9),new Command(Direction.DOWN,1),new Command(Direction.UP,3),
			new Command(Direction.UP,2),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,6),new Command(Direction.UP,2),new Command(Direction.UP,1),
			new Command(Direction.DOWN,9),new Command(Direction.DOWN,3),new Command(Direction.DOWN,6),new Command(Direction.UP,7),new Command(Direction.UP,5),
			new Command(Direction.FORWARD,8),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,6),new Command(Direction.DOWN,1),
			new Command(Direction.UP,9),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,3),new Command(Direction.DOWN,9),
			new Command(Direction.DOWN,5),new Command(Direction.FORWARD,7),new Command(Direction.UP,1),new Command(Direction.UP,4),new Command(Direction.UP,4),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,1),new Command(Direction.UP,2),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,8),
			new Command(Direction.FORWARD,7),new Command(Direction.UP,8),new Command(Direction.DOWN,1),new Command(Direction.DOWN,8),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,1),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,8),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,5),
			new Command(Direction.DOWN,8),new Command(Direction.DOWN,7),new Command(Direction.UP,5),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,5),
			new Command(Direction.UP,9),new Command(Direction.DOWN,5),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,6),
			new Command(Direction.FORWARD,2),new Command(Direction.UP,1),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,7),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,6),new Command(Direction.UP,5),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,7),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,1),
			new Command(Direction.UP,7),new Command(Direction.FORWARD,3),new Command(Direction.UP,3),new Command(Direction.FORWARD,6),new Command(Direction.UP,3),
			new Command(Direction.DOWN,9),new Command(Direction.FORWARD,9),new Command(Direction.UP,6),new Command(Direction.UP,3),new Command(Direction.FORWARD,2),
			new Command(Direction.DOWN,2),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,7),new Command(Direction.UP,7),new Command(Direction.FORWARD,6),
			new Command(Direction.FORWARD,2),new Command(Direction.DOWN,2),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,4),
			new Command(Direction.DOWN,4),new Command(Direction.UP,9),new Command(Direction.DOWN,4),new Command(Direction.DOWN,4),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,7),
			new Command(Direction.UP,4),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,5),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,2),new Command(Direction.UP,8),new Command(Direction.DOWN,7),new Command(Direction.UP,7),
			new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,7),
			new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,6),new Command(Direction.UP,7),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,2),new Command(Direction.UP,9),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,9),
			new Command(Direction.UP,8),new Command(Direction.DOWN,1),new Command(Direction.UP,8),new Command(Direction.UP,2),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,6),new Command(Direction.DOWN,5),new Command(Direction.UP,7),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,7),new Command(Direction.DOWN,6),new Command(Direction.DOWN,2),new Command(Direction.UP,3),new Command(Direction.UP,7),
			new Command(Direction.UP,5),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,1),new Command(Direction.DOWN,5),
			new Command(Direction.UP,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,1),new Command(Direction.UP,6),
			new Command(Direction.DOWN,1),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,4),
			new Command(Direction.FORWARD,8),new Command(Direction.UP,2),new Command(Direction.DOWN,8),new Command(Direction.UP,4),new Command(Direction.UP,9),
			new Command(Direction.FORWARD,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,4),new Command(Direction.UP,3),new Command(Direction.UP,1),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,6),
			new Command(Direction.UP,4),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,2),
			new Command(Direction.DOWN,8),new Command(Direction.FORWARD,9),new Command(Direction.UP,7),new Command(Direction.FORWARD,2),new Command(Direction.UP,1),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,9),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,9),new Command(Direction.DOWN,5),new Command(Direction.UP,2),
			new Command(Direction.DOWN,6),new Command(Direction.FORWARD,8),new Command(Direction.UP,6),new Command(Direction.DOWN,3),new Command(Direction.DOWN,5),
			new Command(Direction.DOWN,1),new Command(Direction.UP,7),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,8),new Command(Direction.UP,4),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,4),new Command(Direction.DOWN,4),new Command(Direction.DOWN,2),new Command(Direction.DOWN,3),
			new Command(Direction.DOWN,1),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,4),new Command(Direction.DOWN,7),
			new Command(Direction.DOWN,7),new Command(Direction.DOWN,9),new Command(Direction.UP,1),new Command(Direction.UP,7),new Command(Direction.FORWARD,4),
			new Command(Direction.UP,7),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,8),
			new Command(Direction.UP,8),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,7),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,9),
			new Command(Direction.FORWARD,6),new Command(Direction.UP,3),new Command(Direction.DOWN,4),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,6),
			new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,3),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,5),
			new Command(Direction.UP,3),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,2),new Command(Direction.DOWN,9),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,7),
			new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,5),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,3),
			new Command(Direction.DOWN,1),new Command(Direction.DOWN,1),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,8),new Command(Direction.UP,3),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,8),
			new Command(Direction.UP,6),new Command(Direction.FORWARD,2),new Command(Direction.DOWN,3),new Command(Direction.DOWN,4),new Command(Direction.FORWARD,9),
			new Command(Direction.UP,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,5),new Command(Direction.DOWN,3),new Command(Direction.UP,7),
			new Command(Direction.FORWARD,5),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,6),
			new Command(Direction.DOWN,1),new Command(Direction.UP,4),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,7),new Command(Direction.UP,3),
			new Command(Direction.DOWN,3),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,1),new Command(Direction.FORWARD,9),
			new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,1),new Command(Direction.FORWARD,6),new Command(Direction.DOWN,5),
			new Command(Direction.UP,7),new Command(Direction.DOWN,9),new Command(Direction.DOWN,2),new Command(Direction.UP,4),new Command(Direction.DOWN,2),
			new Command(Direction.DOWN,2),new Command(Direction.DOWN,1),new Command(Direction.DOWN,2),new Command(Direction.DOWN,5),new Command(Direction.DOWN,4),
			new Command(Direction.DOWN,6),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,7),
			new Command(Direction.UP,9),new Command(Direction.UP,2),new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,9),new Command(Direction.UP,5),
			new Command(Direction.FORWARD,2),new Command(Direction.UP,5),new Command(Direction.UP,9),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,8),
			new Command(Direction.FORWARD,6),new Command(Direction.DOWN,8),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,1),new Command(Direction.DOWN,4),
			new Command(Direction.FORWARD,4),new Command(Direction.DOWN,3),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,9),
			new Command(Direction.DOWN,5),new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),
			new Command(Direction.DOWN,2),new Command(Direction.FORWARD,5),new Command(Direction.UP,2),new Command(Direction.FORWARD,1),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,8),new Command(Direction.DOWN,9),new Command(Direction.FORWARD,5),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,1),new Command(Direction.DOWN,9),new Command(Direction.DOWN,6),new Command(Direction.FORWARD,8),new Command(Direction.FORWARD,1),
			new Command(Direction.DOWN,5),new Command(Direction.UP,5),new Command(Direction.FORWARD,8),new Command(Direction.UP,4),new Command(Direction.DOWN,6),
			new Command(Direction.FORWARD,1),new Command(Direction.UP,2),new Command(Direction.DOWN,3),new Command(Direction.DOWN,1),new Command(Direction.DOWN,8),
			new Command(Direction.DOWN,2),new Command(Direction.UP,6),new Command(Direction.DOWN,5),new Command(Direction.DOWN,2),new Command(Direction.DOWN,3),
			new Command(Direction.FORWARD,2),new Command(Direction.UP,7),new Command(Direction.DOWN,9),new Command(Direction.UP,1),new Command(Direction.UP,1),
			new Command(Direction.FORWARD,7),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,7),new Command(Direction.UP,7),new Command(Direction.DOWN,7),
			new Command(Direction.FORWARD,5),new Command(Direction.UP,2),new Command(Direction.DOWN,7),new Command(Direction.FORWARD,9),new Command(Direction.DOWN,7),
			new Command(Direction.UP,4),new Command(Direction.FORWARD,2),new Command(Direction.FORWARD,1),new Command(Direction.UP,6),new Command(Direction.DOWN,8),
			new Command(Direction.UP,6),new Command(Direction.DOWN,2),new Command(Direction.DOWN,4),new Command(Direction.UP,8),new Command(Direction.UP,8),
			new Command(Direction.UP,5),new Command(Direction.DOWN,6),new Command(Direction.UP,6),new Command(Direction.DOWN,5),new Command(Direction.UP,1),
			new Command(Direction.DOWN,1),new Command(Direction.FORWARD,6),new Command(Direction.UP,7),new Command(Direction.FORWARD,8),new Command(Direction.UP,9),
			new Command(Direction.DOWN,8),new Command(Direction.UP,7),new Command(Direction.FORWARD,9),new Command(Direction.UP,4),new Command(Direction.DOWN,5),
			new Command(Direction.FORWARD,3),new Command(Direction.FORWARD,6),new Command(Direction.FORWARD,4),new Command(Direction.FORWARD,4),new Command(Direction.DOWN,7),
			new Command(Direction.FORWARD,9),new Command(Direction.DOWN,6),new Command(Direction.DOWN,2),new Command(Direction.FORWARD,9),new Command(Direction.FORWARD,3));
	
	@Test
	public void test() {
		assertsPartOne();
		assertsPartTwo();
	}

	/**
	 * Part <b>ONE</b>
	 */
	private static void assertsPartOne() {
		assertEquals(150, getMultiplyFinalPositions(inputTest1));
		assertEquals(1604850, getMultiplyFinalPositions(inputPart1));
	}
	


	/**
	 * Part <b>TWO</b>
	 */
	private static void assertsPartTwo() {
		assertEquals(900, getMultiplyFinalPositionsComplex(inputTest2));
		assertEquals(1685186100, getMultiplyFinalPositionsComplex(inputPart2));
	}

	private static int getMultiplyFinalPositions(List<Command> commands) {
		Submarine submarine = new Submarine();
		for (Command command : commands) {
			submarine.doCommand(command);
		}
		return submarine.depthPosition * submarine.horizontalPosition;
	}
	private static int getMultiplyFinalPositionsComplex(List<Command> commands) {
		SubmarineComplex submarine = new SubmarineComplex();
		for (Command command : commands) {
			submarine.doCommand(command);
		}
		return submarine.depthPosition * submarine.horizontalPosition;
	}

	

}
