package y2020;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;

import org.junit.Test;

import com.google.common.base.Predicate;
import com.google.common.collect.Iterables;

public class Day7 {

	@Test
	public void test() {
		List<BagRule> input = Arrays.asList(
				new BagRule("clear purple bag",new Stock(5,"faded indigo bag"),new Stock(3,"muted purple bag")),
				new BagRule("bright teal bag",new Stock(4,"striped plum bag")),
				new BagRule("dim fuchsia bag",new Stock(2,"vibrant tomato bag"),new Stock(2,"dotted purple bag"),new Stock(2,"plaid indigo bag")),
				new BagRule("dark magenta bag",new Stock(1,"shiny aqua bag"),new Stock(2,"posh white bag")),
				new BagRule("dark chartreuse bag",new Stock(1,"dotted brown bag"),new Stock(4,"vibrant magenta bag")),
				new BagRule("wavy crimson bag",new Stock(5,"pale coral bag")),
				new BagRule("drab cyan bag",new Stock(1,"light green bag"),new Stock(2,"pale teal bag")),
				new BagRule("posh salmon bag",new Stock(5,"wavy maroon bag"),new Stock(5,"shiny coral bag")),
				new BagRule("light violet bag",new Stock(5,"faded teal bag"),new Stock(1,"light gray bag"),new Stock(4,"bright turquoise bag"),new Stock(5,"posh crimson bag")),
				new BagRule("dark turquoise bag",new Stock(1,"clear yellow bag"),new Stock(1,"wavy maroon bag"),new Stock(3,"muted brown bag")),
				new BagRule("bright coral bag",new Stock(5,"mirrored silver bag"),new Stock(4,"light teal bag")),
				new BagRule("dotted lavender bag",new Stock(1,"clear indigo bag")),
				new BagRule("striped white bag",new Stock(5,"dull beige bag")),
				new BagRule("dotted lime bag",new Stock(5,"mirrored magenta bag"),new Stock(4,"faded red bag")),
				new BagRule("dark tan bag",new Stock(5,"bright coral bag"),new Stock(5,"wavy salmon bag"),new Stock(4,"posh green bag")),
				new BagRule("dull black bag",new Stock(2,"shiny brown bag"),new Stock(3,"plaid bronze bag"),new Stock(3,"wavy teal bag"),new Stock(3,"dull chartreuse bag")),
				new BagRule("wavy coral bag",new Stock(5,"clear maroon bag"),new Stock(3,"dotted tan bag")),
				new BagRule("dotted yellow bag",new Stock(1,"shiny green bag"),new Stock(1,"mirrored tomato bag"),new Stock(5,"light bronze bag")),
				new BagRule("striped tan bag",new Stock(3,"pale lime bag")),
				new BagRule("striped aqua bag",new Stock(5,"pale magenta bag"),new Stock(4,"drab magenta bag"),new Stock(2,"dotted violet bag")),
				new BagRule("drab crimson bag",new Stock(4,"posh aqua bag"),new Stock(4,"dim gray bag")),
				new BagRule("bright indigo bag",new Stock(5,"striped violet bag"),new Stock(1,"muted orange bag")),
				new BagRule("striped yellow bag",new Stock(3,"mirrored orange bag"),new Stock(3,"clear black bag"),new Stock(1,"pale magenta bag")),
				new BagRule("dim teal bag",new Stock(1,"drab gold bag")),
				new BagRule("light green bag",new Stock(4,"drab magenta bag"),new Stock(3,"dark orange bag")),
				new BagRule("posh white bag",new Stock(1,"clear teal bag"),new Stock(3,"shiny cyan bag")),
				new BagRule("wavy fuchsia bag",new Stock(5,"vibrant magenta bag"),new Stock(2,"dull maroon bag"),new Stock(4,"faded lime bag")),
				new BagRule("faded gold bag",new Stock(3,"shiny indigo bag"),new Stock(4,"light lime bag")),
				new BagRule("dotted violet bag",new Stock(4,"faded tomato bag"),new Stock(3,"shiny gold bag"),new Stock(4,"faded brown bag"),new Stock(2,"clear bronze bag")),
				new BagRule("posh olive bag",new Stock(2,"pale bronze bag")),
				new BagRule("mirrored salmon bag",new Stock(3,"dim crimson bag"),new Stock(5,"striped plum bag"),new Stock(5,"clear plum bag")),
				new BagRule("mirrored olive bag",new Stock(4,"bright orange bag"),new Stock(5,"dim silver bag"),new Stock(1,"wavy tan bag"),new Stock(5,"striped crimson bag")),
				new BagRule("shiny orange bag",new Stock(2,"dim lime bag"),new Stock(4,"plaid lavender bag"),new Stock(5,"dull indigo bag")),
				new BagRule("dark fuchsia bag",new Stock(4,"dull red bag"),new Stock(1,"dotted fuchsia bag")),
				new BagRule("wavy white bag",new Stock(5,"plaid tomato bag"),new Stock(5,"wavy indigo bag"),new Stock(5,"mirrored brown bag"),new Stock(3,"muted red bag")),
				new BagRule("plaid violet bag",new Stock(2,"faded beige bag"),new Stock(2,"muted gold bag"),new Stock(4,"posh brown bag")),
				new BagRule("light orange bag",new Stock(2,"light tomato bag"),new Stock(3,"clear plum bag")),
				new BagRule("shiny tan bag",new Stock(5,"plaid tan bag"),new Stock(2,"wavy red bag"),new Stock(1,"wavy green bag")),
				new BagRule("dim gold bag",new Stock(1,"dull orange bag")),
				new BagRule("dark gold bag",new Stock(1,"pale cyan bag"),new Stock(5,"dotted beige bag"),new Stock(3,"vibrant teal bag"),new Stock(1,"vibrant magenta bag")),
				new BagRule("striped tomato bag",new Stock(3,"faded white bag"),new Stock(4,"shiny beige bag"),new Stock(1,"bright violet bag"),new Stock(4,"plaid aqua bag")),
				new BagRule("shiny magenta bag",new Stock(5,"dark purple bag"),new Stock(1,"dotted green bag"),new Stock(2,"shiny tomato bag")),
				new BagRule("plaid tomato bag",new Stock(4,"bright coral bag"),new Stock(1,"clear teal bag")),
				new BagRule("pale turquoise bag",new Stock(3,"muted gold bag"),new Stock(3,"dark bronze bag"),new Stock(5,"dotted violet bag"),new Stock(5,"light tomato bag")),
				new BagRule("shiny silver bag",new Stock(5,"pale purple bag"),new Stock(1,"muted maroon bag")),
				new BagRule("drab brown bag",new Stock(3,"dotted yellow bag"),new Stock(3,"wavy maroon bag"),new Stock(3,"striped gold bag"),new Stock(1,"faded aqua bag")),
				new BagRule("striped olive bag",new Stock(5,"bright crimson bag"),new Stock(5,"dim olive bag"),new Stock(2,"pale coral bag"),new Stock(2,"dull orange bag")),
				new BagRule("plaid gray bag",new Stock(2,"dim yellow bag"),new Stock(5,"faded lime bag")),
				new BagRule("striped violet bag",new Stock(5,"shiny gray bag"),new Stock(1,"dim lime bag")),
				new BagRule("wavy chartreuse bag",new Stock(3,"striped magenta bag"),new Stock(4,"muted crimson bag"),new Stock(5,"clear maroon bag")),
				new BagRule("plaid salmon bag",new Stock(2,"bright black bag")),
				new BagRule("mirrored teal bag",new Stock(1,"vibrant crimson bag"),new Stock(5,"plaid magenta bag"),new Stock(2,"muted green bag"),new Stock(4,"wavy brown bag")),
				new BagRule("drab yellow bag",new Stock(2,"posh salmon bag"),new Stock(3,"light purple bag"),new Stock(3,"striped orange bag")),
				new BagRule("bright purple bag",new Stock(5,"muted gold bag"),new Stock(3,"dull olive bag"),new Stock(5,"faded violet bag")),
				new BagRule("dim magenta bag",new Stock(5,"dark olive bag"),new Stock(2,"shiny indigo bag"),new Stock(5,"shiny turquoise bag"),new Stock(5,"dark tan bag")),
				new BagRule("wavy violet bag",new Stock(5,"clear white bag"),new Stock(5,"posh coral bag")),
				new BagRule("wavy blue bag",new Stock(4,"pale chartreuse bag"),new Stock(2,"shiny brown bag")),
				new BagRule("plaid crimson bag",new Stock(4,"faded black bag")),
				new BagRule("vibrant tomato bag",new Stock(3,"posh tomato bag"),new Stock(2,"mirrored silver bag"),new Stock(5,"dotted brown bag")),
				new BagRule("clear indigo bag",new Stock(1,"wavy indigo bag")),
				new BagRule("mirrored fuchsia bag",new Stock(2,"vibrant coral bag"),new Stock(5,"clear tan bag"),new Stock(2,"pale indigo bag"),new Stock(1,"drab bronze bag")),
				new BagRule("light silver bag",new Stock(5,"pale plum bag"),new Stock(5,"clear black bag"),new Stock(1,"pale red bag")),
				new BagRule("dim tan bag",new Stock(1,"pale plum bag")),
				new BagRule("pale salmon bag",new Stock(4,"dim lime bag")),
				new BagRule("light lime bag",new Stock(1,"bright fuchsia bag"),new Stock(1,"bright olive bag")),
				new BagRule("dim red bag",new Stock(5,"clear silver bag")),
				new BagRule("striped chartreuse bag",new Stock(5,"dim chartreuse bag"),new Stock(3,"pale cyan bag")),
				new BagRule("bright gray bag",new Stock(2,"posh teal bag"),new Stock(1,"dark turquoise bag"),new Stock(4,"light yellow bag")),
				new BagRule("wavy gold bag",new Stock(5,"drab white bag"),new Stock(2,"wavy salmon bag"),new Stock(5,"dim lime bag"),new Stock(4,"plaid tomato bag")),
				new BagRule("pale maroon bag",new Stock(3,"vibrant magenta bag"),new Stock(5,"dim maroon bag"),new Stock(4,"dull aqua bag"),new Stock(5,"bright coral bag")),
				new BagRule("shiny aqua bag",new Stock(5,"dotted brown bag")),
				new BagRule("dark tomato bag",new Stock(5,"dull violet bag"),new Stock(1,"vibrant magenta bag"),new Stock(3,"muted brown bag")),
				new BagRule("faded aqua bag",new Stock(1,"bright fuchsia bag"),new Stock(5,"dotted violet bag"),new Stock(4,"shiny gold bag")),
				new BagRule("dark plum bag",new Stock(5,"dull aqua bag"),new Stock(3,"faded red bag")),
				new BagRule("plaid aqua bag",new Stock(3,"drab gold bag"),new Stock(3,"faded tomato bag"),new Stock(5,"plaid cyan bag")),
				new BagRule("faded teal bag",new Stock(1,"vibrant beige bag"),new Stock(5,"posh crimson bag")),
				new BagRule("muted coral bag",new Stock(1,"dim plum bag"),new Stock(1,"wavy salmon bag"),new Stock(5,"plaid cyan bag")),
				new BagRule("posh gray bag",new Stock(3,"posh tomato bag")),
				new BagRule("plaid black bag",new Stock(4,"faded aqua bag")),
				new BagRule("wavy gray bag",new Stock(1,"shiny blue bag")),
				new BagRule("shiny maroon bag",new Stock(2,"wavy crimson bag"),new Stock(1,"dotted coral bag"),new Stock(3,"bright tan bag")),
				new BagRule("mirrored lime bag",new Stock(5,"plaid purple bag")),
				new BagRule("dotted chartreuse bag",new Stock(5,"light salmon bag")),
				new BagRule("vibrant gold bag",new Stock(5,"plaid purple bag"),new Stock(3,"bright olive bag"),new Stock(5,"vibrant yellow bag")),
				new BagRule("wavy yellow bag",new Stock(3,"light tomato bag")),
				new BagRule("drab violet bag",new Stock(2,"light violet bag"),new Stock(1,"vibrant tomato bag"),new Stock(3,"dim bronze bag"),new Stock(5,"striped lavender bag")),
				new BagRule("pale lime bag",new Stock(3,"striped blue bag"),new Stock(3,"shiny indigo bag"),new Stock(5,"posh gold bag")),
				new BagRule("light lavender bag",new Stock(2,"faded chartreuse bag"),new Stock(3,"dim lime bag"),new Stock(4,"faded brown bag")),
				new BagRule("mirrored chartreuse bag",new Stock(5,"dotted violet bag"),new Stock(2,"faded brown bag")),
				new BagRule("clear beige bag",new Stock(4,"faded violet bag"),new Stock(3,"clear white bag"),new Stock(5,"plaid indigo bag"),new Stock(2,"wavy indigo bag")),
				new BagRule("dull lime bag",new Stock(4,"plaid black bag"),new Stock(5,"pale bronze bag"),new Stock(1,"bright plum bag")),
				new BagRule("muted violet bag",new Stock(4,"drab white bag"),new Stock(4,"muted silver bag"),new Stock(4,"dotted bronze bag")),
				new BagRule("faded white bag",new Stock(4,"plaid olive bag")),
				new BagRule("striped teal bag",new Stock(2,"drab crimson bag"),new Stock(3,"clear maroon bag"),new Stock(4,"muted blue bag"),new Stock(2,"posh green bag")),
				new BagRule("dull teal bag",new Stock(5,"wavy yellow bag")),
				new BagRule("wavy maroon bag",new Stock(2,"mirrored salmon bag"),new Stock(2,"light teal bag"),new Stock(5,"posh gray bag"),new Stock(3,"muted olive bag")),
				new BagRule("vibrant salmon bag",new Stock(3,"light turquoise bag"),new Stock(4,"striped maroon bag"),new Stock(3,"mirrored white bag"),new Stock(2,"bright olive bag")),
				new BagRule("striped green bag",new Stock(5,"faded gray bag"),new Stock(2,"pale green bag"),new Stock(4,"posh blue bag")),
				new BagRule("posh tan bag",new Stock(4,"clear salmon bag")),
				new BagRule("wavy green bag",new Stock(1,"vibrant plum bag"),new Stock(1,"muted crimson bag"),new Stock(4,"light teal bag"),new Stock(2,"mirrored salmon bag")),
				new BagRule("dotted white bag",new Stock(3,"plaid teal bag"),new Stock(1,"shiny indigo bag")),
				new BagRule("muted tomato bag",new Stock(4,"pale gray bag"),new Stock(5,"wavy red bag"),new Stock(5,"dark violet bag"),new Stock(3,"posh aqua bag")),
				new BagRule("drab beige bag",new Stock(5,"wavy aqua bag")),
				new BagRule("pale purple bag",new Stock(4,"striped black bag"),new Stock(1,"light turquoise bag")),
				new BagRule("muted indigo bag",new Stock(5,"dim gold bag"),new Stock(2,"dull turquoise bag"),new Stock(4,"dotted olive bag")),
				new BagRule("pale coral bag",new Stock(2,"vibrant beige bag")),
				new BagRule("dark beige bag",new Stock(5,"pale turquoise bag")),
				new BagRule("posh crimson bag",new Stock(5,"dark aqua bag"),new Stock(3,"posh teal bag"),new Stock(5,"dull aqua bag")),
				new BagRule("dim purple bag",new Stock(5,"drab crimson bag"),new Stock(3,"pale aqua bag"),new Stock(5,"clear orange bag")),
				new BagRule("shiny teal bag",new Stock(4,"shiny tan bag"),new Stock(2,"striped salmon bag"),new Stock(5,"drab lime bag")),
				new BagRule("muted crimson bag"),
				new BagRule("plaid green bag",new Stock(3,"pale bronze bag")),
				new BagRule("dim aqua bag",new Stock(2,"light lime bag"),new Stock(4,"posh green bag"),new Stock(5,"clear white bag")),
				new BagRule("plaid lavender bag",new Stock(2,"striped lime bag")),
				new BagRule("dark olive bag",new Stock(1,"drab magenta bag"),new Stock(1,"bright magenta bag"),new Stock(2,"plaid crimson bag")),
				new BagRule("striped crimson bag",new Stock(2,"vibrant white bag"),new Stock(1,"pale bronze bag"),new Stock(2,"striped blue bag"),new Stock(4,"pale coral bag")),
				new BagRule("striped lime bag",new Stock(3,"shiny gold bag"),new Stock(1,"muted coral bag"),new Stock(3,"dotted red bag")),
				new BagRule("plaid silver bag",new Stock(2,"drab aqua bag"),new Stock(2,"striped orange bag"),new Stock(2,"plaid crimson bag")),
				new BagRule("dotted tan bag",new Stock(3,"light purple bag"),new Stock(1,"clear teal bag"),new Stock(5,"dotted crimson bag"),new Stock(2,"dim lime bag")),
				new BagRule("clear blue bag",new Stock(5,"dotted green bag"),new Stock(5,"drab crimson bag"),new Stock(2,"wavy tomato bag")),
				new BagRule("muted green bag",new Stock(3,"clear maroon bag"),new Stock(5,"dull orange bag")),
				new BagRule("dull blue bag",new Stock(3,"light silver bag")),
				new BagRule("striped purple bag",new Stock(4,"vibrant tomato bag"),new Stock(1,"dark bronze bag"),new Stock(1,"mirrored white bag")),
				new BagRule("light salmon bag",new Stock(3,"muted coral bag"),new Stock(1,"mirrored yellow bag"),new Stock(4,"faded red bag"),new Stock(3,"muted silver bag")),
				new BagRule("wavy black bag",new Stock(5,"clear indigo bag"),new Stock(4,"dotted purple bag"),new Stock(3,"posh violet bag"),new Stock(4,"bright magenta bag")),
				new BagRule("mirrored crimson bag",new Stock(3,"muted gray bag"),new Stock(5,"drab chartreuse bag")),
				new BagRule("vibrant bronze bag",new Stock(1,"mirrored turquoise bag"),new Stock(3,"dull crimson bag"),new Stock(3,"faded purple bag"),new Stock(5,"dotted beige bag")),
				new BagRule("pale teal bag",new Stock(5,"clear green bag")),
				new BagRule("muted red bag",new Stock(3,"dim plum bag"),new Stock(3,"clear bronze bag")),
				new BagRule("mirrored aqua bag",new Stock(2,"posh aqua bag"),new Stock(1,"plaid tomato bag"),new Stock(1,"mirrored magenta bag"),new Stock(4,"dim chartreuse bag")),
				new BagRule("dim yellow bag",new Stock(5,"bright fuchsia bag"),new Stock(5,"drab tan bag"),new Stock(1,"dark blue bag")),
				new BagRule("vibrant green bag",new Stock(3,"dull aqua bag"),new Stock(2,"posh cyan bag")),
				new BagRule("mirrored black bag",new Stock(2,"striped gray bag")),
				new BagRule("striped turquoise bag",new Stock(1,"shiny gold bag"),new Stock(4,"shiny turquoise bag")),
				new BagRule("wavy plum bag",new Stock(4,"pale brown bag"),new Stock(4,"dark plum bag"),new Stock(1,"bright lavender bag")),
				new BagRule("dotted purple bag",new Stock(2,"dim maroon bag")),
				new BagRule("posh teal bag",new Stock(1,"clear plum bag"),new Stock(4,"faded black bag"),new Stock(1,"dim crimson bag")),
				new BagRule("shiny crimson bag",new Stock(1,"faded red bag")),
				new BagRule("mirrored beige bag",new Stock(1,"faded bronze bag")),
				new BagRule("dotted olive bag",new Stock(5,"pale plum bag"),new Stock(4,"muted plum bag")),
				new BagRule("bright lime bag",new Stock(3,"faded beige bag"),new Stock(3,"wavy fuchsia bag"),new Stock(3,"vibrant plum bag"),new Stock(3,"shiny coral bag")),
				new BagRule("pale bronze bag",new Stock(5,"faded crimson bag"),new Stock(4,"vibrant tan bag"),new Stock(2,"pale coral bag")),
				new BagRule("dim coral bag",new Stock(5,"drab maroon bag"),new Stock(4,"striped violet bag"),new Stock(1,"plaid crimson bag"),new Stock(2,"dim white bag")),
				new BagRule("bright violet bag",new Stock(5,"clear white bag"),new Stock(1,"plaid beige bag")),
				new BagRule("plaid gold bag",new Stock(2,"striped maroon bag")),
				new BagRule("dull red bag",new Stock(4,"wavy tomato bag"),new Stock(5,"clear beige bag")),
				new BagRule("muted tan bag",new Stock(3,"pale beige bag"),new Stock(4,"dotted beige bag"),new Stock(5,"dull cyan bag"),new Stock(1,"striped gold bag")),
				new BagRule("posh plum bag",new Stock(3,"vibrant purple bag"),new Stock(2,"light tomato bag"),new Stock(3,"drab maroon bag"),new Stock(3,"plaid tomato bag")),
				new BagRule("dotted gold bag",new Stock(1,"posh violet bag"),new Stock(4,"dim purple bag"),new Stock(3,"shiny tomato bag")),
				new BagRule("posh black bag",new Stock(1,"muted olive bag"),new Stock(5,"striped turquoise bag"),new Stock(1,"wavy crimson bag")),
				new BagRule("shiny beige bag",new Stock(2,"dull teal bag"),new Stock(3,"striped lavender bag"),new Stock(3,"vibrant indigo bag"),new Stock(3,"mirrored magenta bag")),
				new BagRule("posh silver bag",new Stock(1,"wavy black bag")),
				new BagRule("dotted bronze bag",new Stock(3,"dim plum bag"),new Stock(1,"posh gray bag"),new Stock(5,"mirrored crimson bag"),new Stock(5,"mirrored lime bag")),
				new BagRule("pale indigo bag",new Stock(2,"wavy black bag"),new Stock(4,"shiny aqua bag"),new Stock(1,"striped lime bag")),
				new BagRule("muted olive bag",new Stock(4,"faded brown bag"),new Stock(1,"muted gold bag"),new Stock(1,"faded teal bag"),new Stock(2,"vibrant orange bag")),
				new BagRule("shiny white bag",new Stock(2,"wavy purple bag")),
				new BagRule("bright yellow bag",new Stock(5,"dotted gray bag"),new Stock(5,"clear indigo bag"),new Stock(2,"clear turquoise bag")),
				new BagRule("pale tan bag",new Stock(5,"dotted purple bag"),new Stock(1,"vibrant white bag"),new Stock(3,"pale red bag"),new Stock(3,"mirrored yellow bag")),
				new BagRule("drab gray bag",new Stock(5,"dotted maroon bag"),new Stock(3,"shiny fuchsia bag"),new Stock(5,"dim lime bag"),new Stock(3,"mirrored brown bag")),
				new BagRule("drab blue bag",new Stock(4,"striped purple bag"),new Stock(3,"plaid tomato bag")),
				new BagRule("posh indigo bag",new Stock(3,"muted blue bag")),
				new BagRule("dotted turquoise bag",new Stock(1,"vibrant plum bag"),new Stock(5,"clear gray bag"),new Stock(2,"wavy yellow bag")),
				new BagRule("light red bag",new Stock(2,"muted silver bag"),new Stock(5,"drab chartreuse bag"),new Stock(4,"wavy cyan bag")),
				new BagRule("drab red bag",new Stock(3,"dotted tomato bag"),new Stock(3,"dotted plum bag"),new Stock(5,"drab orange bag"),new Stock(4,"wavy teal bag")),
				new BagRule("dotted beige bag",new Stock(5,"light violet bag")),
				new BagRule("clear gray bag",new Stock(3,"shiny gold bag"),new Stock(3,"dull orange bag"),new Stock(5,"light fuchsia bag"),new Stock(5,"vibrant beige bag")),
				new BagRule("vibrant beige bag",new Stock(2,"drab magenta bag"),new Stock(5,"dim maroon bag"),new Stock(3,"bright turquoise bag"),new Stock(3,"dim plum bag")),
				new BagRule("dark brown bag",new Stock(2,"striped cyan bag"),new Stock(5,"vibrant yellow bag")),
				new BagRule("bright blue bag",new Stock(4,"vibrant lime bag"),new Stock(4,"faded yellow bag"),new Stock(1,"clear orange bag"),new Stock(4,"wavy gray bag")),
				new BagRule("dull plum bag",new Stock(3,"mirrored salmon bag")),
				new BagRule("striped gold bag",new Stock(1,"faded teal bag"),new Stock(4,"vibrant plum bag")),
				new BagRule("dotted gray bag",new Stock(1,"faded black bag"),new Stock(1,"pale tomato bag")),
				new BagRule("plaid olive bag",new Stock(2,"clear gray bag"),new Stock(5,"dotted tan bag")),
				new BagRule("faded plum bag",new Stock(4,"light turquoise bag"),new Stock(1,"dim brown bag"),new Stock(3,"shiny turquoise bag"),new Stock(1,"posh chartreuse bag")),
				new BagRule("clear turquoise bag",new Stock(2,"bright coral bag"),new Stock(3,"drab cyan bag")),
				new BagRule("wavy brown bag",new Stock(5,"clear yellow bag"),new Stock(5,"dim silver bag"),new Stock(1,"mirrored white bag")),
				new BagRule("muted maroon bag",new Stock(3,"posh aqua bag"),new Stock(2,"drab yellow bag"),new Stock(3,"pale crimson bag"),new Stock(1,"dotted maroon bag")),
				new BagRule("clear plum bag"),
				new BagRule("dim silver bag",new Stock(1,"bright fuchsia bag")),
				new BagRule("dotted silver bag",new Stock(2,"dotted indigo bag"),new Stock(2,"faded chartreuse bag"),new Stock(3,"wavy white bag")),
				new BagRule("vibrant olive bag",new Stock(3,"posh coral bag"),new Stock(3,"drab aqua bag")),
				new BagRule("faded yellow bag",new Stock(1,"plaid tomato bag"),new Stock(1,"light tomato bag")),
				new BagRule("drab lavender bag",new Stock(3,"light gray bag"),new Stock(3,"dotted beige bag"),new Stock(4,"dull tomato bag")),
				new BagRule("drab tomato bag",new Stock(4,"wavy aqua bag"),new Stock(1,"posh teal bag"),new Stock(5,"clear red bag"),new Stock(4,"clear plum bag")),
				new BagRule("pale beige bag",new Stock(5,"wavy salmon bag")),
				new BagRule("pale magenta bag",new Stock(5,"bright fuchsia bag")),
				new BagRule("dotted black bag",new Stock(3,"mirrored lime bag")),
				new BagRule("bright plum bag",new Stock(5,"vibrant teal bag")),
				new BagRule("bright lavender bag",new Stock(5,"dotted purple bag"),new Stock(1,"faded black bag"),new Stock(4,"light purple bag")),
				new BagRule("muted yellow bag",new Stock(4,"dotted aqua bag"),new Stock(1,"dim cyan bag")),
				new BagRule("shiny tomato bag",new Stock(1,"dim crimson bag")),
				new BagRule("dotted magenta bag",new Stock(2,"clear maroon bag"),new Stock(5,"plaid gold bag")),
				new BagRule("dull aqua bag",new Stock(2,"shiny blue bag")),
				new BagRule("faded silver bag",new Stock(4,"faded brown bag"),new Stock(1,"muted brown bag")),
				new BagRule("muted gray bag",new Stock(2,"light yellow bag"),new Stock(5,"mirrored brown bag"),new Stock(3,"bright teal bag"),new Stock(5,"posh teal bag")),
				new BagRule("mirrored gold bag",new Stock(4,"shiny black bag"),new Stock(5,"shiny coral bag"),new Stock(2,"clear orange bag"),new Stock(4,"mirrored aqua bag")),
				new BagRule("plaid teal bag",new Stock(4,"dull orange bag"),new Stock(2,"shiny gold bag"),new Stock(2,"plaid crimson bag"),new Stock(4,"clear green bag")),
				new BagRule("light white bag",new Stock(5,"vibrant white bag"),new Stock(1,"posh lavender bag"),new Stock(3,"clear white bag")),
				new BagRule("shiny turquoise bag",new Stock(3,"bright turquoise bag")),
				new BagRule("muted orange bag",new Stock(1,"bright tan bag"),new Stock(1,"shiny teal bag"),new Stock(5,"bright gold bag")),
				new BagRule("mirrored bronze bag",new Stock(2,"drab white bag"),new Stock(4,"clear bronze bag"),new Stock(3,"drab blue bag")),
				new BagRule("shiny green bag",new Stock(4,"mirrored cyan bag")),
				new BagRule("posh tomato bag",new Stock(3,"dull orange bag"),new Stock(2,"clear plum bag")),
				new BagRule("shiny salmon bag",new Stock(2,"vibrant tomato bag"),new Stock(3,"muted olive bag"),new Stock(2,"dim bronze bag")),
				new BagRule("muted purple bag",new Stock(4,"shiny turquoise bag")),
				new BagRule("dim lime bag",new Stock(3,"posh teal bag")),
				new BagRule("muted chartreuse bag",new Stock(1,"dotted fuchsia bag"),new Stock(4,"light teal bag"),new Stock(4,"dull salmon bag")),
				new BagRule("mirrored yellow bag",new Stock(4,"wavy brown bag")),
				new BagRule("drab teal bag",new Stock(1,"mirrored maroon bag"),new Stock(1,"faded fuchsia bag"),new Stock(3,"bright coral bag"),new Stock(2,"dull purple bag")),
				new BagRule("plaid plum bag",new Stock(4,"dark cyan bag")),
				new BagRule("dim indigo bag",new Stock(3,"dotted gold bag"),new Stock(5,"muted coral bag"),new Stock(2,"posh plum bag")),
				new BagRule("wavy aqua bag",new Stock(4,"drab gold bag"),new Stock(5,"wavy yellow bag")),
				new BagRule("vibrant brown bag",new Stock(3,"posh violet bag"),new Stock(4,"pale magenta bag")),
				new BagRule("faded maroon bag",new Stock(4,"dull maroon bag"),new Stock(4,"light indigo bag"),new Stock(4,"wavy beige bag"),new Stock(1,"clear olive bag")),
				new BagRule("light crimson bag",new Stock(1,"dim gray bag")),
				new BagRule("plaid orange bag",new Stock(5,"plaid bronze bag"),new Stock(1,"dark orange bag")),
				new BagRule("clear gold bag",new Stock(5,"plaid black bag"),new Stock(4,"faded coral bag")),
				new BagRule("mirrored gray bag",new Stock(1,"shiny coral bag"),new Stock(3,"pale beige bag"),new Stock(1,"dark tan bag")),
				new BagRule("dark gray bag",new Stock(4,"dim turquoise bag"),new Stock(3,"clear gray bag")),
				new BagRule("light fuchsia bag",new Stock(3,"dotted brown bag"),new Stock(3,"clear maroon bag")),
				new BagRule("posh cyan bag",new Stock(2,"dotted violet bag")),
				new BagRule("light cyan bag",new Stock(2,"drab maroon bag"),new Stock(5,"vibrant indigo bag"),new Stock(3,"dull tomato bag"),new Stock(3,"wavy gray bag")),
				new BagRule("wavy olive bag",new Stock(5,"wavy cyan bag"),new Stock(4,"mirrored tomato bag")),
				new BagRule("faded indigo bag",new Stock(4,"bright bronze bag"),new Stock(5,"dim lime bag")),
				new BagRule("muted plum bag",new Stock(1,"clear maroon bag")),
				new BagRule("muted brown bag",new Stock(2,"posh gray bag")),
				new BagRule("pale tomato bag",new Stock(3,"dull cyan bag"),new Stock(3,"faded beige bag")),
				new BagRule("striped blue bag",new Stock(1,"faded tomato bag"),new Stock(3,"dotted purple bag")),
				new BagRule("dotted fuchsia bag",new Stock(2,"posh green bag"),new Stock(1,"faded aqua bag")),
				new BagRule("vibrant fuchsia bag",new Stock(3,"mirrored white bag")),
				new BagRule("pale cyan bag",new Stock(3,"dotted green bag"),new Stock(3,"drab maroon bag")),
				new BagRule("wavy silver bag",new Stock(1,"vibrant yellow bag"),new Stock(5,"mirrored chartreuse bag"),new Stock(1,"drab magenta bag"),new Stock(2,"faded tan bag")),
				new BagRule("vibrant black bag",new Stock(3,"dotted purple bag"),new Stock(3,"bright coral bag")),
				new BagRule("dull bronze bag",new Stock(5,"dull white bag"),new Stock(4,"dark olive bag")),
				new BagRule("wavy purple bag",new Stock(2,"dim lavender bag"),new Stock(5,"striped red bag"),new Stock(4,"posh yellow bag"),new Stock(1,"dotted fuchsia bag")),
				new BagRule("dim salmon bag",new Stock(3,"vibrant magenta bag"),new Stock(4,"wavy fuchsia bag"),new Stock(1,"plaid fuchsia bag"),new Stock(2,"dim magenta bag")),
				new BagRule("dim orange bag",new Stock(2,"muted lime bag")),
				new BagRule("plaid fuchsia bag",new Stock(1,"vibrant crimson bag"),new Stock(1,"dotted beige bag"),new Stock(5,"wavy gray bag"),new Stock(1,"dim bronze bag")),
				new BagRule("dark black bag",new Stock(2,"posh lavender bag"),new Stock(4,"light black bag"),new Stock(5,"bright orange bag")),
				new BagRule("muted teal bag",new Stock(5,"clear red bag"),new Stock(4,"vibrant magenta bag"),new Stock(1,"vibrant aqua bag")),
				new BagRule("mirrored lavender bag",new Stock(1,"faded bronze bag"),new Stock(2,"bright violet bag"),new Stock(4,"dull turquoise bag")),
				new BagRule("dark lavender bag",new Stock(5,"dotted gold bag"),new Stock(2,"dark turquoise bag"),new Stock(1,"dark brown bag")),
				new BagRule("dull brown bag",new Stock(2,"faded brown bag"),new Stock(3,"dotted lime bag"),new Stock(5,"dull plum bag"),new Stock(3,"dull white bag")),
				new BagRule("pale gray bag",new Stock(1,"pale salmon bag"),new Stock(5,"dotted fuchsia bag")),
				new BagRule("light coral bag",new Stock(2,"bright magenta bag"),new Stock(1,"wavy brown bag")),
				new BagRule("dull tan bag",new Stock(5,"shiny turquoise bag"),new Stock(5,"light cyan bag"),new Stock(2,"faded indigo bag")),
				new BagRule("dim bronze bag",new Stock(5,"striped blue bag")),
				new BagRule("bright tomato bag",new Stock(1,"striped black bag")),
				new BagRule("shiny chartreuse bag",new Stock(4,"plaid aqua bag"),new Stock(1,"striped tomato bag"),new Stock(3,"striped black bag"),new Stock(4,"dull maroon bag")),
				new BagRule("mirrored silver bag",new Stock(4,"shiny blue bag"),new Stock(4,"dotted maroon bag"),new Stock(3,"clear maroon bag"),new Stock(4,"clear plum bag")),
				new BagRule("pale olive bag",new Stock(5,"drab brown bag"),new Stock(1,"bright lime bag"),new Stock(1,"vibrant lime bag"),new Stock(3,"muted blue bag")),
				new BagRule("pale gold bag",new Stock(1,"mirrored chartreuse bag"),new Stock(4,"posh silver bag")),
				new BagRule("plaid indigo bag",new Stock(1,"bright fuchsia bag"),new Stock(1,"wavy indigo bag"),new Stock(5,"dark aqua bag")),
				new BagRule("mirrored green bag",new Stock(4,"mirrored crimson bag"),new Stock(2,"dull turquoise bag")),
				new BagRule("shiny fuchsia bag",new Stock(4,"wavy crimson bag")),
				new BagRule("drab salmon bag",new Stock(1,"faded silver bag"),new Stock(4,"muted white bag"),new Stock(4,"clear yellow bag")),
				new BagRule("bright salmon bag",new Stock(4,"bright crimson bag"),new Stock(1,"muted tomato bag")),
				new BagRule("posh chartreuse bag",new Stock(3,"posh cyan bag"),new Stock(4,"plaid cyan bag")),
				new BagRule("wavy cyan bag",new Stock(1,"vibrant magenta bag"),new Stock(2,"posh crimson bag")),
				new BagRule("shiny indigo bag",new Stock(1,"plaid teal bag")),
				new BagRule("shiny purple bag",new Stock(1,"dark purple bag"),new Stock(5,"dull magenta bag"),new Stock(3,"plaid fuchsia bag")),
				new BagRule("bright gold bag",new Stock(3,"faded aqua bag")),
				new BagRule("vibrant yellow bag",new Stock(3,"vibrant brown bag"),new Stock(3,"wavy green bag"),new Stock(5,"dotted brown bag"),new Stock(5,"striped plum bag")),
				new BagRule("muted beige bag",new Stock(4,"vibrant tomato bag"),new Stock(3,"dull fuchsia bag")),
				new BagRule("dim maroon bag"),
				new BagRule("mirrored tan bag",new Stock(3,"pale turquoise bag"),new Stock(3,"muted olive bag"),new Stock(3,"shiny violet bag")),
				new BagRule("striped gray bag",new Stock(5,"mirrored gold bag")),
				new BagRule("drab purple bag",new Stock(1,"wavy orange bag")),
				new BagRule("dull silver bag",new Stock(4,"clear chartreuse bag"),new Stock(4,"posh cyan bag"),new Stock(2,"pale salmon bag"),new Stock(3,"shiny lavender bag")),
				new BagRule("dim blue bag",new Stock(1,"clear turquoise bag"),new Stock(1,"clear orange bag"),new Stock(4,"clear teal bag")),
				new BagRule("dull maroon bag",new Stock(2,"striped plum bag")),
				new BagRule("posh magenta bag",new Stock(4,"dim gray bag")),
				new BagRule("light beige bag",new Stock(4,"dotted turquoise bag"),new Stock(1,"pale cyan bag")),
				new BagRule("dim olive bag",new Stock(3,"plaid teal bag"),new Stock(5,"faded brown bag"),new Stock(1,"faded crimson bag")),
				new BagRule("light tomato bag"),
				new BagRule("drab black bag",new Stock(2,"wavy brown bag"),new Stock(1,"dull maroon bag"),new Stock(5,"muted crimson bag"),new Stock(3,"posh green bag")),
				new BagRule("posh coral bag",new Stock(1,"drab gray bag"),new Stock(1,"striped red bag")),
				new BagRule("mirrored cyan bag",new Stock(4,"drab gray bag")),
				new BagRule("dotted salmon bag",new Stock(4,"striped coral bag"),new Stock(2,"muted purple bag")),
				new BagRule("bright maroon bag",new Stock(1,"faded crimson bag"),new Stock(4,"clear maroon bag"),new Stock(2,"faded brown bag")),
				new BagRule("light turquoise bag",new Stock(2,"shiny lime bag"),new Stock(5,"dotted violet bag"),new Stock(3,"vibrant tan bag"),new Stock(5,"shiny cyan bag")),
				new BagRule("faded black bag",new Stock(4,"drab magenta bag"),new Stock(3,"dim plum bag"),new Stock(5,"bright fuchsia bag")),
				new BagRule("vibrant silver bag",new Stock(2,"clear violet bag"),new Stock(2,"drab orange bag"),new Stock(5,"plaid magenta bag"),new Stock(5,"shiny violet bag")),
				new BagRule("vibrant tan bag",new Stock(3,"clear bronze bag"),new Stock(5,"vibrant tomato bag"),new Stock(4,"light teal bag")),
				new BagRule("clear bronze bag",new Stock(1,"posh green bag"),new Stock(4,"faded brown bag"),new Stock(1,"shiny violet bag")),
				new BagRule("striped salmon bag",new Stock(2,"dark fuchsia bag"),new Stock(4,"shiny chartreuse bag")),
				new BagRule("wavy indigo bag"),
				new BagRule("dark violet bag",new Stock(5,"dull violet bag"),new Stock(3,"wavy tomato bag"),new Stock(5,"pale green bag")),
				new BagRule("drab magenta bag",new Stock(4,"wavy indigo bag"),new Stock(2,"dark aqua bag"),new Stock(4,"dotted brown bag"),new Stock(2,"muted crimson bag")),
				new BagRule("dark orange bag",new Stock(3,"faded violet bag"),new Stock(3,"shiny coral bag"),new Stock(4,"light violet bag")),
				new BagRule("drab green bag",new Stock(1,"light tan bag"),new Stock(2,"plaid tomato bag")),
				new BagRule("mirrored magenta bag",new Stock(4,"vibrant plum bag"),new Stock(4,"vibrant black bag")),
				new BagRule("muted cyan bag",new Stock(1,"dull aqua bag"),new Stock(3,"dark cyan bag")),
				new BagRule("dim plum bag",new Stock(2,"wavy yellow bag"),new Stock(3,"bright fuchsia bag")),
				new BagRule("dark bronze bag",new Stock(2,"shiny violet bag"),new Stock(2,"clear plum bag")),
				new BagRule("striped coral bag",new Stock(3,"shiny coral bag")),
				new BagRule("faded violet bag",new Stock(4,"plaid indigo bag")),
				new BagRule("posh brown bag",new Stock(5,"posh magenta bag"),new Stock(5,"bright fuchsia bag"),new Stock(1,"vibrant plum bag")),
				new BagRule("drab coral bag",new Stock(5,"vibrant beige bag")),
				new BagRule("plaid tan bag",new Stock(5,"dark orange bag"),new Stock(5,"dotted tan bag")),
				new BagRule("dark silver bag",new Stock(1,"pale plum bag"),new Stock(5,"bright cyan bag"),new Stock(3,"wavy aqua bag")),
				new BagRule("dark lime bag",new Stock(3,"drab green bag"),new Stock(5,"light crimson bag")),
				new BagRule("dull salmon bag",new Stock(3,"dull maroon bag"),new Stock(5,"striped gold bag"),new Stock(2,"dotted maroon bag")),
				new BagRule("bright white bag",new Stock(5,"pale teal bag"),new Stock(2,"posh white bag"),new Stock(2,"bright crimson bag"),new Stock(3,"pale fuchsia bag")),
				new BagRule("vibrant violet bag",new Stock(5,"dim brown bag"),new Stock(2,"bright brown bag"),new Stock(2,"pale coral bag"),new Stock(1,"wavy plum bag")),
				new BagRule("vibrant magenta bag",new Stock(2,"clear maroon bag"),new Stock(3,"wavy indigo bag"),new Stock(5,"plaid bronze bag")),
				new BagRule("faded coral bag",new Stock(5,"vibrant maroon bag"),new Stock(3,"mirrored beige bag")),
				new BagRule("dark teal bag",new Stock(1,"dark tan bag"),new Stock(2,"posh chartreuse bag")),
				new BagRule("dark crimson bag",new Stock(2,"dark fuchsia bag"),new Stock(5,"striped blue bag")),
				new BagRule("dull yellow bag",new Stock(1,"faded bronze bag"),new Stock(4,"dark beige bag"),new Stock(5,"plaid black bag"),new Stock(1,"posh salmon bag")),
				new BagRule("plaid magenta bag",new Stock(1,"plaid beige bag"),new Stock(2,"posh teal bag")),
				new BagRule("pale chartreuse bag",new Stock(1,"plaid orange bag"),new Stock(2,"vibrant beige bag"),new Stock(5,"muted gold bag")),
				new BagRule("posh lavender bag",new Stock(3,"plaid violet bag"),new Stock(4,"dark blue bag"),new Stock(2,"wavy teal bag"),new Stock(5,"vibrant black bag")),
				new BagRule("dull purple bag",new Stock(2,"posh lime bag"),new Stock(1,"wavy olive bag"),new Stock(1,"striped red bag"),new Stock(5,"pale lime bag")),
				new BagRule("bright tan bag",new Stock(2,"shiny tan bag"),new Stock(4,"clear green bag"),new Stock(1,"light violet bag")),
				new BagRule("pale plum bag",new Stock(4,"dull crimson bag"),new Stock(2,"vibrant orange bag"),new Stock(2,"striped cyan bag")),
				new BagRule("clear crimson bag",new Stock(3,"mirrored silver bag")),
				new BagRule("light blue bag",new Stock(5,"dull magenta bag"),new Stock(4,"clear black bag"),new Stock(2,"bright tan bag"),new Stock(1,"dotted teal bag")),
				new BagRule("muted turquoise bag",new Stock(3,"bright red bag"),new Stock(3,"light tomato bag"),new Stock(3,"dull gold bag"),new Stock(4,"clear cyan bag")),
				new BagRule("muted lime bag",new Stock(5,"dim olive bag"),new Stock(3,"pale fuchsia bag")),
				new BagRule("clear green bag",new Stock(5,"dim maroon bag"),new Stock(4,"bright fuchsia bag"),new Stock(1,"muted crimson bag"),new Stock(1,"shiny blue bag")),
				new BagRule("dim green bag",new Stock(2,"pale turquoise bag")),
				new BagRule("plaid red bag",new Stock(3,"plaid silver bag")),
				new BagRule("mirrored brown bag",new Stock(1,"clear plum bag")),
				new BagRule("dull lavender bag",new Stock(1,"clear teal bag")),
				new BagRule("shiny brown bag",new Stock(5,"shiny coral bag"),new Stock(1,"posh black bag"),new Stock(2,"dotted maroon bag"),new Stock(2,"muted olive bag")),
				new BagRule("dotted green bag",new Stock(2,"clear crimson bag"),new Stock(2,"dim gray bag"),new Stock(1,"plaid green bag"),new Stock(1,"dotted maroon bag")),
				new BagRule("vibrant maroon bag",new Stock(2,"mirrored brown bag"),new Stock(5,"shiny coral bag")),
				new BagRule("dotted tomato bag",new Stock(3,"wavy coral bag"),new Stock(3,"dotted crimson bag")),
				new BagRule("vibrant turquoise bag",new Stock(5,"posh tomato bag"),new Stock(2,"faded bronze bag")),
				new BagRule("bright aqua bag",new Stock(4,"light tan bag")),
				new BagRule("clear teal bag",new Stock(1,"mirrored salmon bag"),new Stock(4,"dark aqua bag")),
				new BagRule("shiny gray bag",new Stock(3,"mirrored crimson bag"),new Stock(4,"drab chartreuse bag")),
				new BagRule("muted black bag",new Stock(4,"wavy orange bag")),
				new BagRule("posh yellow bag",new Stock(4,"plaid teal bag")),
				new BagRule("pale black bag",new Stock(5,"wavy brown bag"),new Stock(1,"mirrored yellow bag")),
				new BagRule("dark red bag",new Stock(5,"striped magenta bag"),new Stock(5,"plaid salmon bag")),
				new BagRule("dull magenta bag",new Stock(2,"light white bag"),new Stock(3,"mirrored blue bag"),new Stock(3,"faded black bag"),new Stock(5,"shiny coral bag")),
				new BagRule("mirrored orange bag",new Stock(5,"posh white bag")),
				new BagRule("dark salmon bag",new Stock(2,"posh fuchsia bag")),
				new BagRule("bright brown bag",new Stock(4,"posh blue bag"),new Stock(3,"shiny brown bag")),
				new BagRule("drab lime bag",new Stock(4,"dotted maroon bag"),new Stock(3,"pale bronze bag"),new Stock(2,"striped black bag")),
				new BagRule("dull violet bag",new Stock(5,"bright lavender bag"),new Stock(1,"shiny coral bag")),
				new BagRule("muted silver bag",new Stock(1,"muted coral bag")),
				new BagRule("dull olive bag",new Stock(4,"pale cyan bag"),new Stock(5,"drab green bag"),new Stock(4,"clear turquoise bag")),
				new BagRule("light aqua bag",new Stock(4,"posh orange bag"),new Stock(4,"dull fuchsia bag")),
				new BagRule("vibrant coral bag",new Stock(1,"clear bronze bag"),new Stock(3,"striped brown bag")),
				new BagRule("muted magenta bag",new Stock(1,"clear fuchsia bag"),new Stock(5,"shiny crimson bag"),new Stock(4,"shiny gold bag"),new Stock(2,"plaid cyan bag")),
				new BagRule("faded blue bag",new Stock(5,"plaid green bag")),
				new BagRule("clear cyan bag",new Stock(3,"drab cyan bag")),
				new BagRule("wavy beige bag",new Stock(4,"mirrored white bag"),new Stock(4,"bright white bag"),new Stock(5,"dark beige bag"),new Stock(5,"pale tomato bag")),
				new BagRule("light maroon bag",new Stock(3,"vibrant maroon bag"),new Stock(1,"dark orange bag"),new Stock(3,"drab plum bag")),
				new BagRule("faded green bag",new Stock(1,"vibrant black bag")),
				new BagRule("vibrant teal bag",new Stock(4,"shiny violet bag")),
				new BagRule("clear coral bag",new Stock(4,"dark maroon bag"),new Stock(1,"striped tomato bag"),new Stock(4,"light orange bag")),
				new BagRule("pale lavender bag",new Stock(4,"light green bag"),new Stock(2,"drab magenta bag")),
				new BagRule("muted blue bag",new Stock(5,"pale cyan bag"),new Stock(4,"posh teal bag")),
				new BagRule("mirrored plum bag",new Stock(5,"drab aqua bag"),new Stock(3,"striped gold bag")),
				new BagRule("dull chartreuse bag",new Stock(1,"dull orange bag"),new Stock(5,"clear chartreuse bag")),
				new BagRule("faded magenta bag",new Stock(4,"bright blue bag")),
				new BagRule("dim cyan bag",new Stock(1,"muted brown bag"),new Stock(3,"posh magenta bag")),
				new BagRule("dim beige bag",new Stock(3,"shiny blue bag"),new Stock(4,"dim black bag")),
				new BagRule("faded tomato bag",new Stock(1,"vibrant magenta bag"),new Stock(2,"plaid cyan bag"),new Stock(4,"muted crimson bag")),
				new BagRule("clear aqua bag",new Stock(1,"dull bronze bag"),new Stock(4,"shiny bronze bag")),
				new BagRule("pale fuchsia bag",new Stock(2,"mirrored orange bag")),
				new BagRule("drab olive bag",new Stock(3,"wavy salmon bag")),
				new BagRule("clear white bag",new Stock(1,"vibrant teal bag"),new Stock(1,"posh tomato bag"),new Stock(5,"vibrant aqua bag")),
				new BagRule("drab orange bag",new Stock(3,"striped gold bag"),new Stock(2,"mirrored tan bag"),new Stock(3,"dull tomato bag"),new Stock(2,"wavy aqua bag")),
				new BagRule("plaid purple bag",new Stock(3,"dotted maroon bag"),new Stock(5,"shiny turquoise bag")),
				new BagRule("mirrored violet bag",new Stock(4,"clear white bag"),new Stock(2,"shiny black bag")),
				new BagRule("dotted teal bag",new Stock(2,"dim teal bag"),new Stock(1,"striped fuchsia bag")),
				new BagRule("bright beige bag",new Stock(2,"dim silver bag"),new Stock(3,"dull beige bag")),
				new BagRule("dim turquoise bag",new Stock(1,"plaid silver bag"),new Stock(1,"light yellow bag"),new Stock(2,"shiny orange bag"),new Stock(3,"striped cyan bag")),
				new BagRule("dotted brown bag"),
				new BagRule("drab maroon bag",new Stock(4,"clear plum bag"),new Stock(4,"shiny coral bag")),
				new BagRule("dark indigo bag",new Stock(1,"mirrored magenta bag")),
				new BagRule("posh bronze bag",new Stock(3,"bright bronze bag"),new Stock(4,"dotted maroon bag"),new Stock(3,"wavy tomato bag"),new Stock(4,"dotted lime bag")),
				new BagRule("vibrant cyan bag",new Stock(5,"wavy brown bag")),
				new BagRule("drab turquoise bag",new Stock(2,"muted silver bag"),new Stock(2,"bright maroon bag"),new Stock(5,"dim gray bag")),
				new BagRule("pale red bag",new Stock(1,"shiny coral bag"),new Stock(5,"mirrored silver bag"),new Stock(3,"shiny turquoise bag")),
				new BagRule("vibrant lime bag",new Stock(4,"light lavender bag"),new Stock(4,"mirrored tomato bag")),
				new BagRule("dim black bag",new Stock(2,"light beige bag"),new Stock(1,"plaid cyan bag"),new Stock(2,"posh yellow bag"),new Stock(3,"vibrant cyan bag")),
				new BagRule("dull coral bag",new Stock(5,"dull orange bag"),new Stock(1,"dotted green bag")),
				new BagRule("posh violet bag",new Stock(5,"light green bag"),new Stock(3,"pale teal bag")),
				new BagRule("bright silver bag",new Stock(5,"wavy white bag"),new Stock(2,"vibrant salmon bag")),
				new BagRule("light plum bag",new Stock(4,"light indigo bag"),new Stock(1,"posh gold bag")),
				new BagRule("plaid coral bag",new Stock(4,"dark olive bag")),
				new BagRule("bright magenta bag",new Stock(1,"bright fuchsia bag"),new Stock(4,"dim crimson bag"),new Stock(2,"clear yellow bag"),new Stock(2,"bright lavender bag")),
				new BagRule("striped lavender bag",new Stock(4,"dull orange bag")),
				new BagRule("drab aqua bag",new Stock(4,"vibrant tan bag"),new Stock(3,"vibrant crimson bag"),new Stock(1,"dotted purple bag")),
				new BagRule("shiny blue bag",new Stock(2,"plaid bronze bag")),
				new BagRule("wavy lime bag",new Stock(2,"drab orange bag")),
				new BagRule("dull white bag",new Stock(4,"light teal bag")),
				new BagRule("pale orange bag",new Stock(2,"plaid yellow bag"),new Stock(1,"posh indigo bag")),
				new BagRule("faded chartreuse bag",new Stock(4,"dull tomato bag"),new Stock(3,"mirrored salmon bag")),
				new BagRule("bright orange bag",new Stock(4,"vibrant yellow bag"),new Stock(4,"vibrant salmon bag"),new Stock(3,"faded white bag"),new Stock(4,"clear orange bag")),
				new BagRule("dark blue bag",new Stock(3,"vibrant indigo bag")),
				new BagRule("striped indigo bag",new Stock(3,"vibrant magenta bag")),
				new BagRule("mirrored blue bag",new Stock(5,"bright crimson bag"),new Stock(5,"light salmon bag"),new Stock(5,"dark olive bag")),
				new BagRule("plaid chartreuse bag",new Stock(5,"drab tomato bag"),new Stock(1,"dark tan bag"),new Stock(4,"dotted crimson bag"),new Stock(5,"dark bronze bag")),
				new BagRule("shiny cyan bag",new Stock(1,"shiny aqua bag"),new Stock(5,"clear plum bag"),new Stock(1,"posh gray bag"),new Stock(5,"shiny coral bag")),
				new BagRule("dim violet bag",new Stock(3,"drab chartreuse bag"),new Stock(4,"pale lavender bag"),new Stock(5,"shiny gold bag")),
				new BagRule("dotted orange bag",new Stock(5,"plaid chartreuse bag"),new Stock(4,"vibrant purple bag"),new Stock(5,"posh teal bag")),
				new BagRule("clear magenta bag",new Stock(3,"clear indigo bag")),
				new BagRule("vibrant chartreuse bag",new Stock(4,"faded violet bag")),
				new BagRule("dark cyan bag",new Stock(2,"dim plum bag"),new Stock(5,"light purple bag"),new Stock(1,"dark olive bag"),new Stock(2,"dim maroon bag")),
				new BagRule("light olive bag",new Stock(5,"pale lime bag"),new Stock(2,"mirrored lime bag")),
				new BagRule("vibrant lavender bag",new Stock(2,"pale black bag")),
				new BagRule("plaid maroon bag",new Stock(4,"clear white bag")),
				new BagRule("pale aqua bag",new Stock(2,"shiny tomato bag"),new Stock(4,"dim gold bag"),new Stock(5,"pale green bag")),
				new BagRule("posh blue bag",new Stock(1,"wavy fuchsia bag"),new Stock(3,"light cyan bag"),new Stock(1,"striped beige bag")),
				new BagRule("clear lime bag",new Stock(4,"mirrored gold bag"),new Stock(2,"wavy coral bag")),
				new BagRule("pale yellow bag",new Stock(2,"dull cyan bag"),new Stock(1,"dotted maroon bag"),new Stock(3,"light teal bag"),new Stock(1,"clear gray bag")),
				new BagRule("muted lavender bag",new Stock(1,"wavy cyan bag")),
				new BagRule("light magenta bag",new Stock(5,"shiny lime bag"),new Stock(3,"light indigo bag"),new Stock(2,"clear beige bag")),
				new BagRule("dotted maroon bag",new Stock(4,"wavy yellow bag"),new Stock(5,"bright fuchsia bag"),new Stock(5,"faded brown bag")),
				new BagRule("shiny red bag",new Stock(2,"faded tomato bag"),new Stock(3,"faded black bag"),new Stock(2,"pale teal bag"),new Stock(5,"muted bronze bag")),
				new BagRule("shiny lavender bag",new Stock(1,"bright yellow bag"),new Stock(2,"plaid purple bag"),new Stock(2,"light coral bag"),new Stock(4,"pale purple bag")),
				new BagRule("clear violet bag",new Stock(1,"plaid chartreuse bag")),
				new BagRule("muted white bag",new Stock(1,"striped turquoise bag")),
				new BagRule("plaid bronze bag"),
				new BagRule("faded fuchsia bag",new Stock(5,"clear red bag")),
				new BagRule("dull orange bag",new Stock(5,"drab gold bag"),new Stock(2,"dotted purple bag"),new Stock(4,"bright turquoise bag"),new Stock(4,"plaid bronze bag")),
				new BagRule("clear red bag",new Stock(4,"clear crimson bag"),new Stock(3,"bright turquoise bag"),new Stock(3,"clear green bag")),
				new BagRule("vibrant aqua bag",new Stock(5,"light gray bag"),new Stock(3,"light tomato bag"),new Stock(5,"vibrant white bag"),new Stock(5,"posh tomato bag")),
				new BagRule("drab bronze bag",new Stock(3,"striped fuchsia bag"),new Stock(3,"vibrant coral bag"),new Stock(3,"posh turquoise bag"),new Stock(5,"clear maroon bag")),
				new BagRule("dotted crimson bag",new Stock(4,"muted teal bag"),new Stock(5,"dull violet bag"),new Stock(2,"muted gold bag")),
				new BagRule("mirrored purple bag",new Stock(5,"drab black bag"),new Stock(1,"dotted teal bag")),
				new BagRule("dark aqua bag"),
				new BagRule("light tan bag",new Stock(5,"dotted tan bag")),
				new BagRule("wavy turquoise bag",new Stock(2,"mirrored cyan bag"),new Stock(4,"mirrored magenta bag"),new Stock(5,"dull salmon bag"),new Stock(2,"vibrant tomato bag")),
				new BagRule("light black bag",new Stock(5,"clear plum bag"),new Stock(5,"faded olive bag")),
				new BagRule("vibrant blue bag",new Stock(4,"dark crimson bag"),new Stock(2,"clear indigo bag"),new Stock(2,"pale lime bag")),
				new BagRule("clear silver bag",new Stock(1,"striped coral bag"),new Stock(5,"faded crimson bag"),new Stock(5,"mirrored chartreuse bag"),new Stock(2,"vibrant magenta bag")),
				new BagRule("shiny gold bag",new Stock(5,"plaid bronze bag"),new Stock(4,"bright fuchsia bag"),new Stock(2,"light violet bag"),new Stock(1,"clear plum bag")),
				new BagRule("bright red bag",new Stock(2,"pale coral bag")),
				new BagRule("dull tomato bag",new Stock(3,"mirrored salmon bag")),
				new BagRule("clear fuchsia bag",new Stock(3,"bright brown bag")),
				new BagRule("faded orange bag",new Stock(4,"clear plum bag"),new Stock(5,"faded maroon bag")),
				new BagRule("clear black bag",new Stock(2,"plaid aqua bag"),new Stock(2,"faded yellow bag"),new Stock(2,"bright magenta bag"),new Stock(5,"striped blue bag")),
				new BagRule("drab white bag",new Stock(1,"muted olive bag"),new Stock(5,"posh magenta bag"),new Stock(3,"plaid tan bag")),
				new BagRule("wavy salmon bag",new Stock(1,"clear maroon bag")),
				new BagRule("shiny yellow bag",new Stock(2,"bright magenta bag")),
				new BagRule("shiny lime bag",new Stock(4,"shiny turquoise bag"),new Stock(2,"mirrored white bag"),new Stock(4,"faded bronze bag"),new Stock(1,"vibrant white bag")),
				new BagRule("clear yellow bag",new Stock(5,"shiny violet bag"),new Stock(4,"light tomato bag"),new Stock(3,"clear plum bag"),new Stock(1,"wavy indigo bag")),
				new BagRule("wavy red bag",new Stock(2,"dim crimson bag"),new Stock(5,"plaid cyan bag")),
				new BagRule("dotted red bag",new Stock(5,"dim plum bag")),
				new BagRule("faded red bag",new Stock(3,"striped maroon bag")),
				new BagRule("muted gold bag",new Stock(1,"vibrant teal bag"),new Stock(3,"faded crimson bag")),
				new BagRule("dotted aqua bag",new Stock(2,"dotted coral bag"),new Stock(4,"faded maroon bag")),
				new BagRule("vibrant purple bag",new Stock(3,"posh aqua bag"),new Stock(2,"light gray bag")),
				new BagRule("faded salmon bag",new Stock(5,"plaid brown bag"),new Stock(4,"drab white bag"),new Stock(5,"wavy olive bag")),
				new BagRule("light chartreuse bag",new Stock(4,"shiny coral bag"),new Stock(2,"shiny purple bag")),
				new BagRule("dim brown bag",new Stock(5,"clear bronze bag"),new Stock(2,"striped orange bag"),new Stock(5,"dark olive bag")),
				new BagRule("striped black bag",new Stock(1,"dark orange bag"),new Stock(4,"faded red bag")),
				new BagRule("dark white bag",new Stock(5,"clear white bag"),new Stock(2,"dull bronze bag"),new Stock(5,"dull chartreuse bag"),new Stock(3,"dark crimson bag")),
				new BagRule("striped brown bag",new Stock(1,"shiny indigo bag"),new Stock(1,"vibrant black bag")),
				new BagRule("bright olive bag",new Stock(4,"striped black bag"),new Stock(3,"dull violet bag"),new Stock(3,"vibrant orange bag")),
				new BagRule("dull green bag",new Stock(4,"dotted orange bag"),new Stock(5,"dotted coral bag"),new Stock(5,"pale tan bag"),new Stock(1,"faded beige bag")),
				new BagRule("faded bronze bag",new Stock(3,"shiny blue bag")),
				new BagRule("faded tan bag",new Stock(2,"pale bronze bag")),
				new BagRule("plaid cyan bag",new Stock(4,"clear maroon bag"),new Stock(5,"dark aqua bag"),new Stock(1,"bright fuchsia bag"),new Stock(2,"plaid bronze bag")),
				new BagRule("striped bronze bag",new Stock(1,"vibrant silver bag"),new Stock(1,"dim red bag"),new Stock(3,"vibrant maroon bag")),
				new BagRule("dotted blue bag",new Stock(2,"vibrant tan bag")),
				new BagRule("drab gold bag",new Stock(2,"dim crimson bag"),new Stock(3,"faded tomato bag"),new Stock(2,"drab magenta bag")),
				new BagRule("faded cyan bag",new Stock(3,"dotted lavender bag"),new Stock(4,"mirrored plum bag"),new Stock(2,"plaid olive bag"),new Stock(1,"muted lime bag")),
				new BagRule("dark green bag",new Stock(5,"dim crimson bag"),new Stock(4,"vibrant aqua bag"),new Stock(1,"pale beige bag"),new Stock(5,"faded aqua bag")),
				new BagRule("posh green bag",new Stock(4,"dim maroon bag"),new Stock(3,"faded black bag"),new Stock(5,"wavy yellow bag")),
				new BagRule("pale brown bag",new Stock(3,"dull coral bag")),
				new BagRule("light yellow bag",new Stock(5,"vibrant black bag")),
				new BagRule("mirrored coral bag",new Stock(1,"wavy teal bag"),new Stock(5,"plaid gold bag"),new Stock(4,"muted crimson bag"),new Stock(3,"clear teal bag")),
				new BagRule("plaid blue bag",new Stock(2,"vibrant tomato bag"),new Stock(3,"light fuchsia bag"),new Stock(1,"shiny tomato bag"),new Stock(1,"faded red bag")),
				new BagRule("light gold bag",new Stock(1,"plaid chartreuse bag"),new Stock(3,"plaid tan bag")),
				new BagRule("light brown bag",new Stock(4,"light green bag"),new Stock(1,"shiny orange bag")),
				new BagRule("light gray bag",new Stock(3,"drab magenta bag")),
				new BagRule("wavy teal bag",new Stock(2,"drab tan bag")),
				new BagRule("drab tan bag",new Stock(5,"light tomato bag"),new Stock(3,"muted tan bag"),new Stock(3,"shiny blue bag"),new Stock(1,"dull white bag")),
				new BagRule("plaid beige bag",new Stock(5,"muted crimson bag"),new Stock(5,"faded white bag"),new Stock(5,"dull aqua bag")),
				new BagRule("striped fuchsia bag",new Stock(5,"dim plum bag"),new Stock(1,"faded gray bag"),new Stock(2,"pale turquoise bag"),new Stock(3,"dull teal bag")),
				new BagRule("vibrant red bag",new Stock(3,"dim aqua bag"),new Stock(5,"plaid green bag")),
				new BagRule("faded crimson bag",new Stock(3,"faded brown bag")),
				new BagRule("muted aqua bag",new Stock(5,"muted purple bag"),new Stock(5,"drab tan bag"),new Stock(2,"shiny magenta bag")),
				new BagRule("pale blue bag",new Stock(4,"pale lavender bag")),
				new BagRule("wavy tomato bag",new Stock(2,"striped plum bag"),new Stock(4,"dull aqua bag"),new Stock(3,"light tan bag"),new Stock(4,"pale black bag")),
				new BagRule("drab fuchsia bag",new Stock(2,"muted purple bag"),new Stock(2,"striped lime bag"),new Stock(4,"clear white bag"),new Stock(1,"bright turquoise bag")),
				new BagRule("dim crimson bag",new Stock(3,"light tomato bag"),new Stock(5,"muted crimson bag"),new Stock(4,"plaid bronze bag"),new Stock(2,"faded tomato bag")),
				new BagRule("faded turquoise bag",new Stock(5,"posh yellow bag"),new Stock(3,"plaid chartreuse bag")),
				new BagRule("vibrant indigo bag",new Stock(5,"bright turquoise bag")),
				new BagRule("mirrored turquoise bag",new Stock(4,"light lavender bag"),new Stock(2,"wavy turquoise bag"),new Stock(2,"wavy red bag")),
				new BagRule("posh turquoise bag",new Stock(4,"posh crimson bag")),
				new BagRule("vibrant white bag",new Stock(2,"dotted purple bag"),new Stock(5,"faded teal bag"),new Stock(4,"faded tomato bag"),new Stock(5,"dull aqua bag")),
				new BagRule("faded olive bag",new Stock(4,"bright bronze bag"),new Stock(2,"vibrant purple bag"),new Stock(3,"dotted violet bag")),
				new BagRule("posh orange bag",new Stock(4,"light green bag"),new Stock(5,"vibrant white bag"),new Stock(1,"shiny lime bag")),
				new BagRule("pale violet bag",new Stock(3,"drab indigo bag")),
				new BagRule("dotted indigo bag",new Stock(5,"bright coral bag"),new Stock(3,"plaid purple bag")),
				new BagRule("clear tan bag",new Stock(4,"dim plum bag"),new Stock(5,"vibrant purple bag")),
				new BagRule("vibrant orange bag",new Stock(3,"striped plum bag")),
				new BagRule("shiny violet bag",new Stock(5,"plaid cyan bag"),new Stock(5,"striped plum bag")),
				new BagRule("striped silver bag",new Stock(1,"clear yellow bag"),new Stock(3,"dotted green bag")),
				new BagRule("bright chartreuse bag",new Stock(5,"wavy tomato bag"),new Stock(2,"bright yellow bag")),
				new BagRule("vibrant plum bag",new Stock(3,"wavy yellow bag"),new Stock(5,"dim maroon bag"),new Stock(5,"plaid bronze bag")),
				new BagRule("clear maroon bag"),
				new BagRule("wavy orange bag",new Stock(3,"plaid aqua bag"),new Stock(1,"pale salmon bag")),
				new BagRule("wavy bronze bag",new Stock(5,"drab green bag"),new Stock(3,"dim plum bag"),new Stock(4,"mirrored lavender bag")),
				new BagRule("light indigo bag",new Stock(5,"dark aqua bag")),
				new BagRule("shiny bronze bag",new Stock(4,"vibrant magenta bag"),new Stock(2,"clear teal bag"),new Stock(4,"muted coral bag")),
				new BagRule("posh aqua bag",new Stock(2,"dotted green bag"),new Stock(4,"bright plum bag"),new Stock(1,"vibrant orange bag")),
				new BagRule("striped maroon bag",new Stock(5,"dotted beige bag"),new Stock(5,"light tomato bag")),
				new BagRule("bright crimson bag",new Stock(5,"vibrant beige bag"),new Stock(3,"faded teal bag"),new Stock(5,"mirrored white bag")),
				new BagRule("pale green bag",new Stock(4,"bright beige bag"),new Stock(2,"posh turquoise bag"),new Stock(3,"mirrored silver bag"),new Stock(5,"dim lime bag")),
				new BagRule("shiny black bag",new Stock(1,"faded yellow bag")),
				new BagRule("plaid brown bag",new Stock(4,"shiny salmon bag"),new Stock(2,"pale bronze bag"),new Stock(3,"dark orange bag")),
				new BagRule("dim lavender bag",new Stock(5,"dotted tan bag"),new Stock(4,"dull maroon bag"),new Stock(4,"striped plum bag"),new Stock(5,"light purple bag")),
				new BagRule("dim gray bag",new Stock(2,"faded tomato bag")),
				new BagRule("dotted plum bag",new Stock(4,"light gray bag"),new Stock(1,"bright turquoise bag"),new Stock(2,"drab maroon bag")),
				new BagRule("faded purple bag",new Stock(3,"vibrant cyan bag"),new Stock(3,"shiny aqua bag")),
				new BagRule("drab plum bag",new Stock(5,"pale chartreuse bag"),new Stock(1,"wavy crimson bag")),
				new BagRule("muted salmon bag",new Stock(3,"pale orange bag"),new Stock(4,"faded yellow bag"),new Stock(3,"dim tomato bag")),
				new BagRule("posh gold bag",new Stock(2,"drab chartreuse bag")),
				new BagRule("light teal bag",new Stock(2,"clear green bag"),new Stock(2,"light violet bag"),new Stock(1,"clear yellow bag"),new Stock(3,"bright turquoise bag")),
				new BagRule("clear tomato bag",new Stock(1,"posh aqua bag"),new Stock(1,"bright beige bag"),new Stock(5,"pale coral bag"),new Stock(3,"mirrored crimson bag")),
				new BagRule("dull turquoise bag",new Stock(2,"plaid coral bag")),
				new BagRule("striped red bag",new Stock(1,"dotted green bag"),new Stock(2,"plaid olive bag"),new Stock(1,"clear crimson bag")),
				new BagRule("shiny plum bag",new Stock(4,"light indigo bag"),new Stock(4,"muted plum bag")),
				new BagRule("dull indigo bag",new Stock(3,"posh white bag"),new Stock(1,"posh green bag"),new Stock(1,"dull plum bag"),new Stock(5,"shiny black bag")),
				new BagRule("dotted coral bag",new Stock(1,"mirrored magenta bag"),new Stock(2,"bright maroon bag"),new Stock(1,"drab tomato bag")),
				new BagRule("drab indigo bag",new Stock(1,"dotted turquoise bag")),
				new BagRule("posh red bag",new Stock(4,"faded blue bag"),new Stock(2,"mirrored green bag")),
				new BagRule("wavy tan bag",new Stock(3,"shiny cyan bag"),new Stock(1,"striped gold bag"),new Stock(2,"dim silver bag"),new Stock(3,"plaid magenta bag")),
				new BagRule("dim chartreuse bag",new Stock(2,"clear bronze bag")),
				new BagRule("vibrant crimson bag",new Stock(3,"faded brown bag"),new Stock(2,"pale chartreuse bag")),
				new BagRule("plaid yellow bag",new Stock(3,"striped brown bag"),new Stock(1,"plaid white bag"),new Stock(4,"vibrant indigo bag")),
				new BagRule("posh fuchsia bag",new Stock(5,"faded bronze bag"),new Stock(3,"drab gray bag")),
				new BagRule("mirrored red bag",new Stock(3,"wavy lime bag"),new Stock(4,"bright tan bag"),new Stock(5,"faded white bag")),
				new BagRule("shiny coral bag",new Stock(4,"wavy yellow bag"),new Stock(2,"bright turquoise bag")),
				new BagRule("dull beige bag",new Stock(3,"posh aqua bag")),
				new BagRule("posh beige bag",new Stock(1,"pale maroon bag"),new Stock(4,"shiny teal bag"),new Stock(1,"clear lime bag")),
				new BagRule("posh maroon bag",new Stock(1,"muted olive bag"),new Stock(2,"dim black bag"),new Stock(1,"plaid cyan bag"),new Stock(3,"dim olive bag")),
				new BagRule("faded gray bag",new Stock(1,"vibrant tomato bag"),new Stock(4,"posh teal bag"),new Stock(5,"striped maroon bag")),
				new BagRule("dotted cyan bag",new Stock(4,"dull orange bag"),new Stock(2,"clear bronze bag"),new Stock(4,"posh gray bag")),
				new BagRule("bright green bag",new Stock(5,"posh tomato bag"),new Stock(2,"wavy red bag")),
				new BagRule("clear lavender bag",new Stock(3,"dark plum bag"),new Stock(5,"dim salmon bag"),new Stock(2,"mirrored magenta bag"),new Stock(3,"plaid silver bag")),
				new BagRule("muted fuchsia bag",new Stock(5,"pale cyan bag")),
				new BagRule("dark yellow bag",new Stock(3,"plaid orange bag"),new Stock(5,"pale lime bag"),new Stock(2,"pale red bag")),
				new BagRule("bright turquoise bag",new Stock(2,"wavy yellow bag")),
				new BagRule("light bronze bag",new Stock(4,"light purple bag")),
				new BagRule("clear orange bag",new Stock(3,"dotted purple bag"),new Stock(4,"plaid fuchsia bag"),new Stock(1,"shiny lime bag")),
				new BagRule("striped orange bag",new Stock(4,"striped red bag"),new Stock(1,"dark bronze bag")),
				new BagRule("clear brown bag",new Stock(3,"light lavender bag"),new Stock(1,"dim plum bag"),new Stock(5,"shiny gray bag")),
				new BagRule("wavy lavender bag",new Stock(1,"pale gray bag"),new Stock(2,"wavy white bag"),new Stock(3,"bright white bag")),
				new BagRule("bright bronze bag",new Stock(2,"shiny turquoise bag"),new Stock(1,"vibrant indigo bag")),
				new BagRule("dull cyan bag",new Stock(5,"plaid orange bag"),new Stock(4,"muted coral bag"),new Stock(2,"bright coral bag"),new Stock(2,"dark olive bag")),
				new BagRule("faded lime bag",new Stock(4,"faded yellow bag"),new Stock(1,"dim lavender bag")),
				new BagRule("shiny olive bag",new Stock(1,"muted olive bag"),new Stock(4,"mirrored turquoise bag"),new Stock(3,"plaid magenta bag")),
				new BagRule("mirrored tomato bag",new Stock(1,"wavy green bag"),new Stock(1,"dotted brown bag"),new Stock(5,"posh magenta bag")),
				new BagRule("striped cyan bag",new Stock(2,"dim teal bag"),new Stock(3,"bright bronze bag"),new Stock(3,"drab chartreuse bag"),new Stock(4,"posh salmon bag")),
				new BagRule("striped magenta bag",new Stock(2,"dark orange bag")),
				new BagRule("pale white bag",new Stock(1,"pale indigo bag")),
				new BagRule("striped plum bag",new Stock(3,"dim plum bag"),new Stock(4,"faded black bag"),new Stock(1,"faded brown bag")),
				new BagRule("faded brown bag",new Stock(4,"clear maroon bag")),
				new BagRule("mirrored indigo bag",new Stock(2,"wavy indigo bag"),new Stock(2,"dull fuchsia bag"),new Stock(5,"bright coral bag")),
				new BagRule("dark coral bag",new Stock(5,"dotted fuchsia bag")),
				new BagRule("dull fuchsia bag",new Stock(5,"pale turquoise bag"),new Stock(5,"dark purple bag"),new Stock(4,"light red bag")),
				new BagRule("clear chartreuse bag",new Stock(5,"dotted turquoise bag")),
				new BagRule("vibrant gray bag",new Stock(3,"plaid orange bag"),new Stock(2,"dotted teal bag")),
				new BagRule("bright fuchsia bag"),
				new BagRule("clear salmon bag",new Stock(4,"light lime bag"),new Stock(1,"muted black bag"),new Stock(4,"vibrant magenta bag"),new Stock(1,"drab yellow bag")),
				new BagRule("muted bronze bag",new Stock(3,"dull aqua bag"),new Stock(4,"striped turquoise bag")),
				new BagRule("striped beige bag",new Stock(3,"vibrant beige bag")),
				new BagRule("dim white bag",new Stock(1,"mirrored blue bag"),new Stock(1,"vibrant cyan bag"),new Stock(1,"plaid coral bag"),new Stock(5,"light yellow bag")),
				new BagRule("clear olive bag",new Stock(2,"faded teal bag"),new Stock(1,"vibrant orange bag"),new Stock(4,"dim bronze bag")),
				new BagRule("light purple bag",new Stock(4,"dull aqua bag"),new Stock(1,"light gray bag"),new Stock(2,"clear green bag"),new Stock(4,"light fuchsia bag")),
				new BagRule("mirrored white bag",new Stock(3,"faded tomato bag"),new Stock(5,"plaid cyan bag"),new Stock(2,"drab magenta bag")),
				new BagRule("drab silver bag",new Stock(2,"dim plum bag"),new Stock(5,"wavy yellow bag"),new Stock(2,"dull teal bag"),new Stock(3,"bright crimson bag")),
				new BagRule("dark maroon bag",new Stock(5,"mirrored purple bag"),new Stock(5,"light tomato bag")),
				new BagRule("posh lime bag",new Stock(2,"light indigo bag"),new Stock(3,"muted tan bag"),new Stock(3,"shiny coral bag")),
				new BagRule("pale crimson bag",new Stock(2,"dotted tan bag")),
				new BagRule("plaid turquoise bag",new Stock(4,"clear teal bag"),new Stock(1,"light lavender bag"),new Stock(1,"posh salmon bag"),new Stock(5,"light teal bag")),
				new BagRule("plaid lime bag",new Stock(5,"wavy gray bag"),new Stock(5,"dull magenta bag"),new Stock(3,"wavy yellow bag"),new Stock(1,"dim aqua bag")),
				new BagRule("pale silver bag",new Stock(4,"mirrored turquoise bag")),
				new BagRule("dull gold bag",new Stock(3,"mirrored gold bag"),new Stock(5,"vibrant purple bag"),new Stock(3,"light beige bag")),
				new BagRule("dark purple bag",new Stock(5,"wavy yellow bag")),
				new BagRule("faded lavender bag",new Stock(5,"posh bronze bag"),new Stock(2,"vibrant violet bag"),new Stock(5,"drab maroon bag"),new Stock(3,"wavy bronze bag")),
				new BagRule("dull crimson bag",new Stock(3,"muted red bag"),new Stock(3,"muted brown bag")),
				new BagRule("bright cyan bag",new Stock(3,"mirrored chartreuse bag"),new Stock(5,"light fuchsia bag"),new Stock(2,"light tan bag")),
				new BagRule("drab chartreuse bag",new Stock(5,"muted green bag"),new Stock(1,"drab olive bag"),new Stock(4,"clear beige bag")),
				new BagRule("dull gray bag",new Stock(5,"posh fuchsia bag")),
				new BagRule("bright black bag",new Stock(5,"faded brown bag"),new Stock(3,"dim aqua bag"),new Stock(4,"bright violet bag")),
				new BagRule("faded beige bag",new Stock(5,"bright teal bag"),new Stock(4,"faded crimson bag"),new Stock(3,"plaid teal bag")),
				new BagRule("posh purple bag",new Stock(3,"shiny purple bag"),new Stock(3,"plaid turquoise bag")),
				new BagRule("plaid white bag",new Stock(1,"dotted cyan bag")),
				new BagRule("wavy magenta bag",new Stock(3,"vibrant tan bag"),new Stock(4,"posh brown bag"),new Stock(4,"bright tan bag")),
				new BagRule("dim tomato bag",new Stock(3,"drab lime bag"),new Stock(4,"vibrant tomato bag")),
				new BagRule("mirrored maroon bag",new Stock(3,"drab coral bag")));
		// Part one
		Map<String, List<String>> bagContainedByMap = new LinkedHashMap<String, List<String>>();
		for (BagRule bagRule : input) {
			for (String innerBag : bagRule.innermostBags) {
				if (bagContainedByMap.containsKey(innerBag)) {
					bagContainedByMap.get(innerBag).add(bagRule.outermostBag);
				} else {					
					bagContainedByMap.put(innerBag, new ArrayList<String>());
					bagContainedByMap.get(innerBag).add(bagRule.outermostBag);
					
				}			}
		}
		List<String> list = bagContainedByMap.get("shiny gold bag");
		List<String> outerLevel = removeDuplicate(list);
		assertEquals(getOuterLevel(bagContainedByMap, Arrays.asList("shiny gold bag")), Arrays.asList("dotted violet bag","faded aqua bag","striped lime bag","striped turquoise bag","clear gray bag","plaid teal bag","muted magenta bag","dim violet bag"));
		assertEquals(getOuterLevel(bagContainedByMap, Arrays.asList("dotted violet bag")), Arrays.asList("striped aqua bag","pale turquoise bag","faded aqua bag","mirrored chartreuse bag","posh cyan bag","light turquoise bag","faded olive bag"));
		List<String> innerLevel;
		for (int i = 0; i < 10; i++) {			
			innerLevel = outerLevel;
			outerLevel = getOuterLevel(bagContainedByMap, innerLevel);
			outerLevel.addAll(innerLevel);
			outerLevel = removeDuplicate(outerLevel);
			System.out.println(outerLevel.size());
		} 
		System.err.println();
		
		// Part two
		BagRule shinyGoldBagRule = findBagRule("shiny gold bag", input);
		int count = shinyGoldBagRule.innermostBags.size();
		List<String> bags = shinyGoldBagRule.innermostBags;
		for (int i = 0; i < 10; i++) {
			bags = getAllBags(getInnerRules(bags, input));
			count += bags.size();
			System.out.println(count);			
		}
	}
	
	private List<BagRule> getInnerRules(List<String> list, List<BagRule> input) {
		List<BagRule> result = new ArrayList<BagRule>();
		for (String bag : list) {
			result.add(findBagRule(bag, input));
		}
		return result;
	}
	
	private List<String> getAllBags(List<BagRule> rules) {
		List<String> result = new ArrayList<String>();
		for (BagRule rule : rules) {
			result.addAll(rule.innermostBags);
		}
		return result;
	}
	
	private BagRule findBagRule(final String outerBag, List<BagRule> list) {
		return Iterables.find(list, new Predicate<BagRule>() {
			public boolean apply(BagRule arg0) {
				return outerBag.equals(arg0.outermostBag);
			}
		}, null);
	}
	
	private List<String> getOuterLevel(Map<String, List<String>> map, List<String> bags) {
		List<String> outerLevel = new ArrayList<String>();
		for (String string : bags) {
			if (map.containsKey(string)) {
				outerLevel.addAll(map.get(string));				
			}
		}
		return removeDuplicate(outerLevel);
	}

	private <T> List<T> removeDuplicate(List<T> list) {
		return new ArrayList<T>(new LinkedHashSet<T>(list));
	}
	
	class BagRule {
		String outermostBag;
		List<String> innermostBags;
		BagRule(String outemostBag) {
			this.outermostBag = outemostBag;
			this.innermostBags = Arrays.asList();
		}
		BagRule(String outermostBag, Stock... stocks) {
			this.outermostBag = outermostBag;
			this.innermostBags = new ArrayList<String>();
			for (Stock stock : stocks) {
				for (int i = 0; i < stock.n; i++) {
					this.innermostBags.add(stock.bag);					
				}
			}
		}
	}
	class Stock {
		int n;
		String bag;
		Stock(int n, String bag) {
			this.n = n;
			this.bag = bag;
		}
	}
}
